from fastapi import APIRouter,Depends,HTTPException,Header
from pydantic import BaseModel
from go_hotel.security.deps import admin_principal
from go_hotel.security.service import Principal
from go_hotel.services.hosted_direct_booking import hosted_direct_booking_service as svc
from go_hotel.services.aoluguya_inventory import configure_aoluguya
from go_hotel.services.hosted_content_acceptance import hosted_content_acceptance_service as content_svc
from go_hotel.services.hosted_reservation_operations import hosted_reservation_operations_service as ops_svc
from go_hotel.services.hosted_frontdesk_uat import hosted_frontdesk_uat_service as fd_svc
from go_hotel.services.alipay_safeguarded_settlement import alipay_safeguarded_settlement_service as pay_svc
from go_hotel.services.guest_stay_fulfillment import guest_stay_fulfillment_service as stay_svc
from go_hotel.services.post_stay_dispute import post_stay_dispute_service as dispute_svc
router=APIRouter(tags=['go-hosted-direct-booking-pilot'])
class Payload(BaseModel):model_config={'extra':'allow'}
def call(fn,*a):
 try:return {'data':fn(*a)}
 except ValueError as e:raise HTTPException(409,detail=str(e))
@router.get('/v1/direct/{slug}')
def page(slug:str):return call(svc.page,slug)
@router.post('/v1/direct/{slug}/reservations')
def reserve(slug:str,b:Payload,idempotency_key:str=Header(alias='Idempotency-Key')):return call(svc.reserve,slug,b.model_dump(exclude_none=True),idempotency_key)
@router.get('/v1/direct/reservations/{reservation_id}')
def status(reservation_id:str):return call(svc.status,reservation_id)
@router.get('/internal/v1/hosted-direct/dashboard')
def dashboard(p:Principal=Depends(admin_principal)):return {'data':svc.dashboard()}
@router.post('/internal/v1/hosted-direct/aoluguya/configure')
def configure(p:Principal=Depends(admin_principal)):return call(configure_aoluguya)
@router.post('/internal/v1/hosted-direct/hotels')
def hotel(b:Payload,p:Principal=Depends(admin_principal)):return call(svc.create_hotel,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/hosted-direct/hotels/{hotel_id}/offers')
def offer(hotel_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(svc.upsert_offer,hotel_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/hosted-direct/hotels/{hotel_id}/publish')
def publish(hotel_id:str,p:Principal=Depends(admin_principal)):return call(svc.publish,hotel_id,p.user_id)
@router.post('/internal/v1/hosted-direct/reservations/{reservation_id}/decision')
def decision(reservation_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(svc.hotel_decision,reservation_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/hosted-direct/reservations/{reservation_id}/cancel')
def cancel(reservation_id:str,p:Principal=Depends(admin_principal)):return call(svc.cancel,reservation_id,p.user_id)
@router.post('/internal/v1/hosted-direct/hotels/{hotel_id}/content-snapshots')
def content_snapshot(hotel_id:str,p:Principal=Depends(admin_principal)):return call(content_svc.snapshot,hotel_id,p.user_id)
@router.post('/internal/v1/hosted-direct/content-snapshots/{snapshot_id}/approve')
def content_approve(snapshot_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(content_svc.approve,snapshot_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/hosted-direct/hotels/{hotel_id}/media-assets')
def media_asset(hotel_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(content_svc.media,hotel_id,b.model_dump(exclude_none=True),p.user_id)
@router.get('/internal/v1/hosted-direct/hotels/{hotel_id}/operations-gate')
def operations_gate(hotel_id:str,p:Principal=Depends(admin_principal)):return call(content_svc.gate,hotel_id)
@router.post('/v1/direct/{slug}/managed-reservations')
def managed_reserve(slug:str,b:Payload,idempotency_key:str=Header(alias='Idempotency-Key')):return call(ops_svc.reserve,slug,b.model_dump(exclude_none=True),idempotency_key,'GO_PAGE','CONSUMER')
@router.post('/internal/v1/hosted-direct/hotels/{hotel_id}/calendar/bootstrap')
def calendar_bootstrap(hotel_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(ops_svc.bootstrap_calendar,hotel_id,b.model_dump(exclude_none=True))
@router.put('/internal/v1/hosted-direct/inventory-pools/{pool_id}/days/{stay_date}')
def inventory_day(pool_id:str,stay_date:str,b:Payload,p:Principal=Depends(admin_principal)):return call(ops_svc.set_inventory_day,pool_id,stay_date,b.model_dump(exclude_none=True))
@router.put('/internal/v1/hosted-direct/rate-variants/{variant_id}/days/{stay_date}')
def rate_day(variant_id:str,stay_date:str,b:Payload,p:Principal=Depends(admin_principal)):return call(ops_svc.set_rate_day,variant_id,stay_date,b.model_dump(exclude_none=True))
@router.post('/internal/v1/hosted-direct/{slug}/phone-reservations')
def phone_reserve(slug:str,b:Payload,idempotency_key:str=Header(alias='Idempotency-Key'),p:Principal=Depends(admin_principal)):return call(ops_svc.reserve,slug,b.model_dump(exclude_none=True),idempotency_key,'PHONE',p.user_id)
@router.post('/internal/v1/hosted-direct/managed-reservations/{reservation_id}/actions')
def managed_action(reservation_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(ops_svc.action,reservation_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/hosted-direct/managed-reservations/{reservation_id}/reschedule')
def managed_reschedule(reservation_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(ops_svc.reschedule,reservation_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/hosted-direct/managed-reservations/expire-pending')
def expire_pending(p:Principal=Depends(admin_principal)):return call(ops_svc.expire_pending,p.user_id)
@router.get('/internal/v1/hosted-direct/hotels/{hotel_id}/operations-dashboard')
def operations_dashboard(hotel_id:str,p:Principal=Depends(admin_principal)):return call(ops_svc.dashboard,hotel_id)
@router.post('/internal/v1/hosted-direct/hotels/{hotel_id}/staff-roles')
def staff_role(hotel_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(fd_svc.assign_role,hotel_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/hosted-direct/hotels/{hotel_id}/shift-handovers')
def shift_handover(hotel_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(fd_svc.handover,hotel_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/hosted-direct/reservations/{reservation_id}/guest-access')
def guest_access(reservation_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(fd_svc.guest_view,reservation_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/hosted-direct/{slug}/governed-phone-reservations')
def governed_phone(slug:str,b:Payload,idempotency_key:str=Header(alias='Idempotency-Key'),p:Principal=Depends(admin_principal)):return call(fd_svc.phone_reserve,slug,b.model_dump(exclude_none=True),idempotency_key,p.user_id)
@router.post('/internal/v1/hosted-direct/reservations/{reservation_id}/action-approvals')
def action_request(reservation_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(fd_svc.request_action,reservation_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/hosted-direct/action-approvals/{approval_id}/approve')
def action_approve(approval_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(fd_svc.approve_action,approval_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/hosted-direct/hotels/{hotel_id}/sla-escalations/run')
def sla_escalate(hotel_id:str,p:Principal=Depends(admin_principal)):return call(fd_svc.escalate,hotel_id,p.user_id)
@router.get('/internal/v1/hosted-direct/reservations/{reservation_id}/arrival-voucher')
def arrival_voucher(reservation_id:str,p:Principal=Depends(admin_principal)):return call(fd_svc.voucher,reservation_id,p.user_id)
@router.post('/internal/v1/hosted-direct/hotels/{hotel_id}/daily-closes')
def daily_close(hotel_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(fd_svc.daily_close,hotel_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/hosted-direct/hotels/{hotel_id}/uat-scenarios')
def uat_scenario(hotel_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(fd_svc.uat,hotel_id,b.model_dump(exclude_none=True),p.user_id)
@router.get('/internal/v1/hosted-direct/hotels/{hotel_id}/frontdesk-command-center')
def frontdesk_command_center(hotel_id:str,p:Principal=Depends(admin_principal)):return call(fd_svc.dashboard,hotel_id)
@router.post('/internal/v1/alipay/hotels/{hotel_id}/merchant-binding')
def alipay_merchant(hotel_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(pay_svc.bind_merchant,hotel_id,b.model_dump(exclude_none=True))
@router.post('/internal/v1/alipay/merchant-bindings/{binding_id}/credentials')
def alipay_credentials(binding_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(pay_svc.credentials,binding_id,b.model_dump(exclude_none=True))
@router.get('/internal/v1/alipay/hotels/{hotel_id}/activation-gate')
def alipay_gate(hotel_id:str,p:Principal=Depends(admin_principal)):return call(pay_svc.gate,hotel_id)
@router.post('/internal/v1/alipay/reservations/{reservation_id}/authorizations')
def alipay_authorize(reservation_id:str,b:Payload,idempotency_key:str=Header(alias='Idempotency-Key'),p:Principal=Depends(admin_principal)):return call(pay_svc.authorize,reservation_id,b.model_dump(exclude_none=True),idempotency_key)
@router.post('/internal/v1/alipay/authorizations/{authorization_id}/release')
def alipay_release(authorization_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(pay_svc.release,authorization_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/alipay/authorizations/{authorization_id}/fulfill')
def alipay_fulfill(authorization_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(pay_svc.fulfill,authorization_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/alipay/authorizations/{authorization_id}/capture')
def alipay_capture(authorization_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(pay_svc.capture,authorization_id,b.model_dump(exclude_none=True))
@router.post('/internal/v1/alipay/authorizations/{authorization_id}/adjustments')
def alipay_adjustment(authorization_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(pay_svc.request_adjustment,authorization_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/alipay/adjustments/{approval_id}/approve')
def alipay_adjustment_approve(approval_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(pay_svc.approve_adjustment,approval_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/v1/webhooks/alipay/safeguarded-settlement')
def alipay_webhook(b:Payload,x_alipay_signature:str=Header(alias='X-Alipay-Signature')):return call(pay_svc.webhook,b.model_dump(exclude_none=True),x_alipay_signature)
@router.post('/internal/v1/alipay/authorizations/{authorization_id}/reconcile')
def alipay_reconcile(authorization_id:str,p:Principal=Depends(admin_principal)):return call(pay_svc.reconcile,authorization_id)
@router.post('/internal/v1/stays/reservations/{reservation_id}')
def stay_create(reservation_id:str,p:Principal=Depends(admin_principal)):return call(stay_svc.create,reservation_id,p.user_id)
@router.post('/internal/v1/stays/{stay_id}/identity-evidence')
def stay_identity(stay_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(stay_svc.identity,stay_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/stays/{stay_id}/arrive')
def stay_arrive(stay_id:str,p:Principal=Depends(admin_principal)):return call(stay_svc.arrive,stay_id,p.user_id)
@router.post('/internal/v1/stays/{stay_id}/room-assignment')
def stay_room(stay_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(stay_svc.assign_room,stay_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/stays/{stay_id}/check-in')
def stay_checkin(stay_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(stay_svc.check_in,stay_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/stays/{stay_id}/extend')
def stay_extend(stay_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(stay_svc.extend,stay_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/stays/{stay_id}/check-out')
def stay_checkout(stay_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(stay_svc.checkout,stay_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/stays/{stay_id}/no-show')
def stay_noshow(stay_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(stay_svc.no_show,stay_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/stays/{stay_id}/disputes')
def stay_dispute(stay_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(stay_svc.dispute,stay_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/stays/{stay_id}/settlement-eligibility')
def stay_eligibility(stay_id:str,p:Principal=Depends(admin_principal)):return call(stay_svc.eligibility,stay_id)
@router.get('/internal/v1/stays/{stay_id}/timeline')
def stay_timeline(stay_id:str,p:Principal=Depends(admin_principal)):return call(stay_svc.timeline,stay_id)
@router.post('/internal/v1/post-stay/stays/{stay_id}/cases')
def dispute_open(stay_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(dispute_svc.open_case,stay_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/post-stay/cases/{case_id}/evidence')
def dispute_evidence(case_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(dispute_svc.evidence,case_id,b.model_dump(exclude_none=True))
@router.post('/internal/v1/post-stay/cases/{case_id}/responses')
def dispute_response(case_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(dispute_svc.respond,case_id,b.model_dump(exclude_none=True))
@router.post('/internal/v1/post-stay/cases/{case_id}/escalate')
def dispute_escalate(case_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(dispute_svc.escalate,case_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/post-stay/cases/{case_id}/mediation')
def dispute_mediate(case_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(dispute_svc.mediate,case_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/post-stay/cases/{case_id}/decisions')
def dispute_decision(case_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(dispute_svc.request_decision,case_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/post-stay/decisions/{decision_id}/approve')
def dispute_decision_approve(decision_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(dispute_svc.approve_decision,decision_id,b.model_dump(exclude_none=True),p.user_id)
@router.post('/internal/v1/post-stay/decisions/{decision_id}/refund-eligibility')
def refund_eligibility(decision_id:str,p:Principal=Depends(admin_principal)):return call(dispute_svc.refund_eligibility,decision_id)
@router.post('/internal/v1/post-stay/refund-eligibilities/{eligibility_id}/execute')
def refund_execute(eligibility_id:str,p:Principal=Depends(admin_principal)):return call(dispute_svc.execute_refund,eligibility_id)
@router.post('/internal/v1/post-stay/cases/{case_id}/reconcile')
def dispute_reconcile(case_id:str,p:Principal=Depends(admin_principal)):return call(dispute_svc.reconcile,case_id)
@router.post('/internal/v1/post-stay/cases/{case_id}/close')
def dispute_close(case_id:str,b:Payload,p:Principal=Depends(admin_principal)):return call(dispute_svc.close,case_id,b.model_dump(exclude_none=True),p.user_id)
