"""Sprint 4C witness independence governance and trust plane disaster recovery.
Revision ID: 0050_sprint4c
Revises: 0049_sprint4b
"""
from alembic import op
import sqlalchemy as sa
revision='0050_sprint4c';down_revision='0049_sprint4b';branch_labels=None;depends_on=None

def _immutable(table):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_TRUST_PLANE_DR_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_TRUST_PLANE_DR_EVIDENCE'); END;")
    elif d=='postgresql':
        op.execute("""CREATE OR REPLACE FUNCTION deny_trust_plane_dr_evidence_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'IMMUTABLE_TRUST_PLANE_DR_EVIDENCE'; END; $$ LANGUAGE plpgsql;""")
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_trust_plane_dr_evidence_mutation();")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_trust_plane_dr_evidence_mutation();")

def upgrade():
    op.create_table('journey_recovery_witness_operator',sa.Column('witness_operator_id',sa.String(64),primary_key=True),sa.Column('operator_key',sa.String(128),nullable=False,unique=True),sa.Column('organization_ref',sa.String(256),nullable=False),sa.Column('control_domain',sa.String(128),nullable=False),sa.Column('cloud_provider',sa.String(64),nullable=False),sa.Column('key_authority',sa.String(128),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_by',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_witness_independence_binding',sa.Column('witness_independence_binding_id',sa.String(64),primary_key=True),sa.Column('external_trust_witness_id',sa.String(64),nullable=False,unique=True),sa.Column('witness_operator_id',sa.String(64),nullable=False),sa.Column('environment',sa.String(16),nullable=False),sa.Column('region_key',sa.String(64),nullable=False),sa.Column('failure_domain',sa.String(128),nullable=False),sa.Column('cloud_provider',sa.String(64),nullable=False),sa.Column('key_authority',sa.String(128),nullable=False),sa.Column('evidence_reference',sa.String(256),nullable=False),sa.Column('bound_by',sa.String(64),nullable=False),sa.Column('bound_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_witness_independence_policy',sa.Column('witness_independence_policy_id',sa.String(64),primary_key=True),sa.Column('policy_key',sa.String(128),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('environment',sa.String(16),nullable=False),sa.Column('minimum_operator_quorum',sa.Integer(),nullable=False),sa.Column('minimum_failure_domains',sa.Integer(),nullable=False),sa.Column('minimum_cloud_providers',sa.Integer(),nullable=False),sa.Column('minimum_key_authorities',sa.Integer(),nullable=False),sa.Column('max_witnesses_per_operator',sa.Integer(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_by',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_witness_independence_assessment',sa.Column('witness_independence_assessment_id',sa.String(64),primary_key=True),sa.Column('witness_federation_id',sa.String(64),nullable=False),sa.Column('witness_independence_policy_id',sa.String(64),nullable=False),sa.Column('environment',sa.String(16),nullable=False),sa.Column('operator_count',sa.Integer(),nullable=False),sa.Column('failure_domain_count',sa.Integer(),nullable=False),sa.Column('cloud_provider_count',sa.Integer(),nullable=False),sa.Column('key_authority_count',sa.Integer(),nullable=False),sa.Column('effective_independent_quorum',sa.Integer(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('assessed_by',sa.String(64),nullable=False),sa.Column('assessed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_cross_operator_gossip',sa.Column('cross_operator_gossip_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('witness_operator_id',sa.String(64),nullable=False),sa.Column('region_key',sa.String(64),nullable=False),sa.Column('merkle_checkpoint_id',sa.String(64),nullable=False),sa.Column('tree_size',sa.Integer(),nullable=False),sa.Column('root_hash',sa.String(64),nullable=False),sa.Column('checkpoint_hash',sa.String(64),nullable=False),sa.Column('peer_digest',sa.String(64),nullable=False),sa.Column('evidence_reference',sa.String(256),nullable=False),sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_checkpoint_archive',sa.Column('checkpoint_archive_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('merkle_checkpoint_id',sa.String(64),nullable=False),sa.Column('tree_size',sa.Integer(),nullable=False),sa.Column('root_hash',sa.String(64),nullable=False),sa.Column('checkpoint_hash',sa.String(64),nullable=False),sa.Column('leaf_hashes_json',sa.JSON(),nullable=False),sa.Column('archive_hash',sa.String(64),nullable=False),sa.Column('storage_reference',sa.String(512),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('archived_by',sa.String(64),nullable=False),sa.Column('archived_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_trust_plane_disaster_incident',sa.Column('trust_plane_disaster_incident_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('failure_scope',sa.String(24),nullable=False),sa.Column('failure_domain_key',sa.String(128),nullable=False),sa.Column('affected_regions_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('severity',sa.String(16),nullable=False),sa.Column('drill_mode',sa.Boolean(),nullable=False),sa.Column('evidence_reference',sa.String(256),nullable=False),sa.Column('opened_by',sa.String(64),nullable=False),sa.Column('opened_at',sa.DateTime(timezone=True),nullable=False),sa.Column('recovered_at',sa.DateTime(timezone=True)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_trust_plane_rebuild',sa.Column('trust_plane_rebuild_id',sa.String(64),primary_key=True),sa.Column('trust_plane_disaster_incident_id',sa.String(64),nullable=False),sa.Column('checkpoint_archive_id',sa.String(64),nullable=False),sa.Column('target_region_key',sa.String(64),nullable=False),sa.Column('rebuilt_root_hash',sa.String(64),nullable=False),sa.Column('rebuilt_checkpoint_hash',sa.String(64),nullable=False),sa.Column('verification_state',sa.String(24),nullable=False),sa.Column('witness_independence_assessment_id',sa.String(64)),sa.Column('evidence_reference',sa.String(256),nullable=False),sa.Column('started_by',sa.String(64),nullable=False),sa.Column('started_at',sa.DateTime(timezone=True),nullable=False),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_trust_plane_recovery_drill',sa.Column('trust_plane_recovery_drill_id',sa.String(64),primary_key=True),sa.Column('trust_plane_disaster_incident_id',sa.String(64),nullable=False),sa.Column('trust_plane_rebuild_id',sa.String(64),nullable=False),sa.Column('environment',sa.String(16),nullable=False),sa.Column('recovery_time_seconds',sa.Integer(),nullable=False),sa.Column('result',sa.String(24),nullable=False),sa.Column('evidence_reference',sa.String(256),nullable=False),sa.Column('recorded_by',sa.String(64),nullable=False),sa.Column('recorded_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_witness_independence_assessment','journey_recovery_cross_operator_gossip','journey_recovery_checkpoint_archive','journey_recovery_trust_plane_rebuild','journey_recovery_trust_plane_recovery_drill']:_immutable(t)

def downgrade():
    for t in ['journey_recovery_trust_plane_recovery_drill','journey_recovery_trust_plane_rebuild','journey_recovery_trust_plane_disaster_incident','journey_recovery_checkpoint_archive','journey_recovery_cross_operator_gossip','journey_recovery_witness_independence_assessment','journey_recovery_witness_independence_policy','journey_recovery_witness_independence_binding','journey_recovery_witness_operator']:
        op.drop_table(t)
