"""Sprint 4K forecast calibration, accuracy and capacity governance.
Revision ID: 0058_sprint4k
Revises: 0057_sprint4j
"""
from alembic import op
import sqlalchemy as sa
revision='0058_sprint4k';down_revision='0057_sprint4j';branch_labels=None;depends_on=None

def imm(table):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_FORECAST_CALIBRATION_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_FORECAST_CALIBRATION_EVIDENCE'); END;")
    elif d=='postgresql':
        op.execute("""CREATE OR REPLACE FUNCTION deny_forecast_calibration_evidence_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'IMMUTABLE_FORECAST_CALIBRATION_EVIDENCE'; END; $$ LANGUAGE plpgsql;""")
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_forecast_calibration_evidence_mutation();")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_forecast_calibration_evidence_mutation();")

def upgrade():
    op.create_table('journey_recovery_risk_forecast_model_version',sa.Column('risk_forecast_model_version_id',sa.String(64),primary_key=True),sa.Column('model_key',sa.String(128),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('environment',sa.String(16),nullable=False),sa.Column('algorithm_key',sa.String(64),nullable=False),sa.Column('parameters_json',sa.JSON(),nullable=False),sa.Column('conservative_parameters_json',sa.JSON(),nullable=False),sa.Column('minimum_samples',sa.Integer(),nullable=False),sa.Column('max_mae_points',sa.Float(),nullable=False),sa.Column('max_brier_score',sa.Float(),nullable=False),sa.Column('max_false_positive_rate',sa.Float(),nullable=False),sa.Column('max_false_negative_rate',sa.Float(),nullable=False),sa.Column('max_capacity_drift_pct',sa.Float(),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('board_approver_one',sa.String(64)),sa.Column('board_approver_two',sa.String(64)),sa.Column('state',sa.String(32),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_forecast_outcome',sa.Column('risk_forecast_outcome_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('risk_forecast_id',sa.String(64),nullable=False),sa.Column('risk_forecast_model_version_id',sa.String(64)),sa.Column('horizon_hours',sa.Integer(),nullable=False),sa.Column('predicted_exposure_points',sa.Float(),nullable=False),sa.Column('predicted_breach_probability',sa.Float(),nullable=False),sa.Column('actual_exposure_points',sa.Float(),nullable=False),sa.Column('actual_breach',sa.Boolean(),nullable=False),sa.Column('absolute_error_points',sa.Float(),nullable=False),sa.Column('squared_probability_error',sa.Float(),nullable=False),sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_forecast_accuracy_assessment',sa.Column('risk_forecast_accuracy_assessment_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('risk_forecast_model_version_id',sa.String(64),nullable=False),sa.Column('horizon_hours',sa.Integer(),nullable=False),sa.Column('sample_count',sa.Integer(),nullable=False),sa.Column('mae_points',sa.Float(),nullable=False),sa.Column('brier_score',sa.Float(),nullable=False),sa.Column('false_positive_rate',sa.Float(),nullable=False),sa.Column('false_negative_rate',sa.Float(),nullable=False),sa.Column('mean_capacity_drift_pct',sa.Float(),nullable=False),sa.Column('calibration_error_pct',sa.Float(),nullable=False),sa.Column('accuracy_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_forecast_calibration',sa.Column('risk_forecast_calibration_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('risk_forecast_model_version_id',sa.String(64),nullable=False),sa.Column('horizon_hours',sa.Integer(),nullable=False),sa.Column('sample_count',sa.Integer(),nullable=False),sa.Column('predicted_breach_rate',sa.Float(),nullable=False),sa.Column('actual_breach_rate',sa.Float(),nullable=False),sa.Column('calibration_error_pct',sa.Float(),nullable=False),sa.Column('calibration_state',sa.String(24),nullable=False),sa.Column('valid_until',sa.DateTime(timezone=True),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_capacity_allocation_drift',sa.Column('risk_capacity_allocation_drift_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('risk_forecast_id',sa.String(64),nullable=False),sa.Column('dimension',sa.String(32),nullable=False),sa.Column('dimension_key',sa.String(128),nullable=False),sa.Column('allocated_capacity_points',sa.Float(),nullable=False),sa.Column('projected_exposure_points',sa.Float(),nullable=False),sa.Column('actual_exposure_points',sa.Float(),nullable=False),sa.Column('allocation_drift_pct',sa.Float(),nullable=False),sa.Column('drift_state',sa.String(24),nullable=False),sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_forecast_safety_control',sa.Column('risk_forecast_safety_control_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('risk_forecast_model_version_id',sa.String(64),nullable=False),sa.Column('control_mode',sa.String(32),nullable=False),sa.Column('source_accuracy_assessment_id',sa.String(64)),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('activated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('released_at',sa.DateTime(timezone=True)),sa.Column('release_evidence_reference',sa.String(256)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_forecast_calibration_event',sa.Column('risk_forecast_calibration_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('model_version_id',sa.String(64)),sa.Column('accuracy_assessment_id',sa.String(64)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_risk_forecast_outcome','journey_recovery_risk_forecast_accuracy_assessment','journey_recovery_risk_forecast_calibration','journey_recovery_risk_capacity_allocation_drift','journey_recovery_risk_forecast_calibration_event']: imm(t)

def downgrade():
    for t in ['journey_recovery_risk_forecast_calibration_event','journey_recovery_risk_forecast_safety_control','journey_recovery_risk_capacity_allocation_drift','journey_recovery_risk_forecast_calibration','journey_recovery_risk_forecast_accuracy_assessment','journey_recovery_risk_forecast_outcome','journey_recovery_risk_forecast_model_version']: op.drop_table(t)
