"""Sprint 4O model training lineage, feature registry and reproducible build governance.
Revision ID: 0062_sprint4o
Revises: 0061_sprint4n
"""
from alembic import op
import sqlalchemy as sa
revision='0062_sprint4o';down_revision='0061_sprint4n';branch_labels=None;depends_on=None

def imm(table):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_FORECAST_TRAINING_GOVERNANCE_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_FORECAST_TRAINING_GOVERNANCE_EVIDENCE'); END;")
    elif d=='postgresql':
        op.execute("""CREATE OR REPLACE FUNCTION deny_forecast_training_governance_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'IMMUTABLE_FORECAST_TRAINING_GOVERNANCE_EVIDENCE'; END; $$ LANGUAGE plpgsql;""")
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_forecast_training_governance_mutation();")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_forecast_training_governance_mutation();")

def upgrade():
    op.create_table('journey_recovery_forecast_training_policy',sa.Column('forecast_training_policy_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('minimum_training_rows',sa.Integer(),nullable=False),sa.Column('max_missing_rate',sa.Float(),nullable=False),sa.Column('max_duplicate_rate',sa.Float(),nullable=False),sa.Column('max_invalid_rate',sa.Float(),nullable=False),sa.Column('reproducibility_required',sa.Boolean(),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('approver_one',sa.String(64)),sa.Column('approver_two',sa.String(64)),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_feature_version',sa.Column('forecast_feature_version_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('feature_key',sa.String(128),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('data_type',sa.String(32),nullable=False),sa.Column('definition_json',sa.JSON(),nullable=False),sa.Column('transform_hash',sa.String(64),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_by',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_training_dataset_snapshot',sa.Column('training_dataset_snapshot_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('dataset_key',sa.String(128),nullable=False),sa.Column('snapshot_version',sa.Integer(),nullable=False),sa.Column('row_count',sa.Integer(),nullable=False),sa.Column('schema_hash',sa.String(64),nullable=False),sa.Column('content_hash',sa.String(64),nullable=False),sa.Column('source_refs_json',sa.JSON(),nullable=False),sa.Column('feature_version_ids_json',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_training_data_quality',sa.Column('training_data_quality_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('training_dataset_snapshot_id',sa.String(64),nullable=False),sa.Column('policy_id',sa.String(64),nullable=False),sa.Column('row_count',sa.Integer(),nullable=False),sa.Column('missing_rate',sa.Float(),nullable=False),sa.Column('duplicate_rate',sa.Float(),nullable=False),sa.Column('invalid_rate',sa.Float(),nullable=False),sa.Column('quality_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('assessed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_training_lineage',sa.Column('forecast_training_lineage_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('training_dataset_snapshot_id',sa.String(64),nullable=False),sa.Column('feature_version_ids_json',sa.JSON(),nullable=False),sa.Column('source_retraining_request_id',sa.String(64)),sa.Column('lineage_hash',sa.String(64),nullable=False),sa.Column('lineage_state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_training_manifest',sa.Column('forecast_training_manifest_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('training_lineage_id',sa.String(64),nullable=False),sa.Column('code_ref',sa.String(256),nullable=False),sa.Column('code_hash',sa.String(64),nullable=False),sa.Column('algorithm_key',sa.String(128),nullable=False),sa.Column('hyperparameters_json',sa.JSON(),nullable=False),sa.Column('random_seed',sa.Integer(),nullable=False),sa.Column('build_hash',sa.String(64),nullable=False),sa.Column('manifest_state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_reproducibility_check',sa.Column('forecast_reproducibility_check_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('training_manifest_id',sa.String(64),nullable=False),sa.Column('expected_build_hash',sa.String(64),nullable=False),sa.Column('reproduced_build_hash',sa.String(64),nullable=False),sa.Column('reproducibility_state',sa.String(24),nullable=False),sa.Column('evidence_reference',sa.String(256),nullable=False),sa.Column('checked_by',sa.String(64),nullable=False),sa.Column('checked_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_model_build_eligibility',sa.Column('forecast_model_build_eligibility_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('training_manifest_id',sa.String(64),nullable=False),sa.Column('data_quality_id',sa.String(64),nullable=False),sa.Column('reproducibility_check_id',sa.String(64),nullable=False),sa.Column('eligibility_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_training_governance_event',sa.Column('forecast_training_governance_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('challenger_model_version_id',sa.String(64)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_forecast_feature_version','journey_recovery_forecast_training_dataset_snapshot','journey_recovery_forecast_training_data_quality','journey_recovery_forecast_training_lineage','journey_recovery_forecast_training_manifest','journey_recovery_forecast_reproducibility_check','journey_recovery_forecast_model_build_eligibility','journey_recovery_forecast_training_governance_event']: imm(t)

def downgrade():
    for t in ['journey_recovery_forecast_training_governance_event','journey_recovery_forecast_model_build_eligibility','journey_recovery_forecast_reproducibility_check','journey_recovery_forecast_training_manifest','journey_recovery_forecast_training_lineage','journey_recovery_forecast_training_data_quality','journey_recovery_forecast_training_dataset_snapshot','journey_recovery_forecast_feature_version','journey_recovery_forecast_training_policy']: op.drop_table(t)
