"""Sprint 4T online segment performance and automatic challenger refresh. Revision ID: 0067_sprint4t Revises: 0066_sprint4s"""
from alembic import op
import sqlalchemy as sa
revision='0067_sprint4t';down_revision='0066_sprint4s';branch_labels=None;depends_on=None
def imm(t):
 if op.get_bind().dialect.name=='sqlite':
  op.execute(f"CREATE TRIGGER {t}_deny_update BEFORE UPDATE ON {t} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_ONLINE_SEGMENT_MODEL_EVIDENCE'); END;")
  op.execute(f"CREATE TRIGGER {t}_deny_delete BEFORE DELETE ON {t} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_ONLINE_SEGMENT_MODEL_EVIDENCE'); END;")
def upgrade():
 op.create_table('journey_recovery_forecast_online_segment_policy',sa.Column('forecast_online_segment_policy_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('minimum_segment_samples',sa.Integer(),nullable=False),sa.Column('max_segment_mae',sa.Float(),nullable=False),sa.Column('max_segment_rmse',sa.Float(),nullable=False),sa.Column('max_segment_brier',sa.Float(),nullable=False),sa.Column('consecutive_breaches_required',sa.Integer(),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('approver_one',sa.String(64)),sa.Column('approver_two',sa.String(64)),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_segment_performance_observation',sa.Column('forecast_segment_performance_observation_id',sa.String(64),primary_key=True),sa.Column('forecast_outcome_attribution_id',sa.String(64),nullable=False,unique=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('deployment_key',sa.String(128),nullable=False),sa.Column('model_version_id',sa.String(64),nullable=False),sa.Column('team_key',sa.String(128),nullable=False),sa.Column('risk_domain',sa.String(128),nullable=False),sa.Column('horizon_hours',sa.Integer(),nullable=False),sa.Column('absolute_error',sa.Float(),nullable=False),sa.Column('squared_error',sa.Float(),nullable=False),sa.Column('brier_score',sa.Float()),sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_segment_performance_assessment',sa.Column('forecast_segment_performance_assessment_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('deployment_key',sa.String(128),nullable=False),sa.Column('model_version_id',sa.String(64),nullable=False),sa.Column('team_key',sa.String(128),nullable=False),sa.Column('risk_domain',sa.String(128),nullable=False),sa.Column('horizon_hours',sa.Integer(),nullable=False),sa.Column('sample_count',sa.Integer(),nullable=False),sa.Column('mae',sa.Float(),nullable=False),sa.Column('rmse',sa.Float(),nullable=False),sa.Column('mean_brier_score',sa.Float()),sa.Column('performance_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('assessed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_automatic_refresh_trigger',sa.Column('forecast_automatic_refresh_trigger_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('source_segment_assessment_id',sa.String(64),nullable=False),sa.Column('retraining_request_id',sa.String(64)),sa.Column('trigger_state',sa.String(32),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evidence_reference',sa.String(512),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_online_segment_event',sa.Column('forecast_online_segment_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('segment_assessment_id',sa.String(64)),sa.Column('retraining_request_id',sa.String(64)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 for t in ['journey_recovery_forecast_segment_performance_observation','journey_recovery_forecast_segment_performance_assessment','journey_recovery_forecast_automatic_refresh_trigger','journey_recovery_forecast_online_segment_event']: imm(t)
def downgrade():
 for t in ['journey_recovery_forecast_online_segment_event','journey_recovery_forecast_automatic_refresh_trigger','journey_recovery_forecast_segment_performance_assessment','journey_recovery_forecast_segment_performance_observation','journey_recovery_forecast_online_segment_policy']: op.drop_table(t)
