"""Sprint 4U segment-targeted challenger remediation governance. Revision ID: 0068_sprint4u Revises: 0067_sprint4t"""
from alembic import op
import sqlalchemy as sa
revision='0068_sprint4u';down_revision='0067_sprint4t';branch_labels=None;depends_on=None
def imm(t):
 if op.get_bind().dialect.name=='sqlite':
  op.execute(f"CREATE TRIGGER {t}_deny_update BEFORE UPDATE ON {t} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_SEGMENT_REMEDIATION_EVIDENCE'); END;")
  op.execute(f"CREATE TRIGGER {t}_deny_delete BEFORE DELETE ON {t} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_SEGMENT_REMEDIATION_EVIDENCE'); END;")
def upgrade():
 op.create_table('journey_recovery_forecast_remediation_policy',sa.Column('forecast_remediation_policy_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('minimum_target_improvement_pct',sa.Float(),nullable=False),sa.Column('max_cross_segment_regression_pct',sa.Float(),nullable=False),sa.Column('minimum_validation_samples',sa.Integer(),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('approver_one',sa.String(64)),sa.Column('approver_two',sa.String(64)),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_remediation_target',sa.Column('forecast_remediation_target_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('retraining_request_id',sa.String(64),nullable=False,unique=True),sa.Column('source_segment_assessment_id',sa.String(64),nullable=False),sa.Column('champion_model_version_id',sa.String(64),nullable=False),sa.Column('team_key',sa.String(128),nullable=False),sa.Column('risk_domain',sa.String(128),nullable=False),sa.Column('horizon_hours',sa.Integer(),nullable=False),sa.Column('baseline_mae',sa.Float(),nullable=False),sa.Column('baseline_rmse',sa.Float(),nullable=False),sa.Column('baseline_brier',sa.Float()),sa.Column('required_improvement_pct',sa.Float(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_segment_validation',sa.Column('forecast_segment_validation_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('remediation_target_id',sa.String(64),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('team_key',sa.String(128),nullable=False),sa.Column('risk_domain',sa.String(128),nullable=False),sa.Column('horizon_hours',sa.Integer(),nullable=False),sa.Column('sample_count',sa.Integer(),nullable=False),sa.Column('challenger_mae',sa.Float(),nullable=False),sa.Column('improvement_pct',sa.Float(),nullable=False),sa.Column('validation_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_cross_segment_regression',sa.Column('forecast_cross_segment_regression_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('remediation_target_id',sa.String(64),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('segment_key',sa.String(256),nullable=False),sa.Column('baseline_mae',sa.Float(),nullable=False),sa.Column('challenger_mae',sa.Float(),nullable=False),sa.Column('regression_pct',sa.Float(),nullable=False),sa.Column('regression_state',sa.String(24),nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_remediation_assessment',sa.Column('forecast_remediation_assessment_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('remediation_target_id',sa.String(64),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('effectiveness_state',sa.String(32),nullable=False),sa.Column('target_improvement_pct',sa.Float(),nullable=False),sa.Column('max_cross_segment_regression_pct',sa.Float(),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('promotion_eligible',sa.Boolean(),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_remediation_event',sa.Column('forecast_remediation_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('remediation_target_id',sa.String(64)),sa.Column('challenger_model_version_id',sa.String(64)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 for t in ['journey_recovery_forecast_remediation_target','journey_recovery_forecast_segment_validation','journey_recovery_forecast_cross_segment_regression','journey_recovery_forecast_remediation_assessment','journey_recovery_forecast_remediation_event']: imm(t)
def downgrade():
 for t in ['journey_recovery_forecast_remediation_event','journey_recovery_forecast_remediation_assessment','journey_recovery_forecast_cross_segment_regression','journey_recovery_forecast_segment_validation','journey_recovery_forecast_remediation_target','journey_recovery_forecast_remediation_policy']:op.drop_table(t)
