"""Sprint 4W multi-segment remediation portfolio and unified promotion governance.
Revision ID: 0070_sprint4w
Revises: 0069_sprint4v
"""
from alembic import op
import sqlalchemy as sa
revision='0070_sprint4w';down_revision='0069_sprint4v';branch_labels=None;depends_on=None

def imm(t):
    if op.get_bind().dialect.name=='sqlite':
        op.execute(f"CREATE TRIGGER {t}_deny_update BEFORE UPDATE ON {t} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_MULTI_SEGMENT_PORTFOLIO_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {t}_deny_delete BEFORE DELETE ON {t} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_MULTI_SEGMENT_PORTFOLIO_EVIDENCE'); END;")

def upgrade():
    op.create_table('journey_recovery_forecast_remediation_portfolio',
        sa.Column('forecast_remediation_portfolio_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('champion_model_version_id',sa.String(64),nullable=False),sa.Column('target_ids_json',sa.JSON(),nullable=False),sa.Column('objectives_json',sa.JSON(),nullable=False),sa.Column('protected_segment_keys_json',sa.JSON(),nullable=False),sa.Column('portfolio_state',sa.String(32),nullable=False),sa.Column('created_by',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_segment_conflict',
        sa.Column('forecast_segment_conflict_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('portfolio_id',sa.String(64),nullable=False),sa.Column('target_a_id',sa.String(64),nullable=False),sa.Column('target_b_id',sa.String(64),nullable=False),sa.Column('conflict_state',sa.String(32),nullable=False),sa.Column('resolution_state',sa.String(24),nullable=False),sa.Column('conflict_penalty_pct',sa.Float(),nullable=False),sa.Column('shared_root_cause_json',sa.JSON(),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('assessed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_portfolio_candidate',
        sa.Column('forecast_portfolio_candidate_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('portfolio_id',sa.String(64),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('strategy',sa.String(24),nullable=False),sa.Column('covered_target_ids_json',sa.JSON(),nullable=False),sa.Column('candidate_state',sa.String(32),nullable=False),sa.Column('registered_by',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_portfolio_assessment',
        sa.Column('forecast_portfolio_assessment_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('portfolio_id',sa.String(64),nullable=False),sa.Column('portfolio_candidate_id',sa.String(64),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('must_fix_total',sa.Integer(),nullable=False),sa.Column('must_fix_passed',sa.Integer(),nullable=False),sa.Column('average_target_improvement_pct',sa.Float(),nullable=False),sa.Column('max_cross_segment_regression_pct',sa.Float(),nullable=False),sa.Column('conflict_penalty_pct',sa.Float(),nullable=False),sa.Column('portfolio_score',sa.Float(),nullable=False),sa.Column('assessment_state',sa.String(32),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_candidate_arbitration',
        sa.Column('forecast_candidate_arbitration_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('portfolio_id',sa.String(64),nullable=False),sa.Column('winner_candidate_id',sa.String(64)),sa.Column('winner_model_version_id',sa.String(64)),sa.Column('decision_state',sa.String(32),nullable=False),sa.Column('rankings_json',sa.JSON(),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('decided_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_portfolio_promotion_gate',
        sa.Column('forecast_portfolio_promotion_gate_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('portfolio_id',sa.String(64),nullable=False),sa.Column('portfolio_candidate_id',sa.String(64),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('arbitration_id',sa.String(64),nullable=False),sa.Column('gate_state',sa.String(32),nullable=False),sa.Column('promotion_eligible',sa.Boolean(),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_portfolio_event',
        sa.Column('forecast_portfolio_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('portfolio_id',sa.String(64)),sa.Column('portfolio_candidate_id',sa.String(64)),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_forecast_segment_conflict','journey_recovery_forecast_portfolio_assessment','journey_recovery_forecast_candidate_arbitration','journey_recovery_forecast_portfolio_promotion_gate','journey_recovery_forecast_portfolio_event']: imm(t)

def downgrade():
    for t in ['journey_recovery_forecast_portfolio_event','journey_recovery_forecast_portfolio_promotion_gate','journey_recovery_forecast_candidate_arbitration','journey_recovery_forecast_portfolio_assessment','journey_recovery_forecast_portfolio_candidate','journey_recovery_forecast_segment_conflict','journey_recovery_forecast_remediation_portfolio']:op.drop_table(t)
