"""Sprint 4X portfolio champion continuity and safe replacement.
Revision ID: 0071_sprint4x
Revises: 0070_sprint4w
"""
from alembic import op
import sqlalchemy as sa
revision='0071_sprint4x';down_revision='0070_sprint4w';branch_labels=None;depends_on=None

def imm(t):
    if op.get_bind().dialect.name=='sqlite':
        op.execute(f"CREATE TRIGGER {t}_deny_update BEFORE UPDATE ON {t} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_PORTFOLIO_CHAMPION_GOVERNANCE_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {t}_deny_delete BEFORE DELETE ON {t} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_PORTFOLIO_CHAMPION_GOVERNANCE_EVIDENCE'); END;")

def upgrade():
    op.create_table('journey_recovery_forecast_portfolio_champion_state',sa.Column('forecast_portfolio_champion_state_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('portfolio_id',sa.String(64),nullable=False),sa.Column('champion_model_version_id',sa.String(64),nullable=False),sa.Column('previous_stable_champion_model_version_id',sa.String(64)),sa.Column('objective_snapshot_json',sa.JSON(),nullable=False),sa.Column('champion_state',sa.String(40),nullable=False),sa.Column('assigned_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_champion_continuity_assessment',sa.Column('forecast_champion_continuity_assessment_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('champion_state_id',sa.String(64),nullable=False),sa.Column('champion_model_version_id',sa.String(64),nullable=False),sa.Column('portfolio_objective_score',sa.Float(),nullable=False),sa.Column('target_health_state',sa.String(24),nullable=False),sa.Column('protected_segment_state',sa.String(24),nullable=False),sa.Column('serving_health_state',sa.String(24),nullable=False),sa.Column('holdout_state',sa.String(24),nullable=False),sa.Column('continuity_state',sa.String(40),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('assessed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_champion_challenge',sa.Column('forecast_champion_challenge_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('portfolio_id',sa.String(64),nullable=False),sa.Column('champion_state_id',sa.String(64),nullable=False),sa.Column('current_champion_model_version_id',sa.String(64),nullable=False),sa.Column('portfolio_candidate_id',sa.String(64),nullable=False),sa.Column('candidate_model_version_id',sa.String(64),nullable=False),sa.Column('challenge_state',sa.String(32),nullable=False),sa.Column('opened_by',sa.String(64),nullable=False),sa.Column('opened_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_champion_candidate_comparison',sa.Column('forecast_champion_candidate_comparison_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('challenge_id',sa.String(64),nullable=False),sa.Column('champion_model_version_id',sa.String(64),nullable=False),sa.Column('candidate_model_version_id',sa.String(64),nullable=False),sa.Column('champion_portfolio_score',sa.Float(),nullable=False),sa.Column('candidate_portfolio_score',sa.Float(),nullable=False),sa.Column('improvement_pct',sa.Float(),nullable=False),sa.Column('protected_segment_safe',sa.Boolean(),nullable=False),sa.Column('generalization_pass',sa.Boolean(),nullable=False),sa.Column('serving_health_pass',sa.Boolean(),nullable=False),sa.Column('statistical_confidence_pass',sa.Boolean(),nullable=False),sa.Column('comparison_state',sa.String(32),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('compared_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_champion_replacement_decision',sa.Column('forecast_champion_replacement_decision_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('challenge_id',sa.String(64),nullable=False),sa.Column('comparison_id',sa.String(64),nullable=False),sa.Column('from_model_version_id',sa.String(64),nullable=False),sa.Column('to_model_version_id',sa.String(64),nullable=False),sa.Column('decision_state',sa.String(32),nullable=False),sa.Column('approved',sa.Boolean(),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('decided_by',sa.String(64),nullable=False),sa.Column('decided_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_champion_transition',sa.Column('forecast_champion_transition_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('replacement_decision_id',sa.String(64),nullable=False),sa.Column('from_model_version_id',sa.String(64),nullable=False),sa.Column('to_model_version_id',sa.String(64),nullable=False),sa.Column('transition_state',sa.String(40),nullable=False),sa.Column('canary_percentage',sa.Integer(),nullable=False),sa.Column('previous_stable_champion_model_version_id',sa.String(64),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('transitioned_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_champion_governance_event',sa.Column('forecast_champion_governance_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('champion_state_id',sa.String(64)),sa.Column('challenge_id',sa.String(64)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_forecast_champion_continuity_assessment','journey_recovery_forecast_champion_candidate_comparison','journey_recovery_forecast_champion_replacement_decision','journey_recovery_forecast_champion_transition','journey_recovery_forecast_champion_governance_event']: imm(t)

def downgrade():
    for t in ['journey_recovery_forecast_champion_governance_event','journey_recovery_forecast_champion_transition','journey_recovery_forecast_champion_replacement_decision','journey_recovery_forecast_champion_candidate_comparison','journey_recovery_forecast_champion_challenge','journey_recovery_forecast_champion_continuity_assessment','journey_recovery_forecast_portfolio_champion_state']: op.drop_table(t)
