const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm');
const fixture=require('./registration_terms_fixture.cjs');
function setup(){const ctx={document:{}};vm.createContext(ctx);fixture.install(ctx);return {ctx,container:fixture.element()}}
async function mount(s,policy=fixture.policy,document=fixture.document,extra={}){return s.ctx.GORegistrationTerms.mount({container:s.container,policy,request:async()=>document,...extra})}
test('approved terms render full body as text, never interpreted markup',async()=>{const s=setup(),doc={...fixture.document,content:'<script>alert(1)</script>\n完整正文'};const result=await mount(s,fixture.policy,doc);assert.equal(result.enabled,true);assert.equal(s.container.children[0].children[1].textContent,doc.content);assert.equal(s.container.children[0].children[1].innerHTML,undefined);assert.equal(result.hashes[doc.id],doc.sha256)});
test('draft documents remain readable but never enable consent even if policy enabled',async()=>{const s=setup(),doc={...fixture.document,status:'DRAFT'};const result=await mount(s,{...fixture.policy,documents:[doc]},doc);assert.equal(result.enabled,false);assert.match(s.container.children[0].children[0].textContent,/草稿/);assert.match(s.container.children[1].textContent,/暂不能/)});
test('policy closed overrides all approved documents',async()=>{assert.equal((await mount(setup(),{...fixture.policy,acceptance_enabled:false})).enabled,false)});
test('changed document hash fails closed',async()=>{await assert.rejects(mount(setup(),fixture.policy,{...fixture.document,sha256:'b'.repeat(64)}),/更新/)});
test('changed document version fails closed',async()=>{await assert.rejects(mount(setup(),fixture.policy,{...fixture.document,version:'v2'}),/更新/)});
test('missing and duplicate documents never enable consent',async()=>{await assert.rejects(mount(setup(),{...fixture.policy,documents:[]}),/尚未提供/);await assert.rejects(mount(setup(),{...fixture.policy,documents:[fixture.document,fixture.document]}),/不完整/)});
test('body load failure never returns enabled consent',async()=>{const s=setup();await assert.rejects(mount(s,fixture.policy,fixture.document,{request:async()=>{throw Error('offline')}}),/offline/);assert.equal(s.container.children.length,0)});
test('unexpected content URL is never fetched',async()=>{let fetched=false;await assert.rejects(mount(setup(),{...fixture.policy,documents:[{...fixture.document,content_url:'https://foreign.test/'}]},fixture.document,{request:async()=>{fetched=true}}),/地址无效/);assert.equal(fetched,false)});
test('navigation during document load cannot write detached container',async()=>{const s=setup();const result=await mount(s,fixture.policy,fixture.document,{isCurrent:()=>false});assert.equal(result,null);assert.equal(s.container.children.length,0)});
test('unlisted terms or blank content fail closed',async()=>{await assert.rejects(mount(setup(),{...fixture.policy,term_hashes:{...fixture.policy.term_hashes,other:'b'.repeat(64)}}),/清单不完整/);await assert.rejects(mount(setup(),fixture.policy,{...fixture.document,content:' '}),/正文缺失/)});
