import React,{useEffect,useMemo,useState}from'react';
import{Alert,Linking,ScrollView,Text,TextInput,View,StyleSheet,Pressable}from'react-native';
import{GO,screen}from'../design';
import{TopBar,Btn,StatusPill}from'../components/GO';
import{api}from'../api/client';

const manualSources=[['SHARE_TO_GO','Share to GO'],['SCREENSHOT_AI','截图 / 图片'],['PDF_AI','PDF'],['FILE_IMPORT','文件'],['TEXT_IMPORT','粘贴文本']];
function parseText(raw:string){const lines=raw.split(/\n+/).map(x=>x.trim()).filter(Boolean);const map:any={姓名:'LEGAL_NAME',名字:'LEGAL_NAME',护照:'PASSPORT_NUMBER',手机号:'MOBILE',手机:'MOBILE',邮箱:'EMAIL',国籍:'NATIONALITY',生日:'DATE_OF_BIRTH'};const fields:any[]=[];let name='';for(const line of lines){const m=line.match(/^([^:：]{1,12})[:：]\s*(.+)$/);if(!m)continue;const ft=map[m[1].trim()];if(!ft)continue;if(ft==='LEGAL_NAME'){name=m[2].trim();continue}fields.push({entity_type:'PROFILE_FACT',traveler_ref:'me',field_type:ft,value:m[2].trim(),sensitive:['PASSPORT_NUMBER','DATE_OF_BIRTH'].includes(ft),confidence_bps:8500})}return [{entity_type:'TRAVELER',traveler_ref:'me',value:{full_name:name||'待确认旅客',relationship_type:'SELF',is_primary:true},confidence_bps:name?9000:5000},...fields]}

export default function TravelProfileImport({navigation}:any){
  const[src,setSrc]=useState('TEXT_IMPORT'),[raw,setRaw]=useState(''),[job,setJob]=useState<any>(null),[busy,setBusy]=useState(false),[err,setErr]=useState('');
  const[providers,setProviders]=useState<any[]>([]),[connections,setConnections]=useState<any[]>([]),[holderConfirmed,setHolderConfirmed]=useState(false),[connection,setConnection]=useState<any>(null);
  const pending=useMemo(()=>job?.items?.some((i:any)=>['NEEDS_REVIEW','EXTRACTED'].includes(i.status)&&!i.review_action),[job]);
  async function loadConnections(){try{const[o,c]=await Promise.all([api('/v1/consumer/profile/provider-connections/options'),api('/v1/consumer/profile/provider-connections')]);setProviders(o.data.providers||[]);setConnections(c.data.items||[])}catch(e:any){setErr(e.message)}}
  useEffect(()=>{loadConnections()},[]);
  async function startConnection(provider:any){if(!holderConfirmed){Alert.alert('请先确认','仅可连接或上传你本人有权使用的平台账号资料。');return}setBusy(true);setErr('');try{const r=await api('/v1/consumer/profile/provider-connections',{method:'POST',body:JSON.stringify({provider:provider.provider,method:'OFFICIAL_AUTHORIZATION',account_holder_confirmed:true})});setConnection(r.data);await loadConnections();if(r.data.authorization_url)await Linking.openURL(r.data.authorization_url)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
  async function extract(){setBusy(true);setErr('');try{const items=parseText(raw);if(items.length<=1)throw new Error('请按“姓名：... / 护照：... / 手机号：...”格式粘贴资料');let r;if(connection?.status==='AWAITING_USER_UPLOAD'){r=await api(`/v1/consumer/profile/provider-connections/${connection.connection_id}/upload`,{method:'POST',body:JSON.stringify({account_holder_confirmed:holderConfirmed,upload_kind:src,items})});setConnection(r.data);setJob(r.data.preview)}else{r=await api('/v1/consumer/profile/imports',{method:'POST',body:JSON.stringify({source_type:src,source_provider:'USER_PROVIDED',source_reference:'mobile_import',items})});setJob(r.data)}await loadConnections()}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
  async function review(item:any,action:'ACCEPT'|'REJECT'){setBusy(true);setErr('');try{const r=await api(`/v1/consumer/profile/imports/${job.import_job_id}/items/${item.import_item_id}/review`,{method:'POST',body:JSON.stringify({action})});setJob(r.data)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
  async function confirm(){if(!job||pending)return;setBusy(true);setErr('');try{const c=await api(`/v1/consumer/profile/imports/${job.import_job_id}/commit`,{method:'POST'});setJob(c.data);if(c.data.status==='COMMITTED')Alert.alert('已加入 GO','你确认的旅行资料已进入 Personal Travel Vault。',[{text:'查看资料库',onPress:()=>navigation.replace('TravelProfileVault')}]);else Alert.alert('仍需确认','请处理冲突或尚未确认的候选项。')}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
  async function removeConnection(id:string,deleteValues:boolean){setBusy(true);try{await api(deleteValues?`/v1/consumer/profile/provider-connections/${id}`:`/v1/consumer/profile/provider-connections/${id}/disconnect`,{method:deleteValues?'DELETE':'POST',...(deleteValues?{}:{body:JSON.stringify({delete_imported_values:false})})});await loadConnections();if(connection?.connection_id===id)setConnection(null)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
  return <View style={screen.root}><TopBar title="一键建立我的旅行资料" onBack={()=>navigation.goBack()}/><ScrollView contentContainerStyle={screen.content}>
    <Text style={screen.h1}>连接我的旅行平台</Text><Text style={screen.sub}>在平台自己的登录页授权，GO 不接收 OTA 密码、验证码、Cookie 或登录令牌。没有官方授权时可上传平台导出的资料。</Text>
    <View style={screen.card}><Pressable style={s.confirm} onPress={()=>setHolderConfirmed(!holderConfirmed)} accessibilityRole="checkbox" accessibilityState={{checked:holderConfirmed}}><View style={[s.box,holderConfirmed&&s.boxOn]}><Text style={s.tick}>{holderConfirmed?'✓':''}</Text></View><Text style={s.confirmText}>我确认这是本人账号，且有权将其中的旅行资料导入 GO</Text></Pressable>{providers.map(p=><View key={p.provider} style={s.provider}><View style={{flex:1}}><Text style={s.itemTitle}>{p.label}</Text><Text style={screen.sub}>{p.official_authorization_available?'可在平台页面授权':'可上传数据导出或截图'}</Text></View><Btn compact title={p.official_authorization_available?'连接':'选择'} onPress={()=>startConnection(p)} disabled={busy}/></View>)}</View>
    {connections.length?<View style={screen.card}><Text style={screen.h2}>已发起的连接</Text>{connections.map(c=><View key={c.connection_id} style={s.connection}><View style={{flex:1}}><Text style={s.itemTitle}>{c.provider}</Text><Text style={screen.sub}>{c.status}</Text></View><Pressable onPress={()=>removeConnection(c.connection_id,false)}><Text style={s.link}>解绑</Text></Pressable><Pressable onPress={()=>Alert.alert('删除连接和已导入资料？','此操作会清除该来源导入的可复用资料。',[{text:'取消',style:'cancel'},{text:'删除',style:'destructive',onPress:()=>removeConnection(c.connection_id,true)}])}><Text style={s.danger}>删除</Text></Pressable></View>)}</View>:null}
    <View style={screen.card}><Text style={screen.h2}>{connection?.status==='AWAITING_USER_UPLOAD'?`上传 ${connection.provider} 导出资料`:'其他导入方式'}</Text><View style={s.chips}>{manualSources.map(([k,n])=><Pressable key={k} style={[s.chip,src===k&&s.active]} onPress={()=>setSrc(k)}><Text style={[s.chipText,src===k&&s.activeText]}>{n}</Text></Pressable>)}</View><TextInput multiline value={raw} onChangeText={setRaw} placeholder={'可粘贴例如：\n姓名：陈某\n护照：E12345678\n手机号：13800000000'} style={s.input}/><Btn title={busy?'处理中...':'生成导入预览'} onPress={extract} disabled={busy}/></View>
    {job?<View style={screen.card}><View style={screen.row}><Text style={screen.h2}>导入前预览</Text><StatusPill text={job.status} tone={job.conflict_count?'amber':'green'}/></View><Text style={screen.sub}>逐项确认后才会写入资料库；敏感字段只显示掩码。</Text>{(job.items||[]).map((i:any)=><View key={i.import_item_id} style={s.item}><Text style={s.itemTitle}>{i.entity_type==='TRAVELER'?'旅客':i.field_type}</Text><Text style={screen.sub}>{i.preview_masked||'旅客实体'} · {i.confidence_bps/100}% · {i.status}</Text>{['NEEDS_REVIEW','EXTRACTED'].includes(i.status)&&!i.review_action?<View style={s.actions}><Btn compact secondary title="不导入" onPress={()=>review(i,'REJECT')}/><Btn compact title="确认" onPress={()=>review(i,'ACCEPT')}/></View>:<Text style={s.reviewed}>{i.review_action==='REJECT'?'已排除':'已确认'}</Text>}</View>)}<Btn title={pending?'请先逐项确认':'确认并加入 GO'} onPress={confirm} disabled={busy||pending}/></View>:null}
    {err?<View style={screen.card}><Text style={screen.h2}>需要处理</Text><Text style={screen.sub}>{err}</Text></View>:null}
  </ScrollView></View>
}
const s=StyleSheet.create({confirm:{flexDirection:'row',alignItems:'flex-start',gap:10,marginBottom:12},box:{width:22,height:22,borderWidth:1,borderColor:GO.line,borderRadius:6,alignItems:'center',justifyContent:'center'},boxOn:{backgroundColor:GO.blue,borderColor:GO.blue},tick:{color:'white',fontWeight:'800'},confirmText:{flex:1,color:GO.ink,lineHeight:20},provider:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:10,borderTopWidth:1,borderColor:GO.line},connection:{flexDirection:'row',alignItems:'center',gap:14,paddingVertical:10,borderTopWidth:1,borderColor:GO.line},link:{color:GO.blue,fontWeight:'700'},danger:{color:GO.orange,fontWeight:'700'},chips:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:12},chip:{paddingHorizontal:11,paddingVertical:8,borderRadius:18,borderWidth:1,borderColor:GO.line},active:{backgroundColor:GO.navy,borderColor:GO.navy},chipText:{fontSize:12,fontWeight:'800',color:GO.ink},activeText:{color:'white'},input:{minHeight:150,borderWidth:1,borderColor:GO.line,borderRadius:16,padding:14,marginTop:16,textAlignVertical:'top',color:GO.ink,backgroundColor:'white'},item:{paddingVertical:12,borderTopWidth:1,borderColor:GO.line},itemTitle:{fontWeight:'800',color:GO.ink},actions:{flexDirection:'row',justifyContent:'flex-end',gap:8,marginTop:8},reviewed:{color:GO.green,fontSize:12,fontWeight:'700',marginTop:6}})
