import React,{useState}from'react';
import{Alert,Linking,ScrollView,Text,TextInput,View,StyleSheet,Pressable}from'react-native';
import{GO,screen}from'../design';import{TopBar,Btn,StatusPill}from'../components/GO';import{api}from'../api/client';

const sources=[['SHARE_TO_GO','Share to GO'],['SCREENSHOT_AI','截图 / 图片'],['PDF_AI','PDF'],['FILE_IMPORT','文件'],['TEXT_IMPORT','粘贴文本']];
const providers=[['CTRIP','关联携程'],['MEITUAN','关联美团'],['FLIGGY','关联飞猪'],['BOOKING','关联 Booking'],['OTHER_OTA','关联其他平台']];
function parseText(raw:string){const lines=raw.split(/\n+/).map(x=>x.trim()).filter(Boolean);const map:any={姓名:'LEGAL_NAME',名字:'LEGAL_NAME',护照:'PASSPORT_NUMBER',手机号:'MOBILE',手机:'MOBILE',邮箱:'EMAIL',国籍:'NATIONALITY',生日:'DATE_OF_BIRTH'};const fields:any[]=[];let name='';for(const line of lines){const m=line.match(/^([^:：]{1,12})[:：]\s*(.+)$/);if(!m)continue;const ft=map[m[1].trim()];if(!ft)continue;if(ft==='LEGAL_NAME'){name=m[2].trim();continue}fields.push({entity_type:'PROFILE_FACT',traveler_ref:'me',field_type:ft,value:m[2].trim(),sensitive:['PASSPORT_NUMBER','DATE_OF_BIRTH'].includes(ft),confidence_bps:8500})}return[{entity_type:'TRAVELER',traveler_ref:'me',value:{full_name:name||'待确认旅客',relationship_type:'SELF',is_primary:true},confidence_bps:name?9000:5000},...fields]}

export default function TravelProfileImport({navigation}:any){
 const[src,setSrc]=useState('TEXT_IMPORT'),[raw,setRaw]=useState(''),[job,setJob]=useState<any>(null),[busy,setBusy]=useState(false),[err,setErr]=useState('');
 async function connect(provider:string){setBusy(true);setErr('');try{const r=await api('/v1/consumer/profile/provider-connections',{method:'POST',body:JSON.stringify({provider,method:'OFFICIAL_AUTHORIZATION',account_holder_confirmed:true})});const c=r.data;if(c.authorization_url){await Linking.openURL(c.authorization_url)}else{Alert.alert('请从原平台导出资料','该平台尚未开放账号授权接口。请由你本人登录原平台导出资料，再回到这里上传。')}}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 async function extract(){setBusy(true);setErr('');try{const items=parseText(raw);if(items.length<=1)throw new Error('请按“姓名：... / 护照：... / 手机号：...”格式粘贴资料');const r=await api('/v1/consumer/profile/imports',{method:'POST',body:JSON.stringify({source_type:src,source_provider:'USER_PROVIDED',source_reference:'mobile_import',items})});setJob(r.data)}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 async function reviewAll(){if(!job)return;setBusy(true);try{let j=job;for(const i of j.items||[]){if(['NEEDS_REVIEW','EXTRACTED'].includes(i.status)){const r=await api(`/v1/consumer/profile/imports/${j.import_job_id}/items/${i.import_item_id}/review`,{method:'POST',body:JSON.stringify({action:'ACCEPT'})});j=r.data}}const c=await api(`/v1/consumer/profile/imports/${j.import_job_id}/commit`,{method:'POST'});setJob(c.data);if(c.data.status==='COMMITTED')Alert.alert('已加入 GO','你的旅行资料已进入 Personal Travel Vault。',[{text:'查看资料库',onPress:()=>navigation.replace('TravelProfileVault')}])}catch(e:any){setErr(e.message)}finally{setBusy(false)}}
 return <View style={screen.root}><TopBar title="一键建立我的旅行资料" onBack={()=>navigation.goBack()}/><ScrollView contentContainerStyle={screen.content}>
  <Text style={screen.h1}>把已有旅行资料带到 GO</Text><Text style={screen.sub}>以你本人的账号身份授权。账号、密码和验证码只在原平台官方页面填写，GO 不接收这些凭据。</Text>
  <View style={screen.card}><Text style={screen.h2}>关联我的账号</Text><Text style={screen.sub}>登录后先预览可导入内容，由你确认后建立个人信息库。</Text><View style={s.chips}>{providers.map(([k,n])=><Pressable key={k} style={s.provider} disabled={busy} onPress={()=>connect(k)}><Text style={s.providerText}>{n}</Text></Pressable>)}</View></View>
  <View style={screen.card}><Text style={screen.h2}>从导出资料建立</Text><View style={s.chips}>{sources.map(([k,n])=><Pressable key={k} style={[s.chip,src===k&&s.active]} onPress={()=>setSrc(k)}><Text style={[s.chipText,src===k&&s.activeText]}>{n}</Text></Pressable>)}</View><TextInput multiline value={raw} onChangeText={setRaw} placeholder={'可粘贴例如：\n姓名：陈某\n护照：E12345678\n手机号：13800000000'} style={s.input}/><Btn title={busy?'处理中...':'识别候选资料'} onPress={extract}/></View>
  {job?<View style={screen.card}><View style={screen.row}><Text style={screen.h2}>识别结果</Text><StatusPill text={job.status} tone={job.conflict_count?'amber':'green'}/></View><Text style={screen.sub}>{job.item_count} 项 · {job.conflict_count||0} 个冲突</Text>{(job.items||[]).map((i:any)=><View key={i.import_item_id} style={s.item}><Text style={s.itemTitle}>{i.entity_type==='TRAVELER'?'Traveler':i.field_type}</Text><Text style={screen.sub}>{i.preview_masked||'旅客实体'} · confidence {i.confidence_bps/100}% · {i.status}</Text></View>)}<Btn title="确认并加入 GO" onPress={reviewAll}/></View>:null}
  {err?<View style={screen.card}><Text style={screen.h2}>需要处理</Text><Text style={screen.sub}>{err}</Text></View>:null}
 </ScrollView></View>}
const s=StyleSheet.create({chips:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:12},provider:{paddingHorizontal:14,paddingVertical:11,borderRadius:12,backgroundColor:GO.navy},providerText:{fontSize:13,fontWeight:'800',color:'white'},chip:{paddingHorizontal:11,paddingVertical:8,borderRadius:18,borderWidth:1,borderColor:GO.line},active:{backgroundColor:GO.navy,borderColor:GO.navy},chipText:{fontSize:12,fontWeight:'800',color:GO.ink},activeText:{color:'white'},input:{minHeight:150,borderWidth:1,borderColor:GO.line,borderRadius:16,padding:14,marginTop:16,textAlignVertical:'top',color:GO.ink,backgroundColor:'white'},item:{paddingVertical:10,borderTopWidth:1,borderColor:GO.line},itemTitle:{fontWeight:'800',color:GO.ink}})
