import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import { webcrypto } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),script=fs.readFileSync(path.join(here,'../frontend/admin/hotel-page-factory.js'),'utf8');
const hid='hotel_ac72aa53c89d4c3984b72436cb85f617',secondary='hotel_d17851be16724affb355375cacc5e58c';
const fields={phone:'0451-88800808',address:'黑龙江哈尔滨松北区创新三路800号',publicSource:'https://hotels.ctrip.com/hotels/2670932.html',eventsEmail:'anson.liu@hyatt.com',eventsSource:'https://www.hyatt.com/unbound-collection/en-US/hrbub-aoluguya/weddings'};
function environment(){const c=vm.createContext({window:{},crypto:webcrypto,TextEncoder,Uint8Array,URL});vm.runInContext(script,c);return c.window.GO_HOTEL_PAGE_FACTORY.reviewedContacts}
function fixture({readonly=false,officialAddress=false,highPhone=false,suppressed=false,badPurpose=false,drift=false,wrongReadback=false}={}){
 let version=1,detailReads=0,posts=0;const calls=[],snapshots=new Map(),contacts=[];
 const canonical=officialAddress?{address:'官方地址：创新三路800号'}:{},provenance=officialAddress?{address:{source_type:'OFFICIAL_WEBSITE',confidence_bps:9500}}:{};
 if(highPhone||suppressed)contacts.push({channel:'PHONE',normalized_value:'+8645188800808',value:'+8645188800808',contact_type:badPurpose?'SALES':'GENERAL',source_type:'OFFICIAL_WEBSITE',source_url:'https://www.hyatt.com/official',is_public_business_contact:true,do_not_contact:suppressed});
 const api={async request(route,options){calls.push({route,options});
  if(route==='/bff/auth/me')return {data:{actor_type:'GO_ADMIN',permissions:readonly?['admin:read']:['admin:rules']}};
  if(route.endsWith('/catalog-scope/preview'))return {data:{protected_ids:[hid,secondary],archived_ids:Array.from({length:112},(_,i)=>'old_'+i),scope_sha256:'a'.repeat(64),running_queue_count:0,physical_deletion:false,immutable_audit_retained:true}};
  if(route.includes('/factory/overview'))return {data:{total_hotels:2,items:[{hotel_id:hid},{hotel_id:secondary}]}};
  if(route.endsWith('/factory/hotels/'+secondary))return {data:{sources:[]}};
  if(route.endsWith('/factory/hotels/'+hid)){detailReads++;return {data:{profile:{hotel_id:hid,page_state:'DRAFT',version:drift&&detailReads>1?version+1:version,canonical_json:{...canonical},field_provenance_json:{...provenance}},sources:[],contacts:contacts.map(c=>({...c,contact_type:wrongReadback&&posts>0&&c.channel==='EMAIL'?'RESERVATIONS':c.contact_type}))}}}
  if(route.endsWith('/sources/ingest')){
   posts++;const body=options.body,key=JSON.stringify(body);let snap=snapshots.get(key);
   if(!snap){version++;snap={source_key:body.source_key,source_type:body.source_type,source_url:body.source_url,payload_json:body.payload};snapshots.set(key,snap);
    if(body.payload.address&&!officialAddress){canonical.address=body.payload.address;provenance.address={source_type:body.source_type,confidence_bps:body.confidence_bps}}
    for(const item of body.payload.contacts||[]){let found=contacts.find(c=>c.channel===item.channel&&c.normalized_value===item.value);if(!found){found={};contacts.push(found)}Object.assign(found,item,{normalized_value:item.value,source_type:body.source_type,source_url:body.source_url,do_not_contact:false})}
   }
   return {data:{profile:{hotel_id:hid},snapshot:snap,idempotent:posts>2}};
  }
  throw new Error('unexpected route '+route);
 }};return {api,calls,contacts,snapshots};
}
test('restricted form accepts updated valid public facts without whole-file hash',()=>{const h=environment(),f=h.contactFields({...fields,phone:'+86 451 8880 0809',eventsEmail:'events.team@hyatt.com'},hid);assert.equal(f.phone,'+8645188800809');assert.equal(f.eventsEmail,'events.team@hyatt.com');assert.ok(Object.isFrozen(f));assert.equal(h.contactFields(fields,hid).phone,'+8645188800808')});
test('wrong hotel, types, URL and phone/email are rejected',()=>{const h=environment();for(const f of [{...fields,admin:true},{...fields,publicSource:'https://hotels.ctrip.com/hotels/1.html'},{...fields,eventsSource:'http://www.hyatt.com/weddings'},{...fields,eventsSource:'https://name:secret@www.hyatt.com/unbound-collection/en-US/hrbub-aoluguya/weddings'},{...fields,phone:'javascript:x'},{...fields,eventsEmail:'reservations@example.com'}])assert.throws(()=>h.contactFields(f,hid));assert.throws(()=>h.contactFields(fields,secondary))});
test('readonly principal sends no writes',async()=>{const h=environment(),f=fixture({readonly:true});await assert.rejects(()=>h.previewContacts(f.api,fields,hid),/权限/);assert.equal(f.calls.some(c=>c.options),false)});
test('normal form writes two truthful sources and events-only email',async()=>{const h=environment(),f=fixture(),p=await h.previewContacts(f.api,fields,hid);assert.equal(f.calls.some(c=>c.options),false);const result=await h.executeContacts(f.api,p);assert.equal(result.draft,true);const posts=f.calls.filter(c=>c.options);assert.equal(posts.length,2);assert.ok(posts.every(c=>c.route.endsWith('/sources/ingest')));assert.equal(posts[0].options.body.source_type,'PUBLIC_SOURCE');assert.equal(posts[1].options.body.source_type,'OFFICIAL_WEBSITE');assert.equal(posts[1].options.body.payload.contacts[0].contact_type,'WEDDINGS_EVENTS_CONTACT');assert.ok(posts.every(c=>c.options.body.rights_status==='PUBLIC_BUSINESS_FACT'));assert.equal(f.contacts.length,2)});
test('higher official address is retained and supplementary source snapshot recorded',async()=>{const h=environment(),f=fixture({officialAddress:true}),p=await h.previewContacts(f.api,fields,hid);assert.equal(p.preserveAddress,true);assert.equal(p.expectedAddress,'官方地址：创新三路800号');const result=await h.executeContacts(f.api,p);assert.equal(result.preserveAddress,true);assert.equal(f.calls.find(c=>c.options).options.body.payload.address,fields.address)});
test('higher-ranked same phone is reused without source downgrade',async()=>{const h=environment(),f=fixture({highPhone:true}),p=await h.previewContacts(f.api,fields,hid);assert.equal(p.reusePhone,true);await h.executeContacts(f.api,p);assert.equal(f.calls.find(c=>c.options).options.body.payload.contacts,undefined);assert.equal(f.contacts.find(c=>c.channel==='PHONE').source_type,'OFFICIAL_WEBSITE')});
test('suppression or incompatible stronger purpose prevents write',async()=>{for(const options of [{suppressed:true},{highPhone:true,badPurpose:true}]){const h=environment(),f=fixture(options);await assert.rejects(()=>h.previewContacts(f.api,fields,hid));assert.equal(f.calls.some(c=>c.options),false)}});
test('changed profile after preview requires re-review before writes',async()=>{const h=environment(),f=fixture({drift:true}),p=await h.previewContacts(f.api,fields,hid);await assert.rejects(()=>h.executeContacts(f.api,p),/已变化/);assert.equal(f.calls.some(c=>c.options),false)});
test('repeat unchanged form keeps stable source identity and no duplicate contacts',async()=>{const h=environment(),f=fixture();await h.executeContacts(f.api,await h.previewContacts(f.api,fields,hid));await h.executeContacts(f.api,await h.previewContacts(f.api,fields,hid));assert.equal(f.snapshots.size,2);assert.equal(f.contacts.length,2)});
test('general-reservations misclassification fails final verification',async()=>{const h=environment(),f=fixture({wrongReadback:true}),p=await h.previewContacts(f.api,fields,hid);await assert.rejects(()=>h.executeContacts(f.api,p),/用途回读/) });

test('same-grade higher confidence phone is not downgraded',async()=>{const h=environment(),f=fixture({highPhone:true});f.contacts[0].source_type='PUBLIC_SOURCE';f.contacts[0].confidence_bps=10000;const p=await h.previewContacts(f.api,fields,hid);assert.equal(p.reusePhone,true);await h.executeContacts(f.api,p);assert.equal(f.calls.find(c=>c.options).options.body.payload.contacts,undefined)});
test('user supplied Ctrip mailbox has separate attributed snapshot and GENERAL purpose',async()=>{const h=environment();assert.match(script,/id="contactPublicEmail" type="email" value="1720574900@qq.com"/);assert.match(script,/用户提供并指明携程来源；尚未独立核验页面/);const f=fixture(),values={...fields,publicEmail:'1720574900@qq.com'},p=await h.previewContacts(f.api,values,hid);await h.executeContacts(f.api,p);const bodies=f.calls.filter(c=>c.options).map(c=>c.options.body);assert.equal(bodies.length,3);const attributed=bodies.find(b=>b.source_key.startsWith('USER_PROVIDED_CTRIP_ATTRIBUTION:'));assert.equal(attributed.source_type,'PUBLIC_SOURCE');assert.deepEqual(Object.keys(attributed.payload),['contacts']);assert.equal(attributed.payload.contacts[0].contact_type,'GENERAL');assert.equal(attributed.payload.contacts[0].value,values.publicEmail);assert.equal(bodies[0].payload.contacts.some(c=>c.channel==='EMAIL'),false);assert.equal(f.contacts.length,3);await h.executeContacts(f.api,await h.previewContacts(f.api,values,hid));assert.equal(f.snapshots.size,3);assert.equal(f.contacts.length,3)});
test('updated attributed email remains configurable without new release',async()=>{const h=environment(),f=fixture(),p=await h.previewContacts(f.api,{...fields,publicEmail:'public-contact@example.test'},hid);await h.executeContacts(f.api,p);assert.equal(f.contacts.find(c=>c.value==='public-contact@example.test').contact_type,'GENERAL')});
test('tampered attribution snapshot stops before remaining source writes',async()=>{const h=environment(),f=fixture(),request=f.api.request;f.api.request=async(route,options)=>{const result=await request(route,options);if(options?.body?.source_key.startsWith('USER_PROVIDED_CTRIP_ATTRIBUTION:'))result.data.snapshot.source_key='pretended-independent-verification';return result};const p=await h.previewContacts(f.api,{...fields,publicEmail:'1720574900@qq.com'},hid);await assert.rejects(()=>h.executeContacts(f.api,p),/快照回读不一致/);assert.equal(f.calls.filter(c=>c.options).length,2)});
test('public email cannot masquerade as the weddings email or inject markup',()=>{const h=environment();assert.throws(()=>h.contactFields({...fields,publicEmail:fields.eventsEmail},hid),/用途不能混填/);assert.throws(()=>h.contactFields({...fields,publicEmail:'<bad>@example.com'},hid))});

test('email local parts reject terminal dot and more than 64 characters',()=>{const h=environment();for(const key of ['eventsEmail','publicEmail'])for(const value of ['a.@'+(key==='eventsEmail'?'hyatt.com':'qq.com'),'a'.repeat(65)+'@'+(key==='eventsEmail'?'hyatt.com':'qq.com')])assert.throws(()=>h.contactFields({...fields,[key]:value},hid))});
