(() => {
  'use strict';
  const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const money=(v,c='CNY')=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:c,maximumFractionDigits:2}).format(v/100);
  const slug='aoluguya-harbin',selected=new Set();let catalog=null,availability=null,criteria=null,querySequence=0;
  const reservations=new Map();let credits=[],selectedCredit='';
  const localDate=n=>{const d=new Date();d.setDate(d.getDate()+n);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  $('checkIn').min=localDate(0);$('checkIn').value=localDate(1);$('checkOut').value=localDate(3);$('checkOut').min=localDate(1);
  $('checkIn').onchange=()=>{const d=new Date($('checkIn').value+'T12:00:00');d.setDate(d.getDate()+1);const min=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;$('checkOut').min=min;if($('checkOut').value<min)$('checkOut').value=min};
  window.GODateRange.bind({startId:'checkIn',endId:'checkOut',labels:{title:'选择入住和退房日期',start:'入住',end:'退房'}});
  async function api(path,body,method=body?'POST':'GET',key){const headers={'Content-Type':'application/json','X-GO-Session':'consumer'};const token=document.cookie.split('; ').find(x=>x.startsWith('go_consumer_csrf='))?.split('=').slice(1).join('=');if(method!=='GET'&&token)headers['X-CSRF-Token']=decodeURIComponent(token);if(key)headers['Idempotency-Key']=key;const response=await fetch(path,{method,credentials:'same-origin',headers,...(body?{body:JSON.stringify(body)}:{})});const result=await response.json();if(!response.ok){const e=Error(({CURRENT_TRAVELER_HOTEL_CONSENT_REQUIRED:'本次入住人授权已失效，请重新确认资料与用途',STAY_CREDIT_NOT_AVAILABLE:'这份额度已使用或正在退款，请刷新后查看',STAY_CREDIT_EXPIRED:'住宿额度已到期，请查看原订单',CREDIT_CHECK_IN_MUST_BE_WITHIN_VALIDITY:'所选入住日期超过住宿额度有效期，请调整日期',CREDIT_VALUE_CHANGED_REQUOTE_REQUIRED:'住宿额度已变化，请重新核对报价',CREDIT_VALUE_CHANGED_RECONFIRM_REQUIRED:'抵扣或补款金额已变化，请重新核对',STAY_CREDIT_ORIGINAL_PROPERTY_AND_CURRENCY_REQUIRED:'这份住宿额度只能用于原酒店及原币种报价',PAYMENT_RECONCILIATION_REQUIRED:'资金状态正在核对，请稍后再试',VAULT_TRAVELER_REFERENCE_REQUIRED:'请先选择本次实际入住人',PRICE_CHANGED_RECONFIRM_REQUIRED:'房价已变化，请重新查询并核对总价',FARE_RULE_CHANGED_RECONFIRM_REQUIRED:'预订规则已更新，请重新查询并核对',FARE_QUOTE_EXPIRED_REQUOTE_REQUIRED:'报价已过期，请重新核对费用后再确认',FARE_ORDER_CHANGED_REQUOTE_REQUIRED:'订单状态已变化，请刷新后重新核对费用',DATED_RATE_CHANGED_REQUOTE_REQUIRED:'所选日期房价已变化，请重新查询报价',FARE_AMOUNT_CHANGED_RECONFIRM_REQUIRED:'变更金额已变化，请重新核对',FARE_CHANGE_NOT_ALLOWED:'此订单当前不可改期',NEW_STAY_DATES_REQUIRED:'请选择新的入住日期',VALID_DATED_EXTENSION_REQUIRED:'续住需延后退房日期，入住日期保持原值',FARE_FEE_CHANGED_RECONFIRM_REQUIRED:'费用与报价不一致，请重新核对',CANCELLATION_WINDOW_CLOSED:'自助取消时间已结束，可提交售后申请进行核实',CONFIRMED_CANCELLATION_FARE_QUOTE_REQUIRED:'酒店已确认，请先核对取消费用',NO_DATED_INVENTORY:'房间刚刚售完，请选择其他方案',RESERVATION_NOT_PENDING:'酒店已处理该订单，请刷新状态后联系酒店',PAYMENT_RELEASE_OR_REFUND_REQUIRED:'该订单需要先处理支付授权或退款',RELEASED_AUTHORIZATION_REBOOK_REQUIRED:'原授权已结束，请重新提交入住申请',REFUND_COMPLETION_REQUIRED_FOR_CLOSURE:'退款尚未完成，请稍后查看',DISPUTE_IDEMPOTENCY_CONFLICT:'提交内容已变化，请刷新后重新申请',ACTIVE_OR_COMPLETED_STAY_REQUIRED:'入住开始后可在这里申请售后',AUTHENTICATION_REQUIRED:'请先登录 GO，再回到这里继续预订'}[result.detail])||'暂时无法完成，请刷新状态后重试。');e.status=response.status;throw e}return result.data}
  const area=r=>r.floor_size?.find(x=>x.unit==='SQUARE_METERS')?.range?.min;
  const views=r=>(r.views||[]).map(x=>x.viewType?.value).filter(Boolean).join(' · ');
  const rates=r=>(availability?.items||[]).filter(x=>x.room_code===r.room_code);
  function lowest(r){const values=rates(r).filter(x=>x.bookable&&x.total_amount_minor!=null).map(x=>x.total_amount_minor);return values.length?Math.min(...values):Infinity}
  function showMessage(text){$('message').textContent=text}
  function render(){if(!catalog)return;let rooms=catalog.rooms.filter(r=>$('roomFilter').value==='all'||($('roomFilter').value==='king'&&r.name.includes('特大床'))||($('roomFilter').value==='twin'&&r.name.includes('单人床'))||($('roomFilter').value==='large'&&area(r)>=72));if($('availableOnly').checked)rooms=rooms.filter(r=>rates(r).some(x=>x.bookable));rooms.sort((a,b)=>$('sort').value==='price'?lowest(a)-lowest(b)||area(a)-area(b):area(a)-area(b));$('resultCount').textContent=`显示 ${rooms.length} / ${catalog.rooms.length} 种官网房型${criteria?` · ${criteria.check_in} 至 ${criteria.check_out}`:''}`;
    $('rooms').innerHTML=rooms.map(room=>{const image=room.media?.find(x=>x.local_available&&x.local_url);return `<article class="room"><div class="room-image-wrap">${image?`<img class="room-photo" src="${esc(image.local_url)}" alt="${esc(image.alt||room.name)}" loading="lazy" width="800" height="600">`:`<div class="room-space"><strong>${esc(area(room))}</strong><span>平方米 · ${esc(views(room)||'景观以官网为准')}</span></div>`}</div><div><div class="room-top"><h3>${esc(room.name)}</h3><button class="text-button" data-compare="${esc(room.room_code)}">${selected.has(room.room_code)?'移出对照':'加入对照'}</button></div><p class="room-facts">${esc(area(room))} m² · ${esc(views(room))}</p><details><summary>客房设施与信息</summary><p>${(room.amenities||[]).filter(Boolean).map(esc).join(' · ')}</p><p>楼层：${room.floor??'官网未披露'} · 最大入住人数：${room.max_occupancy??'以所选报价限制为准'}</p></details>${rates(room).map(rate=>`<div class="rate"><div><h4>${esc(rate.rate_name)}</h4><p>${esc(rate.cancellation_policy)}</p>${window.GODirectFare.rulesSummary(rate.fare_rule,rate.currency)}<details><summary>查看逐晚价格</summary>${rate.nights.map(n=>`<div class="night"><span>${esc(n.stay_date)}</span><span>${money(n.price_minor,rate.currency)}</span></div>`).join('')}</details>${!rate.bookable?'<p>所选日期或人数暂不可预订</p>':''}</div><div class="rate-pay"><div class="rate-price"><strong>${rate.total_amount_minor!=null?money(rate.total_amount_minor,rate.currency):'待报价'}</strong><small>整段入住含税总价</small></div><button class="primary" data-book="${esc(rate.hosted_offer_id)}" ${!rate.bookable?'disabled':''}>选择</button>${selectedCredit?`<button class="text-button" data-redeem="${esc(rate.hosted_offer_id)}" ${!rate.bookable?'disabled':''}>使用住宿额度</button>`:''}</div></div>`).join('')||'<p class="unavailable">该日期尚无可预订报价，可以调整日期或联系酒店。</p>'}</div></article>`}).join('')||'<p class="unavailable">没有符合条件的房型，请调整筛选或日期。</p>';
    document.querySelectorAll('[data-compare]').forEach(b=>b.onclick=()=>{const code=b.dataset.compare;if(selected.has(code))selected.delete(code);else if(selected.size<3)selected.add(code);else{showMessage('最多同时对照 3 种房型');return}render();renderCompare()});document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>book(b.dataset.book));document.querySelectorAll('[data-redeem]').forEach(b=>b.onclick=()=>redeemCredit(b));
  }
  function renderCompare(){const rooms=catalog.rooms.filter(r=>selected.has(r.room_code));$('compare').hidden=!rooms.length;if(!rooms.length)return;$('compareContent').innerHTML=`<table><thead><tr><th scope="col">项目</th>${rooms.map(r=>`<th scope="col">${esc(r.name)}</th>`).join('')}</tr></thead><tbody>${[['面积',r=>`${area(r)} m²`],['景观',views],['整段入住最低总价',r=>Number.isFinite(lowest(r))?money(lowest(r)):'暂无可订报价'],['设施',r=>(r.amenities||[]).filter(Boolean).join('、')]].map(([label,fn])=>`<tr><th scope="row">${label}</th>${rooms.map(r=>`<td>${esc(fn(r))}</td>`).join('')}</tr>`).join('')}</tbody></table>`}
  async function search(){const seq=++querySequence;const current={check_in:$('checkIn').value,check_out:$('checkOut').value,adults:Number($('adults').value),children:Number($('children').value)};if(!current.check_in||current.check_out<=current.check_in){showMessage('请填写有效入住和退房日期');return}const button=$('staySearch').querySelector('button');button.disabled=true;button.textContent='正在查询…';showMessage('');try{const data=await api(`/v1/direct/${slug}/availability`,current);if(seq!==querySequence)return;availability=data;criteria=current;$('simulation').hidden=data.data_mode!=='SIMULATION';render();renderCompare()}catch(e){if(seq!==querySequence)return;availability=null;criteria=null;showMessage(e.message);render()}finally{if(seq===querySequence){button.disabled=false;button.textContent='查询房价'}}}
  $('staySearch').onsubmit=e=>{e.preventDefault();search()};for(const id of ['roomFilter','sort','availableOnly'])$(id).onchange=render;
  async function book(id){try{const rate=availability.items.find(x=>x.hosted_offer_id===id);if(!rate?.bookable)return;const bookingCriteria={...criteria};const v=await api('/v1/consumer/profile/vault');if(!v.travelers.length){showMessage('请先在 GO「我的」添加旅行资料，再继续预订');return}const d=document.createElement('dialog');d.className='go-dialog';d.setAttribute('aria-labelledby','bookingTitle');d.innerHTML=`<form><h2 id="bookingTitle">核对入住申请</h2><p>${esc(rate.room_name)}<br>${esc(bookingCriteria.check_in)} → ${esc(bookingCriteria.check_out)}<br>${bookingCriteria.adults} 位成人 · ${bookingCriteria.children} 位儿童</p><h2>${money(rate.total_amount_minor,rate.currency)}</h2><p>${esc(rate.cancellation_policy)}</p>${window.GODirectFare.rulesSummary(rate.fare_rule,rate.currency)}<p>酒店确认前，本次仅提交预订申请，不会扣款。</p><div class="field"><label for="hotelTraveler">入住人</label><select id="hotelTraveler" required><option value="">请选择实际入住人</option>${v.travelers.map(t=>`<option value="${esc(t.traveler_id)}">${esc(t.full_name)}</option>`).join('')}</select></div><label class="go-consent"><input type="checkbox" required data-consent><span>我已核对资料，同意为本次酒店预订使用所选入住人的姓名和联系电话。</span></label><p role="alert"></p><footer><button type="button" class="btn" data-close>返回选择</button><button type="submit" class="btn primary">提交入住申请</button></footer></form>`;let busy=false;const close=()=>{if(!busy){d.close();d.remove()}};d.querySelector('[data-close]').onclick=close;d.oncancel=e=>{e.preventDefault();if(!busy)close()};d.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;const tid=d.querySelector('select').value;if(!tid||!d.querySelector('[data-consent]').checked)return;busy=true;const button=d.querySelector('[type=submit]');button.disabled=true;try{await api('/v1/consumer/profile/consents',{traveler_id:tid,consent_type:'SENSITIVE_DATA_RELEASE',purpose:'HOTEL_BOOKING',scope:['LEGAL_NAME','MOBILE'],expires_at:new Date(Date.now()+15*60000).toISOString()});const body={...bookingCriteria,hosted_offer_id:id,traveler_id:tid,expected_total_minor:rate.total_amount_minor,...(rate.fare_rule?{expected_fare_rule_hash:rate.fare_rule.rule_hash}:{})};const fingerprint=JSON.stringify(body);if(!reservations.has(fingerprint))reservations.set(fingerprint,crypto.randomUUID());const reservation=await api(`/v1/direct/${slug}/reservations`,body,'POST',reservations.get(fingerprint));busy=false;close();await showReservation(reservation.hosted_reservation_id);await search()}catch(error){d.querySelector('[role=alert]').textContent=error.message;button.disabled=false}finally{busy=false}};document.body.append(d);d.showModal()}catch(e){showMessage(e.status===401?'请先在 GO 首页登录，再回到这里继续预订。':e.message)}}
  async function authorizeReservation(r){
    const d=document.createElement('dialog');d.className='go-dialog';
    d.innerHTML=`<form><h2>核对入住资金授权</h2><p>${esc(r.check_in)} → ${esc(r.check_out)}</p><h2>${money(r.amount_minor,r.currency)}</h2><p>先冻结授权，酒店确认前取消会自动释放。房费在履约确认后扣取；酒店确认后的取消或未到店费用，按下单时锁定的规则处理。</p><div class="go-sim-note">当前为隔离测试，不会冻结或扣取真实资金。</div><label class="go-consent"><input type="checkbox" required data-consent><span>我已核对入住日期与金额，同意本次测试授权。</span></label><p role="alert"></p><footer><button type="button" data-close>暂不授权</button><button type="submit" class="primary">确认测试授权</button></footer></form>`;
    let busy=false;const close=()=>{if(!busy){d.close();d.remove()}};
    d.querySelector('[data-close]').onclick=close;d.oncancel=e=>{e.preventDefault();close()};
    d.querySelector('form').onsubmit=async e=>{
      e.preventDefault();if(busy||!d.querySelector('[data-consent]').checked)return;busy=true;
      const button=d.querySelector('[type=submit]');button.disabled=true;d.querySelector('[data-close]').disabled=true;
      try{await api(`/v1/direct/reservations/${r.hosted_reservation_id}/checkout`,{mode:'CONTRACT_SIMULATOR',expected_amount_minor:r.amount_minor,currency:r.currency});busy=false;close();await showReservation(r.hosted_reservation_id)}
      catch(error){d.querySelector('[role=alert]').textContent=error.message;busy=false;button.disabled=false;d.querySelector('[data-close]').disabled=false}
    };document.body.append(d);d.showModal();
  }
  async function showReservation(id){
    const [data,caps]=await Promise.all([api(`/v1/direct/reservations/${id}`),api('/v1/consumer/checkout-capabilities')]);
    const r=data.reservation||data,state=r.reservation_state||data.reservation_state;
    const labels={CONVERTED_TO_CREDIT:'已转换为原酒店住宿额度',PENDING_HOTEL_CONFIRMATION:'已收到申请 · 等待酒店确认',HOTEL_CONFIRMED_AWAITING_ALIPAY_ONBOARDING:'酒店已确认',CANCELLED:'申请已取消',NO_SHOW:'已记录未到店',HOTEL_REJECTED:'酒店未能确认',HOTEL_CONFIRMATION_TIMEOUT:'确认超时 · 库存已释放'};
    const paymentLabels={CONTRACT_CREDIT_AND_AUTHORIZED:'住宿额度已抵扣，现金差额按报价授权',CONTRACT_CREDIT_PAID:'住宿额度及现金结算已记录',ALIPAY_APPLICATION_PENDING_NO_CHARGE:'尚未授权或扣款',NO_PAYMENT_NO_REFUND_REQUIRED:'无需付款，已有授权已释放',CONTRACT_AUTHORIZED_NOT_ALIPAY:'测试授权已冻结，尚未扣款',CONTRACT_CAPTURED_NOT_ALIPAY:'测试扣款已记录，未发生真实收款'};
    const canAuthorize=!(data.authorizations||[]).some(a=>a.state==='CONTRACT_RELEASED_NOT_ALIPAY')&&caps.simulation_available&&['PENDING_HOTEL_CONFIRMATION','HOTEL_CONFIRMED_AWAITING_ALIPAY_ONBOARDING'].includes(state)&&['ALIPAY_APPLICATION_PENDING_NO_CHARGE','NO_PAYMENT_NO_REFUND_REQUIRED'].includes(r.payment_state);
    $('reservation').hidden=false;$('reservation').innerHTML=`<p class="eyebrow">YOUR RESERVATION</p><h2>${esc(labels[state]||state)}</h2><p>${esc(r.check_in)} → ${esc(r.check_out)} · ${money(r.amount_minor,r.currency)}</p><p role="status">${esc(paymentLabels[r.payment_state]||'资金状态待核对')}</p><button class="text-button" id="refreshReservation">刷新状态</button>${canAuthorize?'<button class="primary" id="authorizeReservation">核对资金授权</button>':''}${state==='PENDING_HOTEL_CONFIRMATION'?'<button class="text-button" id="cancelReservation">取消申请并释放授权</button>':''}${window.GODirectAfterSales.render(data.after_sales,r.currency)}${window.GODirectFare.options(data.after_sales?.fare,r.currency)}`;
    $('refreshReservation').onclick=()=>showReservation(id).catch(e=>showMessage(e.message));
    if($('authorizeReservation'))$('authorizeReservation').onclick=()=>authorizeReservation(r);
    if($('cancelReservation'))$('cancelReservation').onclick=async()=>{const button=$('cancelReservation');button.disabled=true;try{await api(`/v1/direct/reservations/${id}/cancel`,{});await showReservation(id);await search()}catch(e){showMessage(e.message);button.disabled=false}};
    if($('quoteFareCancellation'))$('quoteFareCancellation').onclick=async()=>{const button=$('quoteFareCancellation');button.disabled=true;try{await window.GODirectFare.cancel(r,api,async()=>{await showReservation(id);await search()})}catch(error){showMessage(error.message)}finally{button.disabled=false}};
    if($('quoteFareChange'))$('quoteFareChange').onclick=async()=>{try{await window.GODirectFare.change(r,$('quoteFareChange').dataset.action,api,async()=>{await showReservation(id);await search()})}catch(error){showMessage(error.message)}};
    if($('convertStayCredit'))$('convertStayCredit').onclick=async()=>{try{await window.GODirectCredit.convert(r,api,async()=>{await showReservation(id);await loadCredits();await search()})}catch(error){showMessage(error.message)}};
    if($('retrySupplierRemedy'))$('retrySupplierRemedy').onclick=async()=>{const button=$('retrySupplierRemedy');button.disabled=true;try{await api(`/v1/direct/reservations/${encodeURIComponent(id)}/disruption/retry`,{});await showReservation(id)}catch(error){showMessage(error.message);button.disabled=false}};
    if($('openStayCase'))$('openStayCase').onclick=()=>openStayCase(id);
    document.querySelectorAll('[data-refund-retry]').forEach(button=>button.onclick=async()=>{
      button.disabled=true;
      try{await api(`/v1/direct/reservations/${encodeURIComponent(id)}/refunds/${encodeURIComponent(button.dataset.refundRetry)}/retry`,{});await showReservation(id)}
      catch(error){showMessage(error.message);button.disabled=false}
    });
    await loadCredits();
    $('reservation').scrollIntoView({block:'nearest',behavior:'auto'});
  }
  async function openStayCase(id){
    const d=document.createElement('dialog');d.className='go-dialog';d.setAttribute('aria-labelledby','stayCaseTitle');
    d.innerHTML=`<form><h2 id="stayCaseTitle">告诉我们入住遇到的问题</h2><label>问题类型<select name="kind"><option value="SERVICE">服务体验</option><option value="AMOUNT">费用或扣款</option><option value="FULFILLMENT">入住与履约</option><option value="CANCELLATION">取消与费用</option><option value="NO_SHOW">未到店认定</option></select></label><label>详细说明<textarea name="description" required maxlength="2000" rows="5" placeholder="请描述发生了什么，以及您希望如何处理。请勿填写证件号或银行卡号。"></textarea></label><p class="fine">提交后，GO 会核实情况并协调处理。是否退款及退款金额将单独确认。</p><p role="alert"></p><footer><button type="button" data-close>暂不提交</button><button class="primary" type="submit">提交售后申请</button></footer></form>`;
    let busy=false;const key=crypto.randomUUID(),close=()=>{if(!busy){d.close();d.remove()}};
    d.querySelector('[data-close]').onclick=close;d.oncancel=e=>{e.preventDefault();close()};
    d.querySelector('form').onsubmit=async e=>{e.preventDefault();if(busy)return;
      const description=d.querySelector('[name=description]').value.trim();if(!description)return;
      const body={dispute_type:d.querySelector('[name=kind]').value,description};busy=true;d.querySelector('[type=submit]').disabled=true;
      try{await api(`/v1/direct/reservations/${id}/cases`,body,'POST',key);busy=false;close();await showReservation(id)}
      catch(error){d.querySelector('[role=alert]').textContent=error.message;busy=false;d.querySelector('[type=submit]').disabled=false}
    };document.body.append(d);d.showModal();
  }
  async function restoreReservations(){
    try{const requested=new URLSearchParams(window.location.search).get('reservation');
      if(requested){if(!/^[a-zA-Z0-9_-]{1,100}$/.test(requested)){showMessage('订单链接无效');return}await showReservation(requested);return}
      const data=await api('/v1/consumer/direct-reservations');if(data.items.length)await showReservation(data.items[0].hosted_reservation_id)}
    catch(e){if(e.status!==401)showMessage(e.message)}
  }
  async function loadCredits(){
    try{credits=(await api('/v1/consumer/stay-credits')).items;
      if(!credits.some(c=>c.credit_id===selectedCredit&&c.can_redeem))selectedCredit='';
      const panel=$('stayCredits');panel.innerHTML=window.GODirectCredit.list(credits,slug,selectedCredit);panel.hidden=!panel.innerHTML;
      if($('stayCreditChoice'))$('stayCreditChoice').onchange=()=>{selectedCredit=$('stayCreditChoice').value;render()};render();
    }catch(error){if(error.status!==401)showMessage(error.message)}
  }
  async function redeemCredit(button){
    const c=credits.find(c=>c.credit_id===selectedCredit),rate=availability?.items.find(r=>r.hosted_offer_id===button.dataset.redeem);
    if(!c?.can_redeem||!rate?.bookable||!criteria)return;
    button.disabled=true;
    try{await window.GODirectCredit.redeem(c,rate,{...criteria},api,async result=>{selectedCredit='';await showReservation(result.reservation_id);await loadCredits();await search()})}
    catch(error){showMessage(error.message)}finally{button.disabled=false}
  }
  restoreReservations();loadCredits();
  api(`/v1/direct/${slug}/catalog`).then(data=>{catalog=data;render();search()}).catch(e=>{showMessage(e.message);$('rooms').textContent='酒店信息暂不可用，请稍后刷新。'});
})();
