const app=document.querySelector('#app');
const money=n=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:0}).format((n||0)/100);
const OTA_SNAPSHOT={observed_at:'2026-08-11',stay:'2026-08-11 至 2026-08-12',source:'公开渠道历史快照',hotel_start:104800,rooms:{'摄罗子·枕月双床房':104800,'摄罗子·卧云双床房':124800}};
async function api(p,o){const r=await fetch(p,{headers:{'Content-Type':'application/json','Idempotency-Key':crypto.randomUUID()},...o});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(b.detail||`HTTP_${r.status}`);return b.data}
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function groupOffers(offers){const m=new Map();for(const x of offers||[]){if(!m.has(x.room_name))m.set(x.room_name,[]);m.get(x.room_name).push(x)}return [...m.entries()]}
function otaFor(room){return OTA_SNAPSHOT.rooms[room]||OTA_SNAPSHOT.hotel_start}
function metaFor(room){if(room.includes('卧云'))return '72㎡级 · 大空间 · 以酒店最终确认为准';if(room.includes('枕月'))return '宽敞客房 · 以酒店最终确认为准';if(room.includes('圆梦'))return '舒适客房 · 以酒店最终确认为准';return '客房 · 以酒店最终确认为准'}
function renderPage(d){const c=d.hotel.contact_json||{},groups=groupOffers(d.offers);app.innerHTML=`
<header class="hd-top"><button class="hd-back" onclick="history.back()" aria-label="返回">‹</button><div class="hd-brand">G<i></i>O · 哈尔滨敖麓谷雅酒店</div><div></div></header>
<div class="hd-env"><b>Staging 测试页面</b> · 当前报价仅用于系统测试 · 暂未接入真实支付</div>
<section class="hd-hero"><div class="hd-kicker">AOLUGUYA · HARBIN</div><h1>哈尔滨敖麓谷雅酒店</h1><p>SPA BY L'OCCITANE · The Unbound Collection by Hyatt</p><div class="hd-badges"><span>松北区</span><span>SPA</span><span>室内泳池</span><span>行政酒廊</span></div></section>
<section class="hd-summary"><div class="hd-score-row"><div class="hd-score">9.4 <small>公开渠道历史评分 · 4,700+点评</small></div></div><div class="hd-address">${esc(c.address||'黑龙江省哈尔滨市松北区创新三路800号')} · 入住 ${esc(c.check_in||'14:00')} · 退房 ${esc(c.check_out||'12:00')}</div></section>
<section class="hd-search"><div class="hd-field"><label>入住</label><input id="cin" type="date"></div><div class="hd-field"><label>退房</label><input id="cout" type="date"></div><button id="refresh">查询 GO 当前测试报价</button></section>
<div class="hd-section-title"><h2>客房与价格</h2><p>GO 报价为 Staging 测试数据；公开渠道价格仅作历史参考。</p></div>
${groups.map(([room,offers])=>`<section class="hd-room"><div class="hd-room-media"><h3>${esc(room)}</h3><p>${metaFor(room)}</p></div><div class="hd-room-body"><div class="hd-rate"><div><div class="hd-rate-title">公开渠道历史参考<span class="hd-pill">非实时</span></div><div class="hd-rate-sub">${OTA_SNAPSHOT.stay} · ${OTA_SNAPSHOT.source}</div></div><div class="hd-price"><b>${money(otaFor(room))}</b><small>历史参考起价 / 晚</small></div></div>${offers.map(o=>`<div class="hd-rate"><div><div class="hd-rate-title">GO 当前测试报价</div><div class="hd-rate-sub ok">${esc(o.rate_name)} · ${esc(o.cancellation_policy)}</div><div class="hd-rate-sub">测试库存 ${esc(o.inventory)} · 预订申请模式 · 未接真实支付</div></div><div class="hd-price"><b>${money(o.price_minor)}</b><small>GO Staging 测试价</small><button data-offer="${esc(o.hosted_offer_id)}">提交预订申请</button></div></div>`).join('')}</div></section>`).join('')}
<section class="hd-facts"><h2>服务及设施</h2><div class="hd-fact-grid">${(c.facilities||['SPA','室内泳池','行政酒廊','健身中心','餐厅','免费停车','Wi-Fi','班车']).slice(0,8).map(x=>`<span>${esc(x)}</span>`).join('')}</div></section>
<section class="hd-policy"><b>酒店政策</b><br>前台 / 预订：${esc(c.reservation_phone||c.front_desk_phone||'0451-88800808')}<br>早餐：${esc(c.breakfast?.style||'自助餐')} ${esc(c.breakfast?.hours||'')}<br>宠物：${esc(c.pets||'以酒店最终确认为准')}</section>
<details class="hd-tech"><summary>测试环境与价格来源说明</summary><div>公开渠道历史参考价不是实时库存、实时价格或酒店官方报价。GO 当前报价来自 Staging 测试数据，真实供应链接入后由 Supply Truth 替换。支付状态：${esc(d.payment?.application_state||'NOT_CONNECTED')}；当前不得宣称已完成真实收款、退款或结算。</div></details>
<footer class="hd-bottom"><button class="back" onclick="history.back()">返回</button><button class="primary" id="roomsTop">查看客房报价</button></footer>`;
const today=new Date(),tom=new Date(today),day2=new Date(today);tom.setDate(today.getDate()+1);day2.setDate(today.getDate()+2);const iso=x=>{const y=x.getFullYear(),m=String(x.getMonth()+1).padStart(2,'0'),d=String(x.getDate()).padStart(2,'0');return `${y}-${m}-${d}`};document.querySelector('#cin').value=iso(tom);document.querySelector('#cout').value=iso(day2);document.querySelector('#refresh').onclick=load;document.querySelector('#roomsTop').onclick=()=>document.querySelector('.hd-section-title')?.scrollIntoView({behavior:'smooth'});document.querySelectorAll('[data-offer]').forEach(b=>b.onclick=()=>reserve(b.dataset.offer));}
async function load(){try{renderPage(await api('/v1/direct/aoluguya-harbin'))}catch(e){app.innerHTML=`<div class="hd-error"><b>酒店页面暂时无法加载</b><br>${esc(e.message)}</div>`}}
function closeReserveSheet(){document.querySelector('.hd-sheet-backdrop')?.remove()}
function reserve(id){const cin=document.querySelector('#cin')?.value,cout=document.querySelector('#cout')?.value;if(!cin||!cout){showHdNotice('请先选择入住和退房日期');return}closeReserveSheet();const w=document.createElement('div');w.className='hd-sheet-backdrop';w.innerHTML=`<section class="hd-sheet" role="dialog" aria-modal="true"><div class="hd-sheet-handle"></div><h2>提交预订申请</h2><p>入住 ${esc(cin)} → ${esc(cout)}。测试环境不会产生真实支付。</p><label>住客姓名<input id="hdGuest" autocomplete="name"></label><label>联系电话<input id="hdContact" type="tel" autocomplete="tel"></label><div class="hd-sheet-actions"><button id="hdCancel">取消</button><button id="hdSubmit">提交申请</button></div></section>`;document.body.appendChild(w);w.querySelector('#hdCancel').onclick=closeReserveSheet;w.onclick=e=>{if(e.target===w)closeReserveSheet()};w.querySelector('#hdGuest').focus();w.querySelector('#hdSubmit').onclick=async()=>{const guest=w.querySelector('#hdGuest').value.trim(),contact=w.querySelector('#hdContact').value.trim();if(!guest||!contact){showHdNotice('请填写住客姓名和联系电话');return}const b=w.querySelector('#hdSubmit');b.disabled=true;b.textContent='提交中…';try{const r=await api('/v1/direct/aoluguya-harbin/reservations',{method:'POST',body:JSON.stringify({hosted_offer_id:id,guest_name:guest,guest_contact:contact,check_in:cin,check_out:cout})});closeReserveSheet();showHdNotice(`预订申请已提交：${r.hosted_reservation_id}。等待酒店确认；未发生支付。`)}catch(e){showHdNotice(e.message);b.disabled=false;b.textContent='提交申请'}}}
function showHdNotice(message){document.querySelector('.hd-notice')?.remove();const n=document.createElement('div');n.className='hd-notice';n.setAttribute('role','status');n.textContent=message;document.body.appendChild(n);setTimeout(()=>n.remove(),3200)}
load();
