window.GO_CONSOLE={title:'GO 合作伙伴平台',subtitle:'酒店、机票、铁路、接送用车、租车与景点体验合作伙伴工作台',actorType:'SUPPLIER_USER',nav:[
{route:'/command',label:'经营中心',custom:'supplierCommandCenter'},
{route:'/catalog-fare',label:'酒店退改规则',custom:'supplierCatalogFare'},
{route:'/operations-hub',label:'订单与履约',custom:'supplierOperationsHub'},
{route:'/marketing-rights',label:'促销与权益',custom:'supplierMarketingRightsHub'},
{route:'/analytics-hub',label:'经营数据',custom:'supplierAnalyticsHub'},
{route:'/finance-hub',label:'财务',custom:'supplierFinanceHub'},
{route:'/business-management',label:'业务管理',custom:'supplierBusinessManagementHub'},
{route:'/supplier-exception-center',label:'异常中心',custom:'supplierExceptionCenter'}],hiddenNav:[
{route:'/hotel-webpage',label:'酒店网页',custom:'supplierHotelWebpage'},
{route:'/property',label:'酒店资料',custom:'supplierPropertyProfile'},
{route:'/rooms',label:'房型管理',custom:'supplierProductGraph'},
{route:'/rates',label:'房态房价',custom:'supplierInventoryRates'},
{route:'/benefits',label:'官方权益',custom:'supplierOfficialBenefits'},
{route:'/marketing',label:'自主促销',custom:'supplierPromotions'},
{route:'/go-identity',label:'员工优价 / 业主权益',custom:'supplierIdentityPrograms'},
{route:'/ai-marketing',label:'GO AI 营销建议',custom:'supplierAiMarketing'},
{route:'/growth-data',label:'经营数据明细',custom:'supplierGrowthData'},
{route:'/orders',label:'订单',custom:'supplierOrders'},
{route:'/go-offer',label:'GO Offer',custom:'supplierGoOffer'},
{route:'/fulfillment',label:'入住与履约',custom:'supplierFulfillmentTemplate'},
{route:'/refunds',label:'取消与退款',custom:'supplierRefundTemplate'},
{route:'/supplier-fault',label:'无法履约处理',custom:'supplierFaultCancellation'},
{route:'/t20',label:'T+20 与订阅',custom:'supplierT20'},
{route:'/finance',label:'交易与结算状态',custom:'supplierPaymentFinance'},
{route:'/reconciliation',label:'平台交易证据',custom:'supplierReconciliationTemplate'},
{route:'/reviews-truth',label:'点评 / GO Truth',custom:'supplierReviews'},
{route:'/go-rating',label:'GO星级 / 推荐',custom:'supplierRating'},
{route:'/content',label:'内容与媒体',custom:'supplierContentTemplate'},
{route:'/direct',label:'官方直连',custom:'supplierOfficialDirectTemplate'},
{route:'/direct-value',label:'官方直连价值',custom:'supplierDirectValue'},
{route:'/channel-economics',label:'直连经营分析',custom:'supplierChannelEconomics'},
{route:'/connectors',label:'供应链连接',custom:'supplierConnectors'},
{route:'/inbox',label:'通知中心',custom:'supplierOperatingSnapshot'},
{route:'/account',label:'账号与权限',custom:'supplierAccountTemplate'},
{route:'/help',label:'帮助与工单',custom:'supplierHelpTemplate'},
{route:'/vertical-capabilities',label:'全品类能力',custom:'supplierVerticals'},
{route:'/growth',label:'经营增长记录',custom:'supplierJudgments'}],principles:{recommendationValueSeparated:true,aiSupplierMutationRequiresApproval:true,goOfferDedicatedSupplyOnly:true,structuredOperationsRequired:true,noFakeGrowthMetrics:true,partnerHomeTaskOriented:true,partnerPrimaryNavMax:7,ownerStaffBenefitsInPromotion:true,goConsumerBenefitsNotSupplierBusinessModule:true}};
