"""Sprint 1D runtime persistence tables."""
from alembic import op
import sqlalchemy as sa
revision = "0001_sprint1d"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("offer_snapshot",
        sa.Column("offer_id", sa.String(64), primary_key=True), sa.Column("hotel_id", sa.String(64), nullable=False), sa.Column("room_type_id", sa.String(64), nullable=False), sa.Column("rate_plan_id", sa.String(64), nullable=False), sa.Column("total_amount_minor", sa.BigInteger(), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("check_in", sa.String(10), nullable=False), sa.Column("check_out", sa.String(10), nullable=False), sa.Column("official_direct", sa.Boolean(), nullable=False), sa.Column("fare_rule_id", sa.String(64), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("prebook", sa.Column("prebook_id", sa.String(64), primary_key=True), sa.Column("offer_id", sa.String(64), nullable=False), sa.Column("total_amount_minor", sa.BigInteger(), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("hotel_order_runtime", sa.Column("order_id", sa.String(64), primary_key=True), sa.Column("prebook_id", sa.String(64), nullable=False), sa.Column("hotel_id", sa.String(64), nullable=False), sa.Column("account_id", sa.String(64), nullable=False), sa.Column("total_amount_minor", sa.BigInteger(), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("supplier_confirmation_no", sa.String(128)), sa.Column("version", sa.Integer(), nullable=False, server_default="1"), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False), sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("payment_runtime", sa.Column("payment_id", sa.String(64), primary_key=True), sa.Column("order_id", sa.String(64), nullable=False), sa.Column("amount_minor", sa.BigInteger(), nullable=False), sa.Column("currency", sa.String(3), nullable=False), sa.Column("status", sa.String(32), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("order_event_runtime", sa.Column("event_id", sa.String(64), primary_key=True), sa.Column("event_type", sa.String(96), nullable=False), sa.Column("aggregate_type", sa.String(64), nullable=False), sa.Column("aggregate_id", sa.String(64), nullable=False), sa.Column("payload", sa.JSON(), nullable=False), sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("transactional_outbox", sa.Column("outbox_id", sa.Integer(), primary_key=True, autoincrement=True), sa.Column("event_id", sa.String(64), nullable=False, unique=True), sa.Column("topic", sa.String(128), nullable=False), sa.Column("event_type", sa.String(96), nullable=False), sa.Column("aggregate_id", sa.String(64), nullable=False), sa.Column("payload", sa.JSON(), nullable=False), sa.Column("status", sa.String(24), nullable=False), sa.Column("attempt_count", sa.Integer(), nullable=False), sa.Column("available_at", sa.DateTime(timezone=True), nullable=False), sa.Column("published_at", sa.DateTime(timezone=True)), sa.Column("last_error", sa.Text()), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_table("idempotency_record_runtime", sa.Column("idempotency_key", sa.String(128), primary_key=True), sa.Column("operation", sa.String(96), primary_key=True), sa.Column("request_hash", sa.String(64), nullable=False), sa.Column("response_code", sa.Integer(), nullable=False), sa.Column("response_body", sa.JSON(), nullable=False), sa.Column("resource_id", sa.String(64)), sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.create_index("ix_outbox_pending", "transactional_outbox", ["status","available_at","outbox_id"])

def downgrade():
    for t in ["idempotency_record_runtime","transactional_outbox","order_event_runtime","payment_runtime","hotel_order_runtime","prebook","offer_snapshot"]: op.drop_table(t)
