"""Sprint 3A flight complete golden path.

Revision ID: 0022_sprint3a
Revises: 0021_sprint2b
"""
from alembic import op
import sqlalchemy as sa
revision='0022_sprint3a'; down_revision='0021_sprint2b'; branch_labels=None; depends_on=None

def upgrade():
    op.create_table('flight_offer_runtime',sa.Column('offer_id',sa.String(64),primary_key=True),sa.Column('origin',sa.String(8),nullable=False),sa.Column('destination',sa.String(8),nullable=False),sa.Column('departure_date',sa.String(10),nullable=False),sa.Column('carrier_code',sa.String(8),nullable=False),sa.Column('flight_number',sa.String(16),nullable=False),sa.Column('cabin',sa.String(24),nullable=False),sa.Column('fare_family',sa.String(48),nullable=False),sa.Column('total_amount_minor',sa.BigInteger(),nullable=False),sa.Column('tax_amount_minor',sa.BigInteger(),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('baggage',sa.JSON(),nullable=False),sa.Column('change_policy',sa.JSON(),nullable=False),sa.Column('refund_policy',sa.JSON(),nullable=False),sa.Column('segments',sa.JSON(),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('flight_prebook_runtime',sa.Column('prebook_id',sa.String(64),primary_key=True),sa.Column('offer_id',sa.String(64),nullable=False),sa.Column('total_amount_minor',sa.BigInteger(),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('price_locked',sa.Boolean(),nullable=False),sa.Column('inventory_confirmed',sa.Boolean(),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('flight_order_runtime',sa.Column('order_id',sa.String(64),primary_key=True),sa.Column('account_id',sa.String(64),nullable=False),sa.Column('prebook_id',sa.String(64),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('total_amount_minor',sa.BigInteger(),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('passengers',sa.JSON(),nullable=False),sa.Column('payment_method_id',sa.String(64)),sa.Column('pnr',sa.String(16)),sa.Column('ticket_numbers',sa.JSON(),nullable=False),sa.Column('current_itinerary',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('flight_change_quote_runtime',sa.Column('quote_id',sa.String(64),primary_key=True),sa.Column('order_id',sa.String(64),nullable=False),sa.Column('new_departure_date',sa.String(10),nullable=False),sa.Column('new_flight_number',sa.String(16),nullable=False),sa.Column('fare_difference_minor',sa.BigInteger(),nullable=False),sa.Column('change_fee_minor',sa.BigInteger(),nullable=False),sa.Column('total_due_minor',sa.BigInteger(),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('status',sa.String(24),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    op.create_table('flight_refund_runtime',sa.Column('refund_id',sa.String(64),primary_key=True),sa.Column('order_id',sa.String(64),nullable=False),sa.Column('refund_fee_minor',sa.BigInteger(),nullable=False),sa.Column('refund_amount_minor',sa.BigInteger(),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('completed_at',sa.DateTime(timezone=True)))

def downgrade():
    for t in ['flight_refund_runtime','flight_change_quote_runtime','flight_order_runtime','flight_prebook_runtime','flight_offer_runtime']: op.drop_table(t)
