"""Sprint 4G exception debt burn-down, waiver freeze and executive risk acceptance.
Revision ID: 0054_sprint4g
Revises: 0053_sprint4f
"""
from alembic import op
import sqlalchemy as sa
revision='0054_sprint4g';down_revision='0053_sprint4f';branch_labels=None;depends_on=None

def _immutable(table):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_EXCEPTION_DEBT_GOVERNANCE_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_EXCEPTION_DEBT_GOVERNANCE_EVIDENCE'); END;")
    elif d=='postgresql':
        op.execute("""CREATE OR REPLACE FUNCTION deny_exception_debt_governance_evidence_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'IMMUTABLE_EXCEPTION_DEBT_GOVERNANCE_EVIDENCE'; END; $$ LANGUAGE plpgsql;""")
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_exception_debt_governance_evidence_mutation();")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_exception_debt_governance_evidence_mutation();")

def upgrade():
    op.create_table('journey_recovery_debt_burn_down_policy',
        sa.Column('debt_burn_down_policy_id',sa.String(64),primary_key=True),sa.Column('policy_key',sa.String(128),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('environment',sa.String(16),nullable=False),sa.Column('freeze_trigger_debt_points',sa.Float(),nullable=False),sa.Column('release_threshold_debt_points',sa.Float(),nullable=False),sa.Column('max_debt_age_seconds',sa.Integer(),nullable=False),sa.Column('plan_due_seconds',sa.Integer(),nullable=False),sa.Column('milestone_overdue_escalation_seconds',sa.Integer(),nullable=False),sa.Column('executive_acceptance_max_seconds',sa.Integer(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_by',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_debt_aging_assessment',
        sa.Column('debt_aging_assessment_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('exception_debt_id',sa.String(64),nullable=False),sa.Column('debt_burn_down_policy_id',sa.String(64),nullable=False),sa.Column('debt_points',sa.Float(),nullable=False),sa.Column('debt_state',sa.String(24),nullable=False),sa.Column('debt_age_seconds',sa.Integer(),nullable=False),sa.Column('aging_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('assessed_by',sa.String(64),nullable=False),sa.Column('assessed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_debt_burn_down_plan',
        sa.Column('debt_burn_down_plan_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('source_exception_debt_id',sa.String(64),nullable=False),sa.Column('plan_owner',sa.String(64),nullable=False),sa.Column('executive_sponsor',sa.String(64),nullable=False),sa.Column('objective',sa.String(1024),nullable=False),sa.Column('starting_debt_points',sa.Float(),nullable=False),sa.Column('target_debt_points',sa.Float(),nullable=False),sa.Column('opened_at',sa.DateTime(timezone=True),nullable=False),sa.Column('due_at',sa.DateTime(timezone=True),nullable=False),sa.Column('progress_percent',sa.Float(),nullable=False,server_default='0'),sa.Column('state',sa.String(24),nullable=False),sa.Column('closure_evidence_reference',sa.String(256)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_debt_burn_down_milestone',
        sa.Column('debt_burn_down_milestone_id',sa.String(64),primary_key=True),sa.Column('debt_burn_down_plan_id',sa.String(64),nullable=False),sa.Column('sequence_no',sa.Integer(),nullable=False),sa.Column('title',sa.String(256),nullable=False),sa.Column('owner_team',sa.String(128),nullable=False),sa.Column('accountable_owner',sa.String(64),nullable=False),sa.Column('target_debt_reduction_points',sa.Float(),nullable=False),sa.Column('due_at',sa.DateTime(timezone=True),nullable=False),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('evidence_reference',sa.String(256)),sa.Column('escalation_level',sa.Integer(),nullable=False,server_default='0'),sa.Column('state',sa.String(24),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_debt_responsibility',
        sa.Column('debt_responsibility_id',sa.String(64),primary_key=True),sa.Column('debt_burn_down_plan_id',sa.String(64),nullable=False),sa.Column('team_key',sa.String(128),nullable=False),sa.Column('responsible_owner',sa.String(64),nullable=False),sa.Column('accountable_executive',sa.String(64),nullable=False),sa.Column('consulted_json',sa.JSON(),nullable=False),sa.Column('informed_json',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_waiver_freeze',
        sa.Column('waiver_freeze_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('source_exception_debt_id',sa.String(64),nullable=False),sa.Column('source_aging_assessment_id',sa.String(64)),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('activated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('released_at',sa.DateTime(timezone=True)),sa.Column('released_by',sa.String(64)),sa.Column('release_evidence_reference',sa.String(256)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_executive_risk_acceptance',
        sa.Column('executive_risk_acceptance_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('debt_burn_down_plan_id',sa.String(64),nullable=False),sa.Column('residual_risk_summary',sa.String(2048),nullable=False),sa.Column('evidence_reference',sa.String(256),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('requested_at',sa.DateTime(timezone=True),nullable=False),sa.Column('executive_approver_one',sa.String(64)),sa.Column('executive_approver_two',sa.String(64)),sa.Column('starts_at',sa.DateTime(timezone=True),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_debt_governance_event',
        sa.Column('debt_governance_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('plan_id',sa.String(64)),sa.Column('freeze_id',sa.String(64)),sa.Column('executive_acceptance_id',sa.String(64)),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_debt_aging_assessment','journey_recovery_debt_governance_event']:_immutable(t)

def downgrade():
    for t in ['journey_recovery_debt_governance_event','journey_recovery_executive_risk_acceptance','journey_recovery_waiver_freeze','journey_recovery_debt_responsibility','journey_recovery_debt_burn_down_milestone','journey_recovery_debt_burn_down_plan','journey_recovery_debt_aging_assessment','journey_recovery_debt_burn_down_policy']:op.drop_table(t)
