"""Sprint 4R runtime model traffic governance. Revision ID: 0065_sprint4r Revises: 0064_sprint4q"""
from alembic import op
import sqlalchemy as sa
revision='0065_sprint4r';down_revision='0064_sprint4q';branch_labels=None;depends_on=None
def imm(t):
 d=op.get_bind().dialect.name
 if d=='sqlite':
  op.execute(f"CREATE TRIGGER {t}_deny_update BEFORE UPDATE ON {t} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_MODEL_TRAFFIC_GOVERNANCE_EVIDENCE'); END;");op.execute(f"CREATE TRIGGER {t}_deny_delete BEFORE DELETE ON {t} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_MODEL_TRAFFIC_GOVERNANCE_EVIDENCE'); END;")
def upgrade():
 op.create_table('journey_recovery_forecast_traffic_policy',sa.Column('forecast_traffic_policy_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('champion_deployment_key',sa.String(128),nullable=False),sa.Column('candidate_deployment_key',sa.String(128),nullable=False),sa.Column('allowed_canary_steps_json',sa.JSON(),nullable=False),sa.Column('min_requests_per_step',sa.Integer(),nullable=False),sa.Column('max_error_rate',sa.Float(),nullable=False),sa.Column('max_timeout_rate',sa.Float(),nullable=False),sa.Column('max_p95_latency_ms',sa.Float(),nullable=False),sa.Column('max_shadow_divergence',sa.Float(),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('approver_one',sa.String(64)),sa.Column('approver_two',sa.String(64)),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_traffic_allocation',sa.Column('forecast_traffic_allocation_id',sa.String(64),primary_key=True),sa.Column('forecast_traffic_policy_id',sa.String(64),nullable=False),sa.Column('environment',sa.String(16),nullable=False),sa.Column('champion_percentage',sa.Integer(),nullable=False),sa.Column('canary_percentage',sa.Integer(),nullable=False),sa.Column('allocation_version',sa.Integer(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('activated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_prediction_provenance',sa.Column('prediction_request_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('forecast_traffic_policy_id',sa.String(64),nullable=False),sa.Column('forecast_traffic_allocation_id',sa.String(64),nullable=False),sa.Column('subject_key_hash',sa.String(64),nullable=False),sa.Column('serving_role',sa.String(16),nullable=False),sa.Column('deployment_key',sa.String(128),nullable=False),sa.Column('forecast_artifact_deployment_binding_id',sa.String(64),nullable=False),sa.Column('forecast_runtime_model_identity_id',sa.String(64),nullable=False),sa.Column('model_version_id',sa.String(64),nullable=False),sa.Column('forecast_model_artifact_id',sa.String(64),nullable=False),sa.Column('artifact_digest',sa.String(64),nullable=False),sa.Column('prediction_json',sa.JSON(),nullable=False),sa.Column('latency_ms',sa.Float(),nullable=False),sa.Column('serving_status',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_shadow_comparison',sa.Column('forecast_shadow_comparison_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('champion_prediction_request_id',sa.String(64),nullable=False),sa.Column('candidate_model_version_id',sa.String(64),nullable=False),sa.Column('candidate_deployment_key',sa.String(128),nullable=False),sa.Column('champion_value',sa.Float(),nullable=False),sa.Column('shadow_value',sa.Float(),nullable=False),sa.Column('divergence',sa.Float(),nullable=False),sa.Column('comparison_state',sa.String(24),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_serving_budget_assessment',sa.Column('forecast_serving_budget_assessment_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('forecast_traffic_policy_id',sa.String(64),nullable=False),sa.Column('canary_percentage',sa.Integer(),nullable=False),sa.Column('request_count',sa.Integer(),nullable=False),sa.Column('error_rate',sa.Float(),nullable=False),sa.Column('timeout_rate',sa.Float(),nullable=False),sa.Column('p95_latency_ms',sa.Float(),nullable=False),sa.Column('invalid_prediction_rate',sa.Float(),nullable=False),sa.Column('fallback_rate',sa.Float(),nullable=False),sa.Column('availability',sa.Float(),nullable=False),sa.Column('attestation_mismatch_rate',sa.Float(),nullable=False),sa.Column('assessment_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('assessed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_canary_progression',sa.Column('forecast_canary_progression_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('forecast_traffic_policy_id',sa.String(64),nullable=False),sa.Column('from_percentage',sa.Integer(),nullable=False),sa.Column('to_percentage',sa.Integer(),nullable=False),sa.Column('gate_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evidence_reference',sa.String(512),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_traffic_governance_event',sa.Column('forecast_traffic_governance_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('forecast_traffic_policy_id',sa.String(64)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 for t in ['journey_recovery_forecast_prediction_provenance','journey_recovery_forecast_shadow_comparison','journey_recovery_forecast_serving_budget_assessment','journey_recovery_forecast_canary_progression','journey_recovery_forecast_traffic_governance_event']:imm(t)
def downgrade():
 for t in ['journey_recovery_forecast_traffic_governance_event','journey_recovery_forecast_canary_progression','journey_recovery_forecast_serving_budget_assessment','journey_recovery_forecast_shadow_comparison','journey_recovery_forecast_prediction_provenance','journey_recovery_forecast_traffic_allocation','journey_recovery_forecast_traffic_policy']:op.drop_table(t)
