"""Sprint 4V remediation generalization and post-promotion proof. Revision ID: 0069_sprint4v Revises: 0068_sprint4u"""
from alembic import op
import sqlalchemy as sa
revision='0069_sprint4v';down_revision='0068_sprint4u';branch_labels=None;depends_on=None
def imm(t):
 if op.get_bind().dialect.name=='sqlite':
  op.execute(f"CREATE TRIGGER {t}_deny_update BEFORE UPDATE ON {t} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_REMEDIATION_GENERALIZATION_EVIDENCE'); END;")
  op.execute(f"CREATE TRIGGER {t}_deny_delete BEFORE DELETE ON {t} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_REMEDIATION_GENERALIZATION_EVIDENCE'); END;")
def upgrade():
 op.create_table('journey_recovery_forecast_generalization_policy',sa.Column('forecast_generalization_policy_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('minimum_adjacent_samples',sa.Integer(),nullable=False),sa.Column('max_adjacent_regression_pct',sa.Float(),nullable=False),sa.Column('max_holdout_regression_pct',sa.Float(),nullable=False),sa.Column('minimum_target_sustain_improvement_pct',sa.Float(),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('approver_one',sa.String(64)),sa.Column('approver_two',sa.String(64)),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_generalization_validation',sa.Column('forecast_generalization_validation_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('remediation_target_id',sa.String(64),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('segment_key',sa.String(256),nullable=False),sa.Column('sample_count',sa.Integer(),nullable=False),sa.Column('baseline_mae',sa.Float(),nullable=False),sa.Column('challenger_mae',sa.Float(),nullable=False),sa.Column('regression_pct',sa.Float(),nullable=False),sa.Column('validation_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_holdout_validation',sa.Column('forecast_holdout_validation_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('remediation_target_id',sa.String(64),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('holdout_segment_key',sa.String(256),nullable=False),sa.Column('sample_count',sa.Integer(),nullable=False),sa.Column('baseline_mae',sa.Float(),nullable=False),sa.Column('challenger_mae',sa.Float(),nullable=False),sa.Column('regression_pct',sa.Float(),nullable=False),sa.Column('validation_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_post_promotion_proof',sa.Column('forecast_post_promotion_proof_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('remediation_target_id',sa.String(64),nullable=False),sa.Column('promoted_model_version_id',sa.String(64),nullable=False),sa.Column('target_live_improvement_pct',sa.Float(),nullable=False),sa.Column('max_adjacent_regression_pct',sa.Float(),nullable=False),sa.Column('max_holdout_regression_pct',sa.Float(),nullable=False),sa.Column('global_performance_state',sa.String(24),nullable=False),sa.Column('proof_state',sa.String(40),nullable=False),sa.Column('rollback_required',sa.Boolean(),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 op.create_table('journey_recovery_forecast_generalization_event',sa.Column('forecast_generalization_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('remediation_target_id',sa.String(64)),sa.Column('model_version_id',sa.String(64)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
 for t in ['journey_recovery_forecast_generalization_validation','journey_recovery_forecast_holdout_validation','journey_recovery_forecast_post_promotion_proof','journey_recovery_forecast_generalization_event']:imm(t)
def downgrade():
 for t in ['journey_recovery_forecast_generalization_event','journey_recovery_forecast_post_promotion_proof','journey_recovery_forecast_holdout_validation','journey_recovery_forecast_generalization_validation','journey_recovery_forecast_generalization_policy']:op.drop_table(t)
