"""Travel Intelligence Layer 1.0 P0 implementation.

Revision ID: 0112_ti_p0_20260829
Revises: 0111_test_account_expiry
"""
from alembic import op
import sqlalchemy as sa

revision = "0112_ti_p0_20260829"
down_revision = "0111_test_account_expiry"
branch_labels = None
depends_on = None

def upgrade():
    op.create_table("travel_entity",sa.Column("go_entity_id",sa.Uuid(),primary_key=True),sa.Column("entity_type",sa.String(32),nullable=False),sa.Column("canonical_name",sa.Text(),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("length(canonical_name) > 0",name="ck_ti_entity_name"))
    op.create_index("ix_ti_entity_type","travel_entity",["entity_type"]); op.create_index("ix_ti_entity_status","travel_entity",["status"])
    op.create_table("travel_entity_alias",sa.Column("alias_id",sa.Uuid(),primary_key=True),sa.Column("go_entity_id",sa.Uuid(),sa.ForeignKey("travel_entity.go_entity_id"),nullable=False),sa.Column("source_type",sa.String(40),nullable=False),sa.Column("source_entity_id",sa.Text(),nullable=False),sa.Column("normalized_name",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("source_type","source_entity_id",name="uq_ti_alias_source"))
    op.create_index("ix_ti_alias_entity","travel_entity_alias",["go_entity_id"])
    op.create_table("travel_entity_relation",sa.Column("relation_id",sa.Uuid(),primary_key=True),sa.Column("from_entity_id",sa.Uuid(),sa.ForeignKey("travel_entity.go_entity_id"),nullable=False),sa.Column("relation_type",sa.String(48),nullable=False),sa.Column("to_entity_id",sa.Uuid(),sa.ForeignKey("travel_entity.go_entity_id"),nullable=False),sa.Column("valid_from",sa.DateTime(timezone=True)),sa.Column("valid_to",sa.DateTime(timezone=True)),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("from_entity_id <> to_entity_id",name="ck_ti_relation_not_self"))
    op.create_index("ix_ti_relation_from_type","travel_entity_relation",["from_entity_id","relation_type"])
    op.create_table("travel_entity_fact",sa.Column("fact_id",sa.Uuid(),primary_key=True),sa.Column("go_entity_id",sa.Uuid(),sa.ForeignKey("travel_entity.go_entity_id"),nullable=False),sa.Column("fact_type",sa.String(64),nullable=False),sa.Column("fact_value",sa.JSON(),nullable=False),sa.Column("provenance",sa.String(40),nullable=False),sa.Column("source_id",sa.Text()),sa.Column("observed_at",sa.DateTime(timezone=True),nullable=False),sa.Column("valid_from",sa.DateTime(timezone=True)),sa.Column("valid_to",sa.DateTime(timezone=True)),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("verification_state",sa.String(32),nullable=False),sa.Column("evidence_ref",sa.Text()),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("confidence >= 0 AND confidence <= 1",name="ck_ti_fact_confidence"))
    op.create_index("ix_ti_fact_entity_type","travel_entity_fact",["go_entity_id","fact_type","observed_at"])
    op.create_table("travel_intent",sa.Column("intent_id",sa.Uuid(),primary_key=True),sa.Column("traveler_id",sa.String(64),nullable=False),sa.Column("session_id",sa.String(64),nullable=False),sa.Column("raw_input",sa.Text(),nullable=False),sa.Column("normalized_intent",sa.JSON(),nullable=False),sa.Column("consent_scope",sa.JSON(),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.Column("updated_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_ti_intent_traveler","travel_intent",["traveler_id"]); op.create_index("ix_ti_intent_session","travel_intent",["session_id"])
    op.create_table("travel_intent_constraint",sa.Column("constraint_id",sa.Uuid(),primary_key=True),sa.Column("intent_id",sa.Uuid(),sa.ForeignKey("travel_intent.intent_id"),nullable=False),sa.Column("key",sa.String(64),nullable=False),sa.Column("value_json",sa.JSON(),nullable=False),sa.Column("source",sa.String(32),nullable=False),sa.Column("confidence",sa.Float(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("confidence >= 0 AND confidence <= 1",name="ck_ti_constraint_confidence"))
    op.create_index("ix_ti_constraint_intent","travel_intent_constraint",["intent_id"])
    op.create_table("travel_behavior_event",sa.Column("event_id",sa.Uuid(),primary_key=True),sa.Column("event_type",sa.String(64),nullable=False),sa.Column("occurred_at",sa.DateTime(timezone=True),nullable=False),sa.Column("actor_type",sa.String(32),nullable=False),sa.Column("actor_id",sa.String(64)),sa.Column("tenant_id",sa.String(64)),sa.Column("organization_id",sa.String(64)),sa.Column("traveler_id",sa.String(64)),sa.Column("session_id",sa.String(64)),sa.Column("intent_id",sa.Uuid()),sa.Column("entity_id",sa.Uuid()),sa.Column("decision_id",sa.Uuid()),sa.Column("trip_id",sa.String(64)),sa.Column("order_id",sa.String(64)),sa.Column("transaction_root_id",sa.String(64)),sa.Column("source",sa.String(32),nullable=False),sa.Column("schema_version",sa.String(16),nullable=False),sa.Column("correlation_id",sa.String(64),nullable=False),sa.Column("causation_id",sa.String(64)),sa.Column("idempotency_key",sa.String(160),nullable=False,unique=True),sa.Column("privacy_class",sa.String(16),nullable=False),sa.Column("retention_class",sa.String(24),nullable=False),sa.Column("payload_schema",sa.String(96)),sa.Column("payload",sa.JSON(),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_ti_event_corr","travel_behavior_event",["correlation_id","occurred_at"]); op.create_index("ix_ti_event_type","travel_behavior_event",["event_type"])
    op.create_table("ai_decision",sa.Column("decision_id",sa.Uuid(),primary_key=True),sa.Column("previous_hash",sa.String(64)),sa.Column("decision_hash",sa.String(64),nullable=False,unique=True),sa.Column("input_snapshot_hash",sa.String(64),nullable=False),sa.Column("evidence_snapshot_hash",sa.String(64),nullable=False),sa.Column("rule_version",sa.String(64),nullable=False),sa.Column("prompt_version",sa.String(64),nullable=False),sa.Column("model_version",sa.String(128),nullable=False),sa.Column("input_snapshot",sa.JSON(),nullable=False),sa.Column("evidence_snapshot",sa.JSON(),nullable=False),sa.Column("output_snapshot",sa.JSON(),nullable=False),sa.Column("correlation_id",sa.String(64),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False))
    op.create_index("ix_ti_decision_corr","ai_decision",["correlation_id"])
    op.create_table("ai_decision_model_call",sa.Column("model_call_id",sa.Uuid(),primary_key=True),sa.Column("decision_id",sa.Uuid(),sa.ForeignKey("ai_decision.decision_id"),nullable=False),sa.Column("routing_decision_id",sa.String(64),nullable=False),sa.Column("session_id",sa.String(64),nullable=False),sa.Column("capability",sa.String(48),nullable=False),sa.Column("cost_scope",sa.String(24),nullable=False),sa.Column("business_reference_id",sa.String(96)),sa.Column("tier",sa.Integer(),nullable=False),sa.Column("provider_id",sa.String(64)),sa.Column("model_version",sa.String(128),nullable=False),sa.Column("price_snapshot_id",sa.String(96),nullable=False),sa.Column("estimated_quality",sa.Float(),nullable=False),sa.Column("input_tokens",sa.Integer(),nullable=False),sa.Column("output_tokens",sa.Integer(),nullable=False),sa.Column("estimated_cost_usd",sa.Float(),nullable=False),sa.Column("attributed_revenue_usd",sa.Float(),nullable=False),sa.Column("latency_ms",sa.Integer(),nullable=False),sa.Column("status",sa.String(24),nullable=False),sa.Column("created_at",sa.DateTime(timezone=True),nullable=False),sa.CheckConstraint("estimated_quality >= 0 AND estimated_quality <= 1",name="ck_ti_model_quality"),sa.CheckConstraint("estimated_cost_usd >= 0",name="ck_ti_model_cost"),sa.CheckConstraint("attributed_revenue_usd >= 0",name="ck_ti_model_revenue"),sa.CheckConstraint("input_tokens >= 0 AND output_tokens >= 0",name="ck_ti_model_tokens"))
    op.create_index("ix_ti_model_call_decision","ai_decision_model_call",["decision_id"]); op.create_index("ix_ti_model_call_route","ai_decision_model_call",["routing_decision_id"]); op.create_index("ix_ti_model_call_session","ai_decision_model_call",["session_id","created_at"]); op.create_index("ix_ti_model_call_scope","ai_decision_model_call",["cost_scope","business_reference_id"])
    op.create_table("transaction_relation",sa.Column("relation_id",sa.Uuid(),primary_key=True),sa.Column("source_truth_domain",sa.String(32),nullable=False),sa.Column("source_truth_id",sa.Text(),nullable=False),sa.Column("relation_type",sa.String(48),nullable=False),sa.Column("subject_id",sa.Text(),nullable=False),sa.Column("object_id",sa.Text(),nullable=False),sa.Column("source_event_id",sa.Text(),nullable=False),sa.Column("projected_at",sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint("source_truth_domain","source_truth_id","relation_type","subject_id","object_id",name="uq_ti_transaction_projection"))
    op.create_index("ix_ti_transaction_subject","transaction_relation",["subject_id","relation_type"])

def downgrade():
    op.drop_table("transaction_relation"); op.drop_table("ai_decision_model_call"); op.drop_table("ai_decision"); op.drop_table("travel_behavior_event"); op.drop_table("travel_intent_constraint"); op.drop_table("travel_intent"); op.drop_table("travel_entity_fact"); op.drop_table("travel_entity_relation"); op.drop_table("travel_entity_alias"); op.drop_table("travel_entity")
