"""GO V6.1 controlling master baseline.

This module intentionally contains product/governance invariants, not mutable supplier facts.
It gives runtime and tests a single GO-owned source for the current controlling master version.
"""
MASTER_VERSION = 'V6.1'
MASTER_DATE = "2026-08-22"
MASTER_NAME = "GO Ultimate Master Plan V6.1 + Three-Tier Strategic Positioning + Virtual Direct + Finance + GO Star Equivalent + AI Distribution Constitution"


STRATEGIC_POSITIONING = (
    "AI时代的全球旅行入口",
    "AI时代的全球旅行基础设施",
    "AI时代的全球旅行官方直订平台",
)
IDENTITY_TRANSACTION_INFRASTRUCTURE_EXPLANATION = "旅行身份与交易基础设施是AI时代全球旅行基础设施的核心能力内涵"
IDENTITY_TRANSACTION_INFRASTRUCTURE_POSITIONING = IDENTITY_TRANSACTION_INFRASTRUCTURE_EXPLANATION
OFFICIAL_DIRECT_PLATFORM_POSITIONING = "AI时代的全球旅行官方直订平台"
OFFICIAL_DIRECT_NETWORK_ASSET = "全球旅行官方直连网络"
OFFICIAL_DIRECT_PRODUCT_TERM = "GO直连"

PRODUCT_VOCABULARY = {
    "go_direct": "GO直连",
    "go_ai": "GO AI",
    "go_recommend": "GO推荐",
    "go_privileges": "GO礼遇",
    "go_offer": "GO Offer",
}

HOTEL_PAGE_PRINCIPLE = "GO_PAGE_FIRST_REGISTRATION_ENHANCES_NOT_CREATES"
GO_DIRECT_STATES = ("NOT_REGISTERED", "REGISTRATION_PENDING", "GO_DIRECT_VERIFIED", "GO_DIRECT_LIVE")
SUPPLY_PRINCIPLE = "DIRECT_FIRST_AUTHORIZED_MULTI_FALLBACK"
PAYMENT_PRINCIPLE = "PSP_CONTROLLED_DELAYED_SETTLEMENT"
PRODUCTION_TRUTH_PRINCIPLE = "ENGINEERING_COMPLETE_DOES_NOT_EQUAL_GO_LIVE"
PROFILE_PORTABILITY_PRINCIPLE = "USER_CONTROLLED_UNIVERSAL_IMPORT_PERSONAL_TRAVEL_VAULT"
PROFILE_RELEASE_PRINCIPLE = "PURPOSE_BOUND_MINIMUM_NECESSARY_DATA_RELEASE"

AI_TRAVEL_INFRASTRUCTURE_PRINCIPLE = "EVERY_AI_CAN_UNDERSTAND_TRAVEL_GO_COMPLETES_TRAVEL"
AI_INTERFACE_PRINCIPLE = "GO_PROVIDES_CAPABILITY_NOT_COMPULSORY_UI_OWNERSHIP"
AI_NEUTRALITY_PRINCIPLE = "GO_SERVES_ALL_AUTHORIZED_AI_AGENTS_WITHOUT_SINGLE_MODEL_LOCK_IN"
AI_IDENTITY_RELEASE_PRINCIPLE = "PURPOSE_BOUND_MINIMUM_NECESSARY_CONSENTED_RELEASE"
AI_AGENT_CLIENT_CLASS = "AI_AGENT"

LOCKED_INVARIANTS = (
    "GO_DIRECT_IS_THE_ONLY_ACTIVE_PRODUCT_TERM",
    "HOTEL_PAGE_EXISTS_BEFORE_HOTEL_REGISTRATION",
    "CONTENT_TRUTH_SUPPLY_TRUTH_TRANSACTION_ROUTE_ARE_SEPARATE",
    "NO_SINGLE_THIRD_PARTY_FALLBACK_MAY_BECOME_GO_CORE",
    "PSP_CONTROLS_CUSTOMER_FUNDS_AND_REFUNDS",
    "MOCK_OR_SIMULATOR_MUST_NOT_CREATE_PRODUCTION_SUCCESS_FACTS",
    "SUPPLIER_TIMEOUT_IS_NOT_PERMISSION_TO_RESEND",
    "GO_OWNS_ROOT_KMS_PAYMENT_SUPPLIER_AND_STORE_SIGNING_CONTROL",
    "NO_THIRD_PARTY_OTA_PASSWORD_CAPTURE_OR_SIMULATED_PRIVATE_LOGIN",
    "AI_EXTRACTED_SENSITIVE_PROFILE_FACT_IS_NOT_VERIFIED_FACT",
    "PROFILE_CONFLICTS_MUST_NOT_SILENTLY_OVERWRITE",
    "AI_AND_SUPPLIER_HAVE_NO_FULL_PERSONAL_VAULT_ACCESS",
    "RECOMMENDATION_POOL_AND_VALUE_POOL_ARE_PERMANENTLY_SEPARATE",
    "THREE_PERCENT_IS_A_HEALTHY_DIRECT_VALUE_ANCHOR_NOT_A_MANDATORY_PRICE_OR_RECOMMENDATION_GATE",
    "SUPPLIER_KEEPS_MAJORITY_OF_CHANNEL_SAVINGS_AND_MAY_SHARE_A_SMALL_PART_WITH_CONSUMER",
    "DIRECT_VALUE_PRIORITY_IS_UPGRADE_THEN_LATE_CHECKOUT_THEN_CASH_THEN_BREAKFAST",
    "MARKET_BENCHMARK_EXISTS_TO_STRENGTHEN_OFFICIAL_DIRECT_NOT_REPLACE_IT",
    "OFFICIAL_DIRECT_BOOKING_PLATFORM_IS_THE_THIRD_STRATEGIC_POSITIONING",
    "TRAVEL_IDENTITY_AND_TRANSACTION_INFRASTRUCTURE_IS_EXPLANATION_OF_SECOND_STRATEGIC_POSITIONING",
    "GO_DIRECT_REMAINS_THE_CONNECTION_PRODUCT_TERM",
    "OFFICIAL_DIRECT_NETWORK_IS_THE_UNDERLYING_SUPPLY_CONNECTION_ASSET",
    "AI_AGENT_IS_A_FIRST_CLASS_GO_DISTRIBUTION_CLIENT",
    "EXTERNAL_AI_NEVER_RECEIVES_FULL_PERSONAL_TRAVEL_VAULT",
    "GO_TRANSACTION_TRUTH_REQUIRES_PROVIDER_AND_PAYMENT_EVIDENCE",
    "GO_DOES_NOT_REQUIRE_UI_OWNERSHIP_TO_COMPLETE_TRAVEL",
    "HOTEL_OWNS_PRICE_AND_GO_MUST_NOT_AUTO_CHANGE_IT",
    "HOTEL_CONTROLS_VIRTUAL_DIRECT_INVENTORY",
    "VIRTUAL_DIRECT_IS_DEFAULT_SUPPLIER_OPERATING_MODE",
    "GO_STAR_EQUIVALENT_USES_NATIONAL_STANDARD_REFERENCE_AND_IS_SEPARATE_FROM_RECOMMENDATION",
    "GO_DOES_NOT_BUY_AI_DISTRIBUTION",
    "AUTHORIZED_AI_BASE_CALLS_ARE_FREE",
)

SUPPLIER_SUBSCRIPTION_TIER_ANCHORS_CNY = {
    "UP_TO_TWO_DIAMOND_Y1": 399,
    "THREE_DIAMOND_Y1": 699,
    "FOUR_DIAMOND_Y1": 999,
    "FIVE_DIAMOND_Y1": 1999,
    "FOUR_DIAMOND_Y2_LE_130": 999,
    "FOUR_DIAMOND_Y2_GT_130": 1299,
    "FIVE_DIAMOND_Y2_LT_200": 1999,
    "FIVE_DIAMOND_Y2_200_300": 2999,
    "FIVE_DIAMOND_Y2_GT_300": 3999,
}
T20_FREE_VALID_OFFICIAL_DIRECT_ORDERS = 20
T20_FINAL_COMPLETION_TARGET = 1.0
EQUIVALENT_BILLING_MONTHS = 10
VIRTUAL_DIRECT_PRINCIPLE = "HOTEL_OWNS_PRICE_HOTEL_CONTROLS_INVENTORY_GO_PROVIDES_LOW_COST_CHANNEL"
GO_STAR_EQUIVALENT_REFERENCE = "GB/T 14308-2023"
AI_DISTRIBUTION_PRINCIPLE = "GO_DOES_NOT_BUY_DISTRIBUTION_GO_EARNS_DISTRIBUTION_THROUGH_VALUE"
AI_BASE_INFRASTRUCTURE_CALL_PRICE_CNY = 0
