"""Sprint 4H executive risk portfolio and enterprise risk limits.
Revision ID: 0055_sprint4h
Revises: 0054_sprint4g
"""
from alembic import op
import sqlalchemy as sa
revision='0055_sprint4h';down_revision='0054_sprint4g';branch_labels=None;depends_on=None

def _immutable(table):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_ENTERPRISE_RISK_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_ENTERPRISE_RISK_EVIDENCE'); END;")
    elif d=='postgresql':
        op.execute("""CREATE OR REPLACE FUNCTION deny_enterprise_risk_evidence_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'IMMUTABLE_ENTERPRISE_RISK_EVIDENCE'; END; $$ LANGUAGE plpgsql;""")
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_enterprise_risk_evidence_mutation();")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_enterprise_risk_evidence_mutation();")

def upgrade():
    op.create_table('journey_recovery_enterprise_risk_limit',sa.Column('enterprise_risk_limit_id',sa.String(64),primary_key=True),sa.Column('limit_key',sa.String(128),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('environment',sa.String(16),nullable=False),sa.Column('max_aggregate_exposure_points',sa.Float(),nullable=False),sa.Column('max_team_concentration_pct',sa.Float(),nullable=False),sa.Column('max_risk_domain_concentration_pct',sa.Float(),nullable=False),sa.Column('max_correlated_exposure_points',sa.Float(),nullable=False),sa.Column('max_active_acceptances',sa.Integer(),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('board_approver_one',sa.String(64)),sa.Column('board_approver_two',sa.String(64)),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_executive_risk_position',sa.Column('risk_position_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('executive_risk_acceptance_id',sa.String(64),nullable=False),sa.Column('team_key',sa.String(128),nullable=False),sa.Column('risk_domain',sa.String(128),nullable=False),sa.Column('exposure_points',sa.Float(),nullable=False),sa.Column('correlation_keys_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('registered_by',sa.String(64),nullable=False),sa.Column('registered_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_executive_risk_portfolio_assessment',sa.Column('portfolio_assessment_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('enterprise_risk_limit_id',sa.String(64),nullable=False),sa.Column('active_acceptance_count',sa.Integer(),nullable=False),sa.Column('aggregate_exposure_points',sa.Float(),nullable=False),sa.Column('max_team_concentration_pct',sa.Float(),nullable=False),sa.Column('max_risk_domain_concentration_pct',sa.Float(),nullable=False),sa.Column('max_correlated_exposure_points',sa.Float(),nullable=False),sa.Column('portfolio_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('metrics_json',sa.JSON(),nullable=False),sa.Column('assessed_by',sa.String(64),nullable=False),sa.Column('assessed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_residual_risk_concentration',sa.Column('concentration_assessment_id',sa.String(64),primary_key=True),sa.Column('portfolio_assessment_id',sa.String(64),nullable=False),sa.Column('dimension',sa.String(32),nullable=False),sa.Column('dimension_key',sa.String(128),nullable=False),sa.Column('exposure_points',sa.Float(),nullable=False),sa.Column('concentration_pct',sa.Float(),nullable=False),sa.Column('breached',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_portfolio_freeze',sa.Column('portfolio_freeze_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('source_portfolio_assessment_id',sa.String(64),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('activated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('released_at',sa.DateTime(timezone=True)),sa.Column('released_by',sa.String(64)),sa.Column('release_evidence_reference',sa.String(256)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_enterprise_risk_event',sa.Column('enterprise_risk_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('risk_position_id',sa.String(64)),sa.Column('portfolio_assessment_id',sa.String(64)),sa.Column('portfolio_freeze_id',sa.String(64)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_executive_risk_portfolio_assessment','journey_recovery_residual_risk_concentration','journey_recovery_enterprise_risk_event']:_immutable(t)

def downgrade():
    for t in ['journey_recovery_enterprise_risk_event','journey_recovery_portfolio_freeze','journey_recovery_residual_risk_concentration','journey_recovery_executive_risk_portfolio_assessment','journey_recovery_executive_risk_position','journey_recovery_enterprise_risk_limit']:op.drop_table(t)
