"""Sprint 4P model artifact registry, signed build attestation and supply-chain integrity governance.
Revision ID: 0063_sprint4p
Revises: 0062_sprint4o
"""
from alembic import op
import sqlalchemy as sa
revision='0063_sprint4p';down_revision='0062_sprint4o';branch_labels=None;depends_on=None

def imm(table):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_FORECAST_ARTIFACT_GOVERNANCE_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_FORECAST_ARTIFACT_GOVERNANCE_EVIDENCE'); END;")
    elif d=='postgresql':
        op.execute("""CREATE OR REPLACE FUNCTION deny_forecast_artifact_governance_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'IMMUTABLE_FORECAST_ARTIFACT_GOVERNANCE_EVIDENCE'; END; $$ LANGUAGE plpgsql;""")
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_forecast_artifact_governance_mutation();")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_forecast_artifact_governance_mutation();")

def upgrade():
    op.create_table('journey_recovery_forecast_artifact_policy',sa.Column('forecast_artifact_policy_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('require_sbom',sa.Boolean(),nullable=False),sa.Column('require_signed_attestation',sa.Boolean(),nullable=False),sa.Column('require_promotion_binding',sa.Boolean(),nullable=False),sa.Column('allowed_package_formats_json',sa.JSON(),nullable=False),sa.Column('allowed_builder_key_refs_json',sa.JSON(),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('approver_one',sa.String(64)),sa.Column('approver_two',sa.String(64)),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_model_artifact',sa.Column('forecast_model_artifact_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('training_manifest_id',sa.String(64),nullable=False),sa.Column('build_hash',sa.String(64),nullable=False),sa.Column('package_ref',sa.String(512),nullable=False),sa.Column('package_format',sa.String(32),nullable=False),sa.Column('artifact_digest',sa.String(64),nullable=False),sa.Column('artifact_size_bytes',sa.Integer(),nullable=False),sa.Column('registry_namespace',sa.String(128),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('registered_by',sa.String(64),nullable=False),sa.Column('registered_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_artifact_sbom',sa.Column('forecast_artifact_sbom_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('forecast_model_artifact_id',sa.String(64),nullable=False),sa.Column('sbom_format',sa.String(32),nullable=False),sa.Column('components_json',sa.JSON(),nullable=False),sa.Column('sbom_digest',sa.String(64),nullable=False),sa.Column('provenance_json',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_build_attestation',sa.Column('forecast_build_attestation_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('forecast_model_artifact_id',sa.String(64),nullable=False),sa.Column('training_manifest_id',sa.String(64),nullable=False),sa.Column('build_hash',sa.String(64),nullable=False),sa.Column('artifact_digest',sa.String(64),nullable=False),sa.Column('sbom_digest',sa.String(64),nullable=False),sa.Column('builder_identity',sa.String(128),nullable=False),sa.Column('signing_key_ref',sa.String(256),nullable=False),sa.Column('attestation_payload_hash',sa.String(64),nullable=False),sa.Column('signature',sa.String(128),nullable=False),sa.Column('verification_state',sa.String(24),nullable=False),sa.Column('evidence_reference',sa.String(512),nullable=False),sa.Column('verified_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_artifact_promotion_binding',sa.Column('forecast_artifact_promotion_binding_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('challenger_model_version_id',sa.String(64),nullable=False),sa.Column('forecast_model_artifact_id',sa.String(64),nullable=False),sa.Column('training_manifest_id',sa.String(64),nullable=False),sa.Column('forecast_build_attestation_id',sa.String(64),nullable=False),sa.Column('build_hash',sa.String(64),nullable=False),sa.Column('artifact_digest',sa.String(64),nullable=False),sa.Column('binding_hash',sa.String(64),nullable=False),sa.Column('binding_state',sa.String(24),nullable=False),sa.Column('bound_by',sa.String(64),nullable=False),sa.Column('bound_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_artifact_integrity_assessment',sa.Column('forecast_artifact_integrity_assessment_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('forecast_model_artifact_id',sa.String(64),nullable=False),sa.Column('expected_artifact_digest',sa.String(64),nullable=False),sa.Column('observed_artifact_digest',sa.String(64),nullable=False),sa.Column('expected_build_hash',sa.String(64),nullable=False),sa.Column('observed_build_hash',sa.String(64),nullable=False),sa.Column('integrity_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evidence_reference',sa.String(512),nullable=False),sa.Column('assessed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_artifact_governance_event',sa.Column('forecast_artifact_governance_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('challenger_model_version_id',sa.String(64)),sa.Column('forecast_model_artifact_id',sa.String(64)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_forecast_model_artifact','journey_recovery_forecast_artifact_sbom','journey_recovery_forecast_build_attestation','journey_recovery_forecast_artifact_promotion_binding','journey_recovery_forecast_artifact_integrity_assessment','journey_recovery_forecast_artifact_governance_event']: imm(t)

def downgrade():
    for t in ['journey_recovery_forecast_artifact_governance_event','journey_recovery_forecast_artifact_integrity_assessment','journey_recovery_forecast_artifact_promotion_binding','journey_recovery_forecast_build_attestation','journey_recovery_forecast_artifact_sbom','journey_recovery_forecast_model_artifact','journey_recovery_forecast_artifact_policy']: op.drop_table(t)
