from __future__ import annotations

EVENT_TYPES = {
    "INTENT_CREATED","INTENT_REFINED","SEARCH_EXECUTED","ENTITY_IMPRESSION","ENTITY_VIEWED","ENTITY_SAVED","ENTITY_REJECTED","ENTITY_COMPARED",
    "JUDGMENT_REQUESTED","JUDGMENT_COMPLETED","RECOMMENDATION_SHOWN","RECOMMENDATION_ACCEPTED","RECOMMENDATION_REJECTED","OFFER_VIEWED","OFFER_SELECTED",
    "BOOKING_STARTED","BOOKING_CREATED","PAYMENT_CONFIRMED","SUPPLIER_CONFIRMED","BOOKING_CANCELLED","REFUND_COMPLETED","TRIP_STARTED","TRIP_COMPLETED","REVIEW_CREATED","REBOOKED"
}
ACTOR_TYPES = {"TRAVELER","SUPPLIER","GO_ADMIN","GO_SYSTEM","MODEL","EXTERNAL_SYSTEM"}
SOURCES = {"CONSUMER","SUPPLIER","ADMIN","DOMAIN_SERVICE","EVENT_PROJECTION","MODEL_GATEWAY","PUBLIC_PROVIDER","OFFICIAL_PROVIDER"}
PRIVACY_CLASSES = {"PUBLIC","INTERNAL","PERSONAL","SENSITIVE"}
RETENTION_CLASSES = {"TRANSIENT_30D","OPERATIONAL_400D","AUDIT_7Y","LEGAL_HOLD"}
CAPABILITIES = {"INTENT_EXTRACTION","ENTITY_RESOLUTION","QUERY_REWRITE","TRAVEL_REASONING","REVIEW_ANALYSIS","EXPLANATION"}
ENTITY_TYPES = {"HOTEL","ROOM_TYPE","BRAND","HOTEL_GROUP","CITY","DISTRICT","DESTINATION","POI","AIRPORT","STATION","FLIGHT","RAIL_SERVICE","ATTRACTION","EXPERIENCE","RIDE_PRODUCT","RENTAL_PRODUCT"}
TRANSACTION_TRUTH_DOMAINS = {"ORDER","PAYMENT_LEDGER","SUPPLIER_FULFILLMENT","REFUND","TRIP"}
