import {createRequire} from 'node:module';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
const require=createRequire(import.meta.url),{chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const base=process.env.TICKET_BROWSER_ROOT,origin='http://127.0.0.1:4187',out=base+'/evidence';await fs.mkdir(out,{recursive:true});
const state=process.env.TICKET_BROWSER_STATE;
const credentials=JSON.parse(await fs.readFile(state+'/credentials.private.json','utf8'));
const suppliers=JSON.parse(await fs.readFile(state+'/suppliers.private.json','utf8'));
const ops=JSON.parse(await fs.readFile(state+'/operations.private.json','utf8'));
const report={binding:JSON.parse(await fs.readFile(base+'/binding.json','utf8')),mode:'ISOLATED_SQLITE_CHROMIUM',native_device:'NOT_RUN',events:[],steps:[],errors:[]};
const browser=await chromium.launch({headless:true});report.browser=browser.version();
const day=n=>new Date(Date.now()+n*86400000).toISOString().slice(0,10);
let consumer, supplier, admin,checker,oid,quoteId;
async function page(role,account,width=1440){
 const context=await browser.newContext({viewport:{width,height:950},locale:'zh-CN'});await context.route('**/*',r=>new URL(r.request().url()).origin===origin?r.continue():r.abort());
 const p=await context.newPage();p.setDefaultTimeout(15000);p.on('pageerror',e=>report.errors.push({role,message:e.message}));
 p.on('response',r=>{const path=new URL(r.url()).pathname;if(path.startsWith('/v1/')||path.startsWith('/internal/'))report.events.push({role,path,status:r.status(),method:r.request().method()});});
 await p.goto(origin+({consumer:'/go-app/',supplier:'/supplier-console/',admin:'/go-admin/'}[role]));
 if(role==='consumer'){await p.locator('#accountBtn').click();await p.locator('#email').fill(account.username);await p.locator('#pwd').fill(account.password);await p.locator('#login').click();await p.locator('#email').waitFor({state:'detached'});}
 else{await p.locator('#user').fill(account.username);await p.locator('#pass').fill(account.password);await p.locator('form#login button').first().click();await p.locator('.shell').waitFor();}
 return p;
}
async function step(name,p,fn){try{await fn();report.steps.push({name,result:'PASS'});}catch(e){report.steps.push({name,result:'FAIL',error:e.message,visible:(await p.locator('body').innerText()).slice(-6000)});throw e;}finally{await p.screenshot({path:out+'/'+report.steps.length+'-'+name+'.png',fullPage:true});await fs.writeFile(out+'/results.json',JSON.stringify(report,null,2));}}
async function dialog(p){const d=p.locator('dialog[open]');await d.waitFor();if(await d.locator('#goPartyCount').count())await d.locator('#goPartyCount').selectOption('2');for(const el of await d.locator('[data-traveler],[data-consent],[data-quote-consent]').all())await el.check();const title=await d.locator('h2').first().innerText();await d.locator('[type=submit]').click();await p.waitForFunction(t=>document.querySelector('dialog[open] h2')?.textContent!==t,title);}
async function work(p,action,note='隔离验收处理',receipt=null){const f=p.locator('[data-ticket-form]');await f.locator('[name=action]').selectOption(action);await f.locator('[name=note]').fill(note);if(receipt)for(const [k,v] of Object.entries(receipt)){const el=f.locator(`[name=${k}]`);if(k==='state')await el.selectOption(v);else await el.fill(v);}const response=p.waitForResponse(r=>r.request().method()==='POST'&&r.url().includes('/ticket-operations/'));await f.locator('[type=submit]').click();const r=await response;assert.equal(r.status(),200,await r.text());const result=await r.json();await p.locator(`[data-ticket-form][data-ticket-revision="${result.data.workflow.revision}"]`).waitFor();}
async function adminOrder(p){await p.goto(origin+'/go-admin/#/vertical-flight');await p.locator('#adminOrderId').fill(oid);await p.locator('#adminOrderSearch [type=submit]').click();await p.locator('[data-ticket-links]').getByRole('button',{name:oid,exact:true}).click();await p.locator('[data-ticket-form]').waitFor();}
try{
 consumer=await page('consumer',credentials.consumer,390);supplier=await page('supplier',suppliers.FLIGHT);admin=await page('admin',ops.maker);checker=await page('admin',ops.checker);
 await step('travelers',consumer,async()=>{await consumer.locator('#accountBtn').click();for(const [name,rel] of [['GO TEST ADULT A','SELF'],['GO TEST ADULT B','FAMILY']]){await consumer.locator('#vmAdd').click();const d=consumer.locator('dialog[open]');await d.locator('#pvName').fill(name);await d.locator('#pvRel').selectOption(rel);await d.locator('#pvPhone').fill('13800000000');await d.locator('#pvLicense').fill('TEST-ISOLATED');await d.locator('[data-confirm]').check();await d.locator('[type=submit]').click();await d.waitFor({state:'detached'});}});
 await step('book-flight',consumer,async()=>{
  await consumer.goto(origin+'/go-app/');await consumer.locator('[data-home-vertical=FLIGHT]').click();await consumer.locator('#jAdults').selectOption('2');
  await consumer.locator('[data-j-field=origin][data-leg="0"]').fill('SHA');await consumer.locator('[data-j-field=destination][data-leg="0"]').fill('PEK');await consumer.locator('[data-j-field=departure_date][data-leg="0"]').fill(day(30));await consumer.locator('[data-j-field=departure_date][data-leg="1"]').fill(day(35));
  await consumer.locator('#jSubmit').click();await consumer.locator('[data-select]').last().click();await consumer.locator('[data-select]').last().click();await consumer.locator('#jCompose').click();await consumer.locator('#jPrebook').click();await consumer.locator('#jCreate').click();await dialog(consumer);
  const checkout=consumer.waitForResponse(r=>r.request().method()==='POST'&&r.url().includes('/checkout/FLIGHT/'));await dialog(consumer);const r=await checkout;assert.equal(r.status(),200);oid=new URL(r.url()).pathname.split('/')[5];report.order_id=oid;await consumer.locator('#jChange').waitFor();
 });
 await step('partial-change',consumer,async()=>{await consumer.locator('#jChange').click();const d=consumer.locator('dialog[open]');await d.locator('[data-flight-change-coupon]').first().check();await d.locator('[data-coupon-change-date]').first().fill(day(31));const response=consumer.waitForResponse(r=>r.url().endsWith('/change-quote')&&r.ok());await dialog(consumer);quoteId=(await (await response).json()).data.quote_id;await dialog(consumer);await consumer.getByText('改签处理中',{exact:false}).first().waitFor();});
 await step('supplier-receipt',supplier,async()=>{await supplier.goto(origin+'/supplier-console/#/orders');await supplier.getByText(oid,{exact:true}).click();await supplier.locator('[data-ticket-form]').waitFor();await work(supplier,'REGISTER');await work(supplier,'CLAIM');await work(supplier,'RECEIPT','已核对所选乘客',{state:'TICKETED',evidence_reference:'isolated://browser-change',supplier_reference:'WEBPART',ticket_numbers:'BROWSER-ONE',quote_id:quoteId});});
 await step('operator-apply',admin,async()=>{await adminOrder(admin);await work(admin,'APPLY');await admin.getByText('BROWSER-ONE',{exact:false}).first().waitFor();});
 await step('independent-verify',checker,async()=>{await adminOrder(checker);await work(checker,'VERIFY');await work(checker,'FOLLOW_UP','已确认消费者端新票号和保留票券');});
 await step('consumer-partial-refund',consumer,async()=>{await consumer.locator('#jTrips').click();await consumer.locator('#tripQuery').fill(oid);await consumer.locator('[data-go-trip-index]').first().click();await consumer.getByText('BROWSER-ONE',{exact:false}).first().waitFor();await consumer.locator('[data-checkin-coupon]').first().getByText(day(31),{exact:false}).waitFor();await consumer.locator('#jCouponRefund').click();await consumer.locator('[data-flight-refund-coupon]').first().check();await dialog(consumer);const refreshed=consumer.waitForResponse(r=>new URL(r.url()).pathname===`/v1/flights/orders/${oid}`&&r.request().method()==='GET'&&r.ok());await dialog(consumer);const facts=(await (await refreshed).json()).data.money_summary;assert.equal(facts.verified,true);assert.ok(facts.refunded_minor>0);assert.equal(facts.net_minor,facts.captured_minor-facts.refunded_minor);report.money_summary=facts;await consumer.waitForFunction(expected=>document.querySelector('[data-coupon-net]')?.textContent===expected,'净实付 '+new Intl.NumberFormat('zh-CN',{style:'currency',currency:facts.currency}).format(facts.net_minor/100));await consumer.getByText('已退票',{exact:false}).first().waitFor();await consumer.getByText('该票券已退票，不可值机',{exact:true}).waitFor();assert.equal(await consumer.locator('[data-checkin-coupon]').first().locator('a').count(),0);});
 assert.deepEqual(report.errors,[]);report.result='PASS';
}catch(e){report.result='FAIL';report.error=e.message;process.exitCode=1;}
finally{await fs.writeFile(out+'/results.json',JSON.stringify(report,null,2));await browser.close();console.log(JSON.stringify({result:report.result,steps:report.steps.map(({name,result})=>({name,result})),error:report.error}));}
