import React from 'react';
import {View,Text,Pressable,StyleSheet,TextInput} from 'react-native';
export const C={navy:'#071A3A',coral:'#FF4A3D',ivory:'#F7F3EC',slate:'#6B7686',line:'#E6E8EC',white:'#FFFFFF',green:'#1B7F5A'};
export const S=StyleSheet.create({
 page:{flex:1,backgroundColor:C.ivory},content:{padding:20,paddingBottom:40},title:{fontSize:28,fontWeight:'800',color:C.navy},h2:{fontSize:20,fontWeight:'800',color:C.navy},sub:{fontSize:14,color:C.slate,marginTop:6,lineHeight:20},card:{backgroundColor:C.white,borderRadius:20,padding:16,marginTop:14,borderWidth:1,borderColor:'#F0F1F3'},
 button:{backgroundColor:C.navy,paddingVertical:15,paddingHorizontal:18,borderRadius:14,marginTop:12,alignItems:'center'},secondaryButton:{backgroundColor:C.white,paddingVertical:14,paddingHorizontal:16,borderRadius:14,marginTop:10,alignItems:'center',borderWidth:1,borderColor:C.navy},buttonText:{color:C.white,fontWeight:'800'},secondaryText:{color:C.navy,fontWeight:'800'},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},price:{fontSize:22,fontWeight:'800',color:C.navy},pill:{paddingHorizontal:10,paddingVertical:6,borderRadius:999,backgroundColor:'#F1F3F6',marginRight:8,marginTop:8},pillText:{fontSize:12,color:C.navy},input:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:14,paddingHorizontal:14,paddingVertical:13,marginTop:10,color:C.navy},divider:{height:1,backgroundColor:C.line,marginVertical:14},success:{color:C.green,fontWeight:'800'},danger:{color:C.coral,fontWeight:'800'}
});
export function Button({title,onPress,secondary=false,disabled=false}:{title:string,onPress:()=>void,secondary?:boolean,disabled?:boolean}){return <Pressable disabled={disabled} style={[secondary?S.secondaryButton:S.button,disabled&&{opacity:.45}]} onPress={onPress}><Text style={secondary?S.secondaryText:S.buttonText}>{title}</Text></Pressable>}
export function Field({value,onChangeText,placeholder,secure=false}:{value:string,onChangeText:(s:string)=>void,placeholder:string,secure?:boolean}){return <TextInput value={value} onChangeText={onChangeText} placeholder={placeholder} secureTextEntry={secure} style={S.input} autoCapitalize="none"/>}
export function Money({minor,currency='CNY'}:{minor:number,currency?:string}){return <Text style={S.price}>{currency==='CNY'?'¥':currency+' '}{(Number(minor||0)/100).toLocaleString(undefined,{minimumFractionDigits:0,maximumFractionDigits:2})}</Text>}
export function Pill({children}:{children:React.ReactNode}){return <View style={S.pill}><Text style={S.pillText}>{children}</Text></View>}
