"""Sprint 3N recovery experimentation and production calibration
Revision ID: 0035_sprint3n
Revises: 0034_sprint3m
"""
from alembic import op
import sqlalchemy as sa
revision='0035_sprint3n';down_revision='0034_sprint3m';branch_labels=None;depends_on=None

def upgrade():
    op.create_table('journey_recovery_experiment',sa.Column('experiment_id',sa.String(64),primary_key=True),sa.Column('name',sa.String(128),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('control_strategy_version_id',sa.String(64),nullable=False),sa.Column('candidate_strategy_version_id',sa.String(64),nullable=False),sa.Column('allocation_percent',sa.Integer(),nullable=False),sa.Column('min_sample_per_arm',sa.Integer(),nullable=False),sa.Column('significance_alpha',sa.Float(),nullable=False),sa.Column('primary_metric',sa.String(64),nullable=False),sa.Column('stratification_json',sa.JSON(),nullable=False),sa.Column('promotion_gate_json',sa.JSON(),nullable=False),sa.Column('approved_by',sa.String(64)),sa.Column('approved_at',sa.DateTime(timezone=True)),sa.Column('started_at',sa.DateTime(timezone=True)),sa.Column('ended_at',sa.DateTime(timezone=True)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    for c in ('state','control_strategy_version_id','candidate_strategy_version_id','approved_by'):op.create_index(f'ix_jrex_{c}','journey_recovery_experiment',[c])
    op.create_table('journey_recovery_experiment_observation',sa.Column('observation_id',sa.String(64),primary_key=True),sa.Column('experiment_id',sa.String(64),nullable=False),sa.Column('execution_item_id',sa.String(64),nullable=False),sa.Column('arm',sa.String(16),nullable=False),sa.Column('vertical',sa.String(32)),sa.Column('adapter_key',sa.String(96)),sa.Column('confirmed',sa.Boolean(),nullable=False),sa.Column('timeout',sa.Boolean(),nullable=False),sa.Column('manual_review',sa.Boolean(),nullable=False),sa.Column('confirmation_seconds',sa.Float()),sa.Column('metrics_json',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('experiment_id','execution_item_id',name='uq_jreo_experiment_item'))
    for c in ('experiment_id','execution_item_id','arm','vertical','adapter_key','created_at'):op.create_index(f'ix_jreo_{c}','journey_recovery_experiment_observation',[c])
    op.create_table('journey_recovery_experiment_decision',sa.Column('decision_id',sa.String(64),primary_key=True),sa.Column('experiment_id',sa.String(64),nullable=False),sa.Column('decision',sa.String(32),nullable=False),sa.Column('metrics_json',sa.JSON(),nullable=False),sa.Column('significance_json',sa.JSON(),nullable=False),sa.Column('strata_json',sa.JSON(),nullable=False),sa.Column('gate_results_json',sa.JSON(),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    for c in ('experiment_id','decision','created_at'):op.create_index(f'ix_jred_{c}','journey_recovery_experiment_decision',[c])
    op.create_table('journey_recovery_calibration_profile',sa.Column('calibration_profile_id',sa.String(96),primary_key=True),sa.Column('vertical',sa.String(32),nullable=False),sa.Column('adapter_key',sa.String(96),nullable=False),sa.Column('sample_count',sa.Integer(),nullable=False),sa.Column('source_experiment_id',sa.String(64)),sa.Column('calibrated_parameters_json',sa.JSON(),nullable=False),sa.Column('confidence_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('vertical','adapter_key',name='uq_jrcp_vertical_adapter'))
    for c in ('vertical','adapter_key','source_experiment_id','state'):op.create_index(f'ix_jrcp_{c}','journey_recovery_calibration_profile',[c])

def downgrade():
    op.drop_table('journey_recovery_calibration_profile');op.drop_table('journey_recovery_experiment_decision');op.drop_table('journey_recovery_experiment_observation');op.drop_table('journey_recovery_experiment')
