"""Sprint 3O production learning registry provenance benchmark governance
Revision ID: 0036_sprint3o
Revises: 0035_sprint3n
"""
from alembic import op
import sqlalchemy as sa
revision='0036_sprint3o';down_revision='0035_sprint3n';branch_labels=None;depends_on=None

def upgrade():
    op.create_table('journey_recovery_learning_registry',sa.Column('learning_registry_id',sa.String(64),primary_key=True),sa.Column('vertical',sa.String(32),nullable=False),sa.Column('adapter_key',sa.String(96),nullable=False),sa.Column('reliability_profile_id',sa.String(96)),sa.Column('strategy_version_id',sa.String(64)),sa.Column('experiment_id',sa.String(64)),sa.Column('calibration_profile_id',sa.String(96)),sa.Column('benchmark_profile_id',sa.String(96)),sa.Column('state',sa.String(32),nullable=False),sa.Column('freshness_state',sa.String(32),nullable=False),sa.Column('valid_until',sa.DateTime(timezone=True)),sa.Column('revalidation_required',sa.Boolean(),nullable=False),sa.Column('provenance_hash',sa.String(64),nullable=False),sa.Column('governance_json',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('vertical','adapter_key',name='uq_jrlr_vertical_adapter'))
    for c in ('vertical','adapter_key','reliability_profile_id','strategy_version_id','experiment_id','calibration_profile_id','benchmark_profile_id','state','freshness_state','valid_until','provenance_hash'):op.create_index(f'ix_jrlr_{c}','journey_recovery_learning_registry',[c])
    op.create_table('journey_recovery_provenance_edge',sa.Column('provenance_edge_id',sa.String(64),primary_key=True),sa.Column('learning_registry_id',sa.String(64),nullable=False),sa.Column('from_kind',sa.String(48),nullable=False),sa.Column('from_id',sa.String(96),nullable=False),sa.Column('to_kind',sa.String(48),nullable=False),sa.Column('to_id',sa.String(96),nullable=False),sa.Column('relation',sa.String(48),nullable=False),sa.Column('edge_hash',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    for c in ('learning_registry_id','from_kind','from_id','to_kind','to_id','relation','created_at'):op.create_index(f'ix_jrpe_{c}','journey_recovery_provenance_edge',[c])
    op.create_table('journey_recovery_benchmark_profile',sa.Column('benchmark_profile_id',sa.String(96),primary_key=True),sa.Column('vertical',sa.String(32),nullable=False),sa.Column('cohort_key',sa.String(96),nullable=False),sa.Column('supplier_count',sa.Integer(),nullable=False),sa.Column('sample_count',sa.Integer(),nullable=False),sa.Column('anonymization_k',sa.Integer(),nullable=False),sa.Column('benchmark_metrics_json',sa.JSON(),nullable=False),sa.Column('confidence_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('calculated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('valid_until',sa.DateTime(timezone=True),nullable=False),sa.UniqueConstraint('vertical','cohort_key',name='uq_jrbp_vertical_cohort'))
    for c in ('vertical','cohort_key','state','calculated_at','valid_until'):op.create_index(f'ix_jrbp_{c}','journey_recovery_benchmark_profile',[c])
    op.create_table('journey_recovery_drift_assessment',sa.Column('drift_assessment_id',sa.String(64),primary_key=True),sa.Column('learning_registry_id',sa.String(64),nullable=False),sa.Column('vertical',sa.String(32),nullable=False),sa.Column('adapter_key',sa.String(96),nullable=False),sa.Column('baseline_window_json',sa.JSON(),nullable=False),sa.Column('current_window_json',sa.JSON(),nullable=False),sa.Column('drift_metrics_json',sa.JSON(),nullable=False),sa.Column('drift_detected',sa.Boolean(),nullable=False),sa.Column('severity',sa.String(16),nullable=False),sa.Column('action',sa.String(32),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    for c in ('learning_registry_id','vertical','adapter_key','drift_detected','severity','action','created_at'):op.create_index(f'ix_jrda_{c}','journey_recovery_drift_assessment',[c])

def downgrade():
    op.drop_table('journey_recovery_drift_assessment');op.drop_table('journey_recovery_benchmark_profile');op.drop_table('journey_recovery_provenance_edge');op.drop_table('journey_recovery_learning_registry')
