"""Sprint 4B transparency gossip, witness federation, trust recovery.
Revision ID: 0049_sprint4b
Revises: 0048_sprint4a
"""
from alembic import op
import sqlalchemy as sa
revision='0049_sprint4b';down_revision='0048_sprint4a';branch_labels=None;depends_on=None

def _immutable(table):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_GOSSIP_TRUST_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_GOSSIP_TRUST_EVIDENCE'); END;")
    elif d=='postgresql':
        op.execute("""CREATE OR REPLACE FUNCTION deny_gossip_trust_evidence_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'IMMUTABLE_GOSSIP_TRUST_EVIDENCE'; END; $$ LANGUAGE plpgsql;""")
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_gossip_trust_evidence_mutation();")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_gossip_trust_evidence_mutation();")

def upgrade():
    op.create_table('journey_recovery_checkpoint_gossip',sa.Column('checkpoint_gossip_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('observer_key',sa.String(128),nullable=False),sa.Column('region_key',sa.String(64),nullable=False),sa.Column('tree_size',sa.Integer(),nullable=False),sa.Column('root_hash',sa.String(64),nullable=False),sa.Column('checkpoint_hash',sa.String(64),nullable=False),sa.Column('evidence_reference',sa.String(256),nullable=False),sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_witness_federation',sa.Column('witness_federation_id',sa.String(64),primary_key=True),sa.Column('federation_key',sa.String(128),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('environment',sa.String(16),nullable=False),sa.Column('witness_ids_json',sa.JSON(),nullable=False),sa.Column('minimum_quorum',sa.Integer(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_by',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_consistency_proof',sa.Column('consistency_proof_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('old_checkpoint_id',sa.String(64),nullable=False),sa.Column('new_checkpoint_id',sa.String(64),nullable=False),sa.Column('old_tree_size',sa.Integer(),nullable=False),sa.Column('new_tree_size',sa.Integer(),nullable=False),sa.Column('old_root_hash',sa.String(64),nullable=False),sa.Column('new_root_hash',sa.String(64),nullable=False),sa.Column('old_leaf_hashes_json',sa.JSON(),nullable=False),sa.Column('appended_leaf_hashes_json',sa.JSON(),nullable=False),sa.Column('proof_hash',sa.String(64),nullable=False),sa.Column('verification_state',sa.String(24),nullable=False),sa.Column('created_by',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_split_view_incident',sa.Column('split_view_incident_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('tree_size',sa.Integer(),nullable=False),sa.Column('observer_states_json',sa.JSON(),nullable=False),sa.Column('conflicting_checkpoint_hashes_json',sa.JSON(),nullable=False),sa.Column('affected_regions_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('severity',sa.String(16),nullable=False),sa.Column('evidence_reference',sa.String(256),nullable=False),sa.Column('opened_by',sa.String(64),nullable=False),sa.Column('opened_at',sa.DateTime(timezone=True),nullable=False),sa.Column('resolved_at',sa.DateTime(timezone=True)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_region_isolation',sa.Column('region_isolation_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('region_key',sa.String(64),nullable=False),sa.Column('split_view_incident_id',sa.String(64),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('reason_code',sa.String(64),nullable=False),sa.Column('isolated_by',sa.String(64),nullable=False),sa.Column('isolated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('rejoined_at',sa.DateTime(timezone=True)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_trust_recovery',sa.Column('trust_recovery_id',sa.String(64),primary_key=True),sa.Column('split_view_incident_id',sa.String(64),nullable=False),sa.Column('environment',sa.String(16),nullable=False),sa.Column('region_key',sa.String(64),nullable=False),sa.Column('target_checkpoint_id',sa.String(64),nullable=False),sa.Column('consistency_proof_id',sa.String(64),nullable=False),sa.Column('witness_federation_id',sa.String(64),nullable=False),sa.Column('witness_quorum_count',sa.Integer(),nullable=False),sa.Column('evidence_reference',sa.String(256),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('requested_at',sa.DateTime(timezone=True),nullable=False),sa.Column('completed_at',sa.DateTime(timezone=True)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_checkpoint_gossip','journey_recovery_consistency_proof']:_immutable(t)

def downgrade():
    for t in ['journey_recovery_trust_recovery','journey_recovery_region_isolation','journey_recovery_split_view_incident','journey_recovery_consistency_proof','journey_recovery_witness_federation','journey_recovery_checkpoint_gossip']:
        op.drop_table(t)
