"""Sprint 4I enterprise risk appetite and stress testing.
Revision ID: 0056_sprint4i
Revises: 0055_sprint4h
"""
from alembic import op
import sqlalchemy as sa
revision='0056_sprint4i';down_revision='0055_sprint4h';branch_labels=None;depends_on=None

def _immutable(table):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_RISK_APPETITE_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_RISK_APPETITE_EVIDENCE'); END;")
    elif d=='postgresql':
        op.execute("""CREATE OR REPLACE FUNCTION deny_risk_appetite_evidence_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'IMMUTABLE_RISK_APPETITE_EVIDENCE'; END; $$ LANGUAGE plpgsql;""")
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_risk_appetite_evidence_mutation();")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_risk_appetite_evidence_mutation();")

def upgrade():
    op.create_table('journey_recovery_risk_appetite_envelope',sa.Column('risk_appetite_envelope_id',sa.String(64),primary_key=True),sa.Column('appetite_key',sa.String(128),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('environment',sa.String(16),nullable=False),sa.Column('max_current_exposure_points',sa.Float(),nullable=False),sa.Column('max_stressed_exposure_points',sa.Float(),nullable=False),sa.Column('min_headroom_points',sa.Float(),nullable=False),sa.Column('min_capacity_buffer_pct',sa.Float(),nullable=False),sa.Column('max_sensitivity_pct',sa.Float(),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('board_approver_one',sa.String(64)),sa.Column('board_approver_two',sa.String(64)),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_stress_scenario',sa.Column('stress_scenario_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('scenario_key',sa.String(128),nullable=False),sa.Column('scenario_type',sa.String(32),nullable=False),sa.Column('shock_multiplier',sa.Float(),nullable=False),sa.Column('correlation_amplifier',sa.Float(),nullable=False),sa.Column('affected_correlation_keys_json',sa.JSON(),nullable=False),sa.Column('affected_risk_domains_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_by',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_stress_assessment',sa.Column('stress_assessment_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('risk_appetite_envelope_id',sa.String(64),nullable=False),sa.Column('portfolio_assessment_id',sa.String(64),nullable=False),sa.Column('scenario_ids_json',sa.JSON(),nullable=False),sa.Column('current_exposure_points',sa.Float(),nullable=False),sa.Column('stressed_exposure_points',sa.Float(),nullable=False),sa.Column('headroom_points',sa.Float(),nullable=False),sa.Column('capacity_buffer_pct',sa.Float(),nullable=False),sa.Column('sensitivity_pct',sa.Float(),nullable=False),sa.Column('assessment_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('metrics_json',sa.JSON(),nullable=False),sa.Column('assessed_by',sa.String(64),nullable=False),sa.Column('assessed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_capacity_buffer',sa.Column('capacity_buffer_id',sa.String(64),primary_key=True),sa.Column('stress_assessment_id',sa.String(64),nullable=False),sa.Column('dimension',sa.String(32),nullable=False),sa.Column('dimension_key',sa.String(128),nullable=False),sa.Column('baseline_exposure_points',sa.Float(),nullable=False),sa.Column('stressed_exposure_points',sa.Float(),nullable=False),sa.Column('sensitivity_pct',sa.Float(),nullable=False),sa.Column('headroom_points',sa.Float(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_stress_preemptive_freeze',sa.Column('stress_freeze_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('source_stress_assessment_id',sa.String(64),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('activated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('released_at',sa.DateTime(timezone=True)),sa.Column('released_by',sa.String(64)),sa.Column('release_evidence_reference',sa.String(256)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_appetite_event',sa.Column('risk_appetite_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('stress_assessment_id',sa.String(64)),sa.Column('stress_freeze_id',sa.String(64)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_risk_stress_assessment','journey_recovery_risk_capacity_buffer','journey_recovery_risk_appetite_event']:_immutable(t)

def downgrade():
    for t in ['journey_recovery_risk_appetite_event','journey_recovery_stress_preemptive_freeze','journey_recovery_risk_capacity_buffer','journey_recovery_risk_stress_assessment','journey_recovery_risk_stress_scenario','journey_recovery_risk_appetite_envelope']:op.drop_table(t)
