"""GO Consumer Growth + Official Direct Value Constitution V5.3.

Adds market benchmark evidence, supplier-funded official-direct value, channel-economics
memory and consumer cellular growth attribution. Recommendation/Judgment tables are not
modified: commercial value cannot buy recommendation.
"""
from alembic import op
import sqlalchemy as sa
revision='0110_7012f1955180'
down_revision='0109_bf96588075fe'
branch_labels=None
depends_on=None

def _idx(table,names):
    for name,cols in names: op.create_index(name,table,cols,unique=False)

def _immutable(table,code):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, '{code}'); END")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, '{code}'); END")
    elif d=='postgresql':
        fn=f'deny_{table}_mutation';op.execute(f"CREATE OR REPLACE FUNCTION {fn}() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION '{code}'; END; $$ LANGUAGE plpgsql")
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION {fn}()")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION {fn}()")

def _drop_immutable(table):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f'DROP TRIGGER IF EXISTS {table}_deny_update');op.execute(f'DROP TRIGGER IF EXISTS {table}_deny_delete')
    elif d=='postgresql':
        fn=f'deny_{table}_mutation';op.execute(f'DROP TRIGGER IF EXISTS {table}_deny_update ON {table}');op.execute(f'DROP TRIGGER IF EXISTS {table}_deny_delete ON {table}');op.execute(f'DROP FUNCTION IF EXISTS {fn}()')

def upgrade():
    op.create_table('direct_value_offer',
      sa.Column('direct_value_offer_id',sa.String(64),primary_key=True),sa.Column('supplier_id',sa.String(64),nullable=False),sa.Column('hotel_id',sa.String(64),nullable=False),sa.Column('status',sa.String(24),nullable=False),
      sa.Column('cash_discount_bps',sa.Integer(),nullable=False,server_default='0'),sa.Column('upgrade_priority',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('late_checkout_priority',sa.Boolean(),nullable=False,server_default=sa.false()),sa.Column('late_checkout_time',sa.String(8)),
      sa.Column('breakfast_option',sa.String(24),nullable=False,server_default='NONE'),sa.Column('benefits_json',sa.JSON(),nullable=False),sa.Column('supplier_incremental_cost_minor',sa.Integer(),nullable=False,server_default='0'),sa.Column('consumer_perceived_value_minor',sa.Integer(),nullable=False,server_default='0'),sa.Column('currency',sa.String(3),nullable=False),sa.Column('starts_at',sa.DateTime(timezone=True)),sa.Column('ends_at',sa.DateTime(timezone=True)),sa.Column('authorization_reference',sa.String(160),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    _idx('direct_value_offer',[('ix_direct_value_offer_supplier_id',['supplier_id']),('ix_direct_value_offer_hotel_id',['hotel_id']),('ix_direct_value_offer_status',['status']),('ix_direct_value_offer_starts_at',['starts_at']),('ix_direct_value_offer_ends_at',['ends_at']),('ix_direct_value_offer_created_at',['created_at']),('ix_direct_value_offer_hotel_status',['hotel_id','status'])])
    op.create_table('market_benchmark_quote',
      sa.Column('benchmark_quote_id',sa.String(64),primary_key=True),sa.Column('hotel_id',sa.String(64),nullable=False),sa.Column('source_provider',sa.String(64),nullable=False),sa.Column('source_type',sa.String(32),nullable=False),sa.Column('check_in',sa.String(10),nullable=False),sa.Column('check_out',sa.String(10),nullable=False),sa.Column('room_type_key',sa.String(128),nullable=False),sa.Column('occupancy_key',sa.String(64),nullable=False),sa.Column('meal_plan_key',sa.String(64),nullable=False),sa.Column('cancellation_key',sa.String(128),nullable=False),sa.Column('tax_fee_key',sa.String(64),nullable=False),sa.Column('eligibility_key',sa.String(128),nullable=False),sa.Column('total_amount_minor',sa.Integer(),nullable=False),sa.Column('currency',sa.String(3),nullable=False),sa.Column('comparable_fingerprint',sa.String(64),nullable=False),sa.Column('authorized_for_consumer',sa.Boolean(),nullable=False),sa.Column('captured_at',sa.DateTime(timezone=True),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True)),sa.Column('evidence_json',sa.JSON(),nullable=False))
    _idx('market_benchmark_quote',[('ix_market_benchmark_quote_hotel_id',['hotel_id']),('ix_market_benchmark_quote_source_provider',['source_provider']),('ix_market_benchmark_quote_source_type',['source_type']),('ix_market_benchmark_quote_check_in',['check_in']),('ix_market_benchmark_quote_comparable_fingerprint',['comparable_fingerprint']),('ix_market_benchmark_quote_captured_at',['captured_at']),('ix_market_benchmark_quote_expires_at',['expires_at']),('ix_market_benchmark_hotel_capture',['hotel_id','captured_at'])])
    op.create_table('supplier_channel_economics',
      sa.Column('channel_economics_id',sa.String(64),primary_key=True),sa.Column('supplier_id',sa.String(64),nullable=False),sa.Column('hotel_id',sa.String(64),nullable=False),sa.Column('direct_value_offer_id',sa.String(64)),sa.Column('direct_rate_minor',sa.Integer(),nullable=False),sa.Column('market_rate_minor',sa.Integer()),sa.Column('ota_channel_cost_bps',sa.Integer(),nullable=False),sa.Column('go_direct_cost_bps',sa.Integer(),nullable=False),sa.Column('cash_discount_bps',sa.Integer(),nullable=False),sa.Column('consumer_value_shared_minor',sa.Integer(),nullable=False),sa.Column('supplier_incremental_cost_minor',sa.Integer(),nullable=False),sa.Column('ota_net_revenue_minor',sa.Integer()),sa.Column('go_net_revenue_minor',sa.Integer(),nullable=False),sa.Column('net_revenue_uplift_minor',sa.Integer()),sa.Column('currency',sa.String(3),nullable=False),sa.Column('assumptions_json',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    _idx('supplier_channel_economics',[('ix_supplier_channel_economics_supplier_id',['supplier_id']),('ix_supplier_channel_economics_hotel_id',['hotel_id']),('ix_supplier_channel_economics_direct_value_offer_id',['direct_value_offer_id']),('ix_supplier_channel_economics_created_at',['created_at'])])
    op.create_table('direct_value_recommendation',
      sa.Column('direct_value_recommendation_id',sa.String(64),primary_key=True),sa.Column('supplier_id',sa.String(64),nullable=False),sa.Column('hotel_id',sa.String(64),nullable=False),sa.Column('direct_value_offer_id',sa.String(64)),sa.Column('recommendation_type',sa.String(40),nullable=False),sa.Column('proposed_cash_discount_bps',sa.Integer(),nullable=False),sa.Column('proposed_benefits_json',sa.JSON(),nullable=False),sa.Column('consumer_perceived_value_minor',sa.Integer(),nullable=False),sa.Column('supplier_incremental_cost_minor',sa.Integer(),nullable=False),sa.Column('value_efficiency_bps',sa.Integer(),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('recommendation_pool_unchanged',sa.Boolean(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False))
    _idx('direct_value_recommendation',[('ix_direct_value_recommendation_supplier_id',['supplier_id']),('ix_direct_value_recommendation_hotel_id',['hotel_id']),('ix_direct_value_recommendation_direct_value_offer_id',['direct_value_offer_id']),('ix_direct_value_recommendation_recommendation_type',['recommendation_type']),('ix_direct_value_recommendation_created_at',['created_at'])])
    op.create_table('consumer_growth_event',
      sa.Column('growth_event_id',sa.String(64),primary_key=True),sa.Column('user_id',sa.String(64)),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('source_surface',sa.String(64)),sa.Column('object_type',sa.String(48)),sa.Column('object_id',sa.String(96)),sa.Column('referrer_user_id',sa.String(64)),sa.Column('journey_id',sa.String(64)),sa.Column('supplier_id',sa.String(64)),sa.Column('metadata_json',sa.JSON(),nullable=False),sa.Column('occurred_at',sa.DateTime(timezone=True),nullable=False))
    _idx('consumer_growth_event',[('ix_consumer_growth_event_user_id',['user_id']),('ix_consumer_growth_event_event_type',['event_type']),('ix_consumer_growth_event_source_surface',['source_surface']),('ix_consumer_growth_event_object_type',['object_type']),('ix_consumer_growth_event_object_id',['object_id']),('ix_consumer_growth_event_referrer_user_id',['referrer_user_id']),('ix_consumer_growth_event_journey_id',['journey_id']),('ix_consumer_growth_event_supplier_id',['supplier_id']),('ix_consumer_growth_event_occurred_at',['occurred_at']),('ix_growth_event_user_time',['user_id','occurred_at'])])
    op.create_table('consumer_growth_attribution',
      sa.Column('growth_attribution_id',sa.String(64),primary_key=True),sa.Column('user_id',sa.String(64),nullable=False),sa.Column('acquisition_source',sa.String(64)),sa.Column('registration_trigger',sa.String(64)),sa.Column('activation_trigger',sa.String(64)),sa.Column('referrer_user_id',sa.String(64)),sa.Column('supplier_id',sa.String(64)),sa.Column('first_seen_at',sa.DateTime(timezone=True),nullable=False),sa.Column('registered_at',sa.DateTime(timezone=True)),sa.Column('activated_at',sa.DateTime(timezone=True)),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    _idx('consumer_growth_attribution',[('ix_consumer_growth_attribution_user_id',['user_id']),('ix_consumer_growth_attribution_acquisition_source',['acquisition_source']),('ix_consumer_growth_attribution_registration_trigger',['registration_trigger']),('ix_consumer_growth_attribution_activation_trigger',['activation_trigger']),('ix_consumer_growth_attribution_referrer_user_id',['referrer_user_id']),('ix_consumer_growth_attribution_supplier_id',['supplier_id']),('ix_consumer_growth_attribution_activated_at',['activated_at']),('ix_growth_attribution_user_activation',['user_id','activated_at'])])
    op.create_index('uq_consumer_growth_attribution_user','consumer_growth_attribution',['user_id'],unique=True)
    op.create_table('consumer_trip_member',
      sa.Column('trip_member_id',sa.String(64),primary_key=True),sa.Column('journey_id',sa.String(64),nullable=False),sa.Column('user_id',sa.String(64),nullable=False),sa.Column('role',sa.String(24),nullable=False),sa.Column('status',sa.String(24),nullable=False),sa.Column('source_invitation_id',sa.String(64)),sa.Column('joined_at',sa.DateTime(timezone=True),nullable=False))
    _idx('consumer_trip_member',[('ix_consumer_trip_member_journey_id',['journey_id']),('ix_consumer_trip_member_user_id',['user_id']),('ix_consumer_trip_member_status',['status']),('ix_consumer_trip_member_source_invitation_id',['source_invitation_id']),('ix_consumer_trip_member_joined_at',['joined_at'])]);op.create_index('uq_consumer_trip_member_journey_user','consumer_trip_member',['journey_id','user_id'],unique=True)
    op.create_table('consumer_trip_invitation',
      sa.Column('invitation_id',sa.String(64),primary_key=True),sa.Column('journey_id',sa.String(64),nullable=False),sa.Column('inviter_user_id',sa.String(64),nullable=False),sa.Column('invite_token_hash',sa.String(64),nullable=False),sa.Column('invitee_hint_hash',sa.String(64)),sa.Column('status',sa.String(24),nullable=False),sa.Column('joined_user_id',sa.String(64)),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('joined_at',sa.DateTime(timezone=True)))
    _idx('consumer_trip_invitation',[('ix_consumer_trip_invitation_journey_id',['journey_id']),('ix_consumer_trip_invitation_inviter_user_id',['inviter_user_id']),('ix_consumer_trip_invitation_invite_token_hash',['invite_token_hash']),('ix_consumer_trip_invitation_invitee_hint_hash',['invitee_hint_hash']),('ix_consumer_trip_invitation_status',['status']),('ix_consumer_trip_invitation_joined_user_id',['joined_user_id']),('ix_consumer_trip_invitation_expires_at',['expires_at'])]);op.create_index('uq_consumer_trip_invitation_token','consumer_trip_invitation',['invite_token_hash'],unique=True)
    op.create_table('traveler_claim',
      sa.Column('traveler_claim_id',sa.String(64),primary_key=True),sa.Column('traveler_id',sa.String(64),nullable=False),sa.Column('owner_user_id',sa.String(64),nullable=False),sa.Column('target_email_hash',sa.String(64),nullable=False),sa.Column('claim_token_hash',sa.String(64),nullable=False),sa.Column('status',sa.String(24),nullable=False),sa.Column('claimed_user_id',sa.String(64)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('expires_at',sa.DateTime(timezone=True),nullable=False),sa.Column('claimed_at',sa.DateTime(timezone=True)))
    _idx('traveler_claim',[('ix_traveler_claim_traveler_id',['traveler_id']),('ix_traveler_claim_owner_user_id',['owner_user_id']),('ix_traveler_claim_target_email_hash',['target_email_hash']),('ix_traveler_claim_claim_token_hash',['claim_token_hash']),('ix_traveler_claim_status',['status']),('ix_traveler_claim_claimed_user_id',['claimed_user_id']),('ix_traveler_claim_expires_at',['expires_at'])]);op.create_index('uq_traveler_claim_token','traveler_claim',['claim_token_hash'],unique=True)
    op.create_table('trip_import_intent',
      sa.Column('trip_import_intent_id',sa.String(64),primary_key=True),sa.Column('user_id',sa.String(64),nullable=False),sa.Column('source_type',sa.String(48),nullable=False),sa.Column('source_provider',sa.String(96)),sa.Column('source_reference',sa.Text()),sa.Column('content_hash',sa.String(64),nullable=False),sa.Column('status',sa.String(32),nullable=False),sa.Column('detected_verticals_json',sa.JSON(),nullable=False),sa.Column('created_journey_id',sa.String(64)),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False))
    _idx('trip_import_intent',[('ix_trip_import_intent_user_id',['user_id']),('ix_trip_import_intent_source_type',['source_type']),('ix_trip_import_intent_source_provider',['source_provider']),('ix_trip_import_intent_content_hash',['content_hash']),('ix_trip_import_intent_status',['status']),('ix_trip_import_intent_created_journey_id',['created_journey_id']),('ix_trip_import_intent_created_at',['created_at'])])
    for t,c in [('market_benchmark_quote','IMMUTABLE_MARKET_BENCHMARK_EVIDENCE'),('supplier_channel_economics','IMMUTABLE_CHANNEL_ECONOMICS_EVIDENCE'),('direct_value_recommendation','IMMUTABLE_DIRECT_VALUE_RECOMMENDATION'),('consumer_growth_event','IMMUTABLE_CONSUMER_GROWTH_EVENT')]:_immutable(t,c)

def downgrade():
    for t in ['consumer_growth_event','direct_value_recommendation','supplier_channel_economics','market_benchmark_quote']:_drop_immutable(t)
    for t in ['trip_import_intent','traveler_claim','consumer_trip_invitation','consumer_trip_member','consumer_growth_attribution','consumer_growth_event','direct_value_recommendation','supplier_channel_economics','market_benchmark_quote','direct_value_offer']:op.drop_table(t)
