"""Sprint 3T runtime observability burn rate and release safety controller
Revision ID: 0041_sprint3t
Revises: 0040_sprint3s
"""
from alembic import op
import sqlalchemy as sa
revision='0041_sprint3t';down_revision='0040_sprint3s';branch_labels=None;depends_on=None

def upgrade():
    op.create_table('journey_recovery_runtime_observation',sa.Column('runtime_observation_id',sa.String(64),primary_key=True),sa.Column('release_manifest_id',sa.String(64)),sa.Column('environment',sa.String(16),nullable=False),sa.Column('runtime_instance',sa.String(128),nullable=False),sa.Column('window_seconds',sa.Integer(),nullable=False),sa.Column('request_count',sa.Integer(),nullable=False),sa.Column('error_count',sa.Integer(),nullable=False),sa.Column('error_rate',sa.Float(),nullable=False),sa.Column('availability',sa.Float(),nullable=False),sa.Column('latency_p95_ms',sa.Float(),nullable=False),sa.Column('slo_target',sa.Float(),nullable=False),sa.Column('payload_json',sa.JSON(),nullable=False),sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False))
    op.create_table('journey_recovery_release_safety_assessment',sa.Column('safety_assessment_id',sa.String(64),primary_key=True),sa.Column('release_manifest_id',sa.String(64)),sa.Column('environment',sa.String(16),nullable=False),sa.Column('state',sa.String(32),nullable=False),sa.Column('short_burn_rate',sa.Float(),nullable=False),sa.Column('long_burn_rate',sa.Float(),nullable=False),sa.Column('error_budget_remaining',sa.Float(),nullable=False),sa.Column('release_correlated_anomaly',sa.Boolean(),nullable=False),sa.Column('anomaly_json',sa.JSON(),nullable=False),sa.Column('action',sa.String(48),nullable=False),sa.Column('assessed_by',sa.String(64),nullable=False),sa.Column('assessed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False))
    op.create_table('journey_recovery_release_safety_control',sa.Column('release_safety_control_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False,unique=True),sa.Column('promotion_frozen',sa.Boolean(),nullable=False),sa.Column('freeze_reason',sa.String(256)),sa.Column('source_assessment_id',sa.String(64)),sa.Column('updated_by',sa.String(64),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False))
    op.create_table('journey_recovery_rollback_recommendation',sa.Column('rollback_recommendation_id',sa.String(64),primary_key=True),sa.Column('safety_assessment_id',sa.String(64),nullable=False),sa.Column('release_manifest_id',sa.String(64),nullable=False),sa.Column('rollback_target_manifest_id',sa.String(64)),sa.Column('environment',sa.String(16),nullable=False),sa.Column('state',sa.String(32),nullable=False),sa.Column('reason_json',sa.JSON(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('acknowledged_by',sa.String(64)),sa.Column('acknowledged_at',sa.DateTime(timezone=True)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False))
    for t,cols,p in [('journey_recovery_runtime_observation',['release_manifest_id','environment','runtime_instance','observed_at'],'jrro'),('journey_recovery_release_safety_assessment',['release_manifest_id','environment','state','release_correlated_anomaly','action','assessed_at'],'jrrsa'),('journey_recovery_release_safety_control',['environment','promotion_frozen','source_assessment_id','updated_at'],'jrrsc'),('journey_recovery_rollback_recommendation',['safety_assessment_id','release_manifest_id','rollback_target_manifest_id','environment','state','created_at'],'jrrr')]:
        for c in cols: op.create_index(f'ix_{p}_{c}',t,[c])

def downgrade():
    op.drop_table('journey_recovery_rollback_recommendation');op.drop_table('journey_recovery_release_safety_control');op.drop_table('journey_recovery_release_safety_assessment');op.drop_table('journey_recovery_runtime_observation')
