"""Sprint 4J enterprise risk forecast and dynamic capacity.
Revision ID: 0057_sprint4j
Revises: 0056_sprint4i
"""
from alembic import op
import sqlalchemy as sa
revision='0057_sprint4j';down_revision='0056_sprint4i';branch_labels=None;depends_on=None

def _immutable(table):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_RISK_FORECAST_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_RISK_FORECAST_EVIDENCE'); END;")
    elif d=='postgresql':
        op.execute("""CREATE OR REPLACE FUNCTION deny_risk_forecast_evidence_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'IMMUTABLE_RISK_FORECAST_EVIDENCE'; END; $$ LANGUAGE plpgsql;""")
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_risk_forecast_evidence_mutation();")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_risk_forecast_evidence_mutation();")

def upgrade():
    op.create_table('journey_recovery_risk_forecast_policy',sa.Column('risk_forecast_policy_id',sa.String(64),primary_key=True),sa.Column('policy_key',sa.String(128),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('environment',sa.String(16),nullable=False),sa.Column('warning_capacity_utilization_pct',sa.Float(),nullable=False),sa.Column('restrict_capacity_utilization_pct',sa.Float(),nullable=False),sa.Column('reserve_capacity_pct',sa.Float(),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('board_approver_one',sa.String(64)),sa.Column('board_approver_two',sa.String(64)),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_indicator',sa.Column('risk_indicator_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('indicator_key',sa.String(128),nullable=False),sa.Column('indicator_type',sa.String(32),nullable=False),sa.Column('dimension',sa.String(32),nullable=False),sa.Column('dimension_key',sa.String(128)),sa.Column('observed_value',sa.Float(),nullable=False),sa.Column('threshold_value',sa.Float(),nullable=False),sa.Column('direction',sa.String(16),nullable=False),sa.Column('weight',sa.Float(),nullable=False),sa.Column('signal_state',sa.String(24),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('observed_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_forecast',sa.Column('risk_forecast_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('risk_forecast_policy_id',sa.String(64),nullable=False),sa.Column('horizon_hours',sa.Integer(),nullable=False),sa.Column('current_exposure_points',sa.Float(),nullable=False),sa.Column('projected_exposure_points',sa.Float(),nullable=False),sa.Column('projected_capacity_consumption_pct',sa.Float(),nullable=False),sa.Column('projected_headroom_points',sa.Float(),nullable=False),sa.Column('weighted_risk_signal',sa.Float(),nullable=False),sa.Column('forecast_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('inputs_json',sa.JSON(),nullable=False),sa.Column('forecasted_at',sa.DateTime(timezone=True),nullable=False),sa.Column('valid_until',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_dynamic_risk_capacity',sa.Column('risk_capacity_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('risk_forecast_id',sa.String(64),nullable=False),sa.Column('dimension',sa.String(32),nullable=False),sa.Column('dimension_key',sa.String(128),nullable=False),sa.Column('allocated_capacity_points',sa.Float(),nullable=False),sa.Column('current_exposure_points',sa.Float(),nullable=False),sa.Column('projected_exposure_points',sa.Float(),nullable=False),sa.Column('capacity_utilization_pct',sa.Float(),nullable=False),sa.Column('available_capacity_points',sa.Float(),nullable=False),sa.Column('allocation_state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_early_warning',sa.Column('early_warning_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('risk_forecast_id',sa.String(64),nullable=False),sa.Column('warning_type',sa.String(64),nullable=False),sa.Column('severity',sa.String(16),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('acknowledged_at',sa.DateTime(timezone=True)),sa.Column('acknowledged_by',sa.String(64)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_risk_restriction',sa.Column('forecast_restriction_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('source_risk_forecast_id',sa.String(64),nullable=False),sa.Column('restriction_scope',sa.String(64),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('activated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('released_at',sa.DateTime(timezone=True)),sa.Column('released_by',sa.String(64)),sa.Column('release_evidence_reference',sa.String(256)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_risk_forecast_event',sa.Column('risk_forecast_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('risk_forecast_id',sa.String(64)),sa.Column('forecast_restriction_id',sa.String(64)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_risk_indicator','journey_recovery_risk_forecast','journey_recovery_dynamic_risk_capacity','journey_recovery_risk_forecast_event']:_immutable(t)

def downgrade():
    for t in ['journey_recovery_risk_forecast_event','journey_recovery_forecast_risk_restriction','journey_recovery_risk_early_warning','journey_recovery_dynamic_risk_capacity','journey_recovery_risk_forecast','journey_recovery_risk_indicator','journey_recovery_risk_forecast_policy']:op.drop_table(t)
