"""Sprint 4N forecast drift detection, population stability and governed model refresh.
Revision ID: 0061_sprint4n
Revises: 0060_sprint4m
"""
from alembic import op
import sqlalchemy as sa
revision='0061_sprint4n';down_revision='0060_sprint4m';branch_labels=None;depends_on=None

def imm(table):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_FORECAST_DRIFT_GOVERNANCE_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_FORECAST_DRIFT_GOVERNANCE_EVIDENCE'); END;")
    elif d=='postgresql':
        op.execute("""CREATE OR REPLACE FUNCTION deny_forecast_drift_governance_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'IMMUTABLE_FORECAST_DRIFT_GOVERNANCE_EVIDENCE'; END; $$ LANGUAGE plpgsql;""")
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_forecast_drift_governance_mutation();")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_forecast_drift_governance_mutation();")

def upgrade():
    op.create_table('journey_recovery_forecast_drift_policy',sa.Column('forecast_drift_policy_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('minimum_sample_count',sa.Integer(),nullable=False),sa.Column('max_population_psi',sa.Float(),nullable=False),sa.Column('max_segment_psi',sa.Float(),nullable=False),sa.Column('max_residual_drift_pct',sa.Float(),nullable=False),sa.Column('consecutive_breaches_required',sa.Integer(),nullable=False),sa.Column('baseline_window_key',sa.String(64),nullable=False),sa.Column('comparison_window_key',sa.String(64),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('approver_one',sa.String(64)),sa.Column('approver_two',sa.String(64)),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_drift_assessment',sa.Column('forecast_drift_assessment_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('policy_id',sa.String(64),nullable=False),sa.Column('champion_model_version_id',sa.String(64),nullable=False),sa.Column('horizon_hours',sa.Integer(),nullable=False),sa.Column('sample_count',sa.Integer(),nullable=False),sa.Column('population_psi',sa.Float(),nullable=False),sa.Column('max_segment_psi',sa.Float(),nullable=False),sa.Column('residual_drift_pct',sa.Float(),nullable=False),sa.Column('drift_state',sa.String(24),nullable=False),sa.Column('segment_metrics_json',sa.JSON(),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evaluated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_retraining_request',sa.Column('forecast_retraining_request_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('source_drift_assessment_id',sa.String(64),nullable=False),sa.Column('champion_model_version_id',sa.String(64),nullable=False),sa.Column('requested_model_key',sa.String(128),nullable=False),sa.Column('refresh_reason_codes_json',sa.JSON(),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('requested_at',sa.DateTime(timezone=True),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_refresh_pipeline',sa.Column('forecast_refresh_pipeline_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('retraining_request_id',sa.String(64),nullable=False),sa.Column('source_champion_model_version_id',sa.String(64),nullable=False),sa.Column('challenger_model_version_id',sa.String(64)),sa.Column('pipeline_state',sa.String(32),nullable=False),sa.Column('governance_next_step',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_drift_event',sa.Column('forecast_drift_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('drift_assessment_id',sa.String(64)),sa.Column('retraining_request_id',sa.String(64)),sa.Column('challenger_model_version_id',sa.String(64)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_forecast_drift_assessment','journey_recovery_forecast_retraining_request','journey_recovery_forecast_refresh_pipeline','journey_recovery_forecast_drift_event']: imm(t)

def downgrade():
    for t in ['journey_recovery_forecast_drift_event','journey_recovery_forecast_refresh_pipeline','journey_recovery_forecast_retraining_request','journey_recovery_forecast_drift_assessment','journey_recovery_forecast_drift_policy']: op.drop_table(t)
