"""Sprint 4Q artifact deployment provenance and model serving attestation.
Revision ID: 0064_sprint4q
Revises: 0063_sprint4p
"""
from alembic import op
import sqlalchemy as sa
revision='0064_sprint4q';down_revision='0063_sprint4p';branch_labels=None;depends_on=None

def imm(table):
    d=op.get_bind().dialect.name
    if d=='sqlite':
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_FORECAST_SERVING_GOVERNANCE_EVIDENCE'); END;")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} BEGIN SELECT RAISE(ABORT, 'IMMUTABLE_FORECAST_SERVING_GOVERNANCE_EVIDENCE'); END;")
    elif d=='postgresql':
        op.execute("""CREATE OR REPLACE FUNCTION deny_forecast_serving_governance_mutation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'IMMUTABLE_FORECAST_SERVING_GOVERNANCE_EVIDENCE'; END; $$ LANGUAGE plpgsql;""")
        op.execute(f"CREATE TRIGGER {table}_deny_update BEFORE UPDATE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_forecast_serving_governance_mutation();")
        op.execute(f"CREATE TRIGGER {table}_deny_delete BEFORE DELETE ON {table} FOR EACH ROW EXECUTE FUNCTION deny_forecast_serving_governance_mutation();")

def upgrade():
    op.create_table('journey_recovery_forecast_serving_policy',sa.Column('forecast_serving_policy_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('version_no',sa.Integer(),nullable=False),sa.Column('require_serving_attestation',sa.Boolean(),nullable=False),sa.Column('require_runtime_fingerprint',sa.Boolean(),nullable=False),sa.Column('require_artifact_binding',sa.Boolean(),nullable=False),sa.Column('requested_by',sa.String(64),nullable=False),sa.Column('approver_one',sa.String(64)),sa.Column('approver_two',sa.String(64)),sa.Column('state',sa.String(24),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_artifact_deployment_binding',sa.Column('forecast_artifact_deployment_binding_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('model_version_id',sa.String(64),nullable=False),sa.Column('forecast_model_artifact_id',sa.String(64),nullable=False),sa.Column('forecast_artifact_promotion_binding_id',sa.String(64),nullable=False),sa.Column('deployment_key',sa.String(128),nullable=False),sa.Column('expected_artifact_digest',sa.String(64),nullable=False),sa.Column('expected_build_hash',sa.String(64),nullable=False),sa.Column('binding_hash',sa.String(64),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('bound_by',sa.String(64),nullable=False),sa.Column('bound_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_runtime_model_identity',sa.Column('forecast_runtime_model_identity_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('deployment_key',sa.String(128),nullable=False),sa.Column('runtime_instance_ref',sa.String(256),nullable=False),sa.Column('model_version_id',sa.String(64),nullable=False),sa.Column('forecast_model_artifact_id',sa.String(64),nullable=False),sa.Column('runtime_model_fingerprint',sa.String(64),nullable=False),sa.Column('state',sa.String(24),nullable=False),sa.Column('registered_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_model_serving_attestation',sa.Column('forecast_model_serving_attestation_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('forecast_artifact_deployment_binding_id',sa.String(64),nullable=False),sa.Column('forecast_runtime_model_identity_id',sa.String(64),nullable=False),sa.Column('model_version_id',sa.String(64),nullable=False),sa.Column('forecast_model_artifact_id',sa.String(64),nullable=False),sa.Column('expected_artifact_digest',sa.String(64),nullable=False),sa.Column('loaded_artifact_digest',sa.String(64),nullable=False),sa.Column('expected_build_hash',sa.String(64),nullable=False),sa.Column('loaded_build_hash',sa.String(64),nullable=False),sa.Column('expected_runtime_fingerprint',sa.String(64),nullable=False),sa.Column('observed_runtime_fingerprint',sa.String(64),nullable=False),sa.Column('attestation_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('evidence_reference',sa.String(512),nullable=False),sa.Column('attested_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_model_deployment_lineage',sa.Column('forecast_model_deployment_lineage_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('deployment_key',sa.String(128),nullable=False),sa.Column('previous_binding_id',sa.String(64)),sa.Column('current_binding_id',sa.String(64),nullable=False),sa.Column('transition_type',sa.String(24),nullable=False),sa.Column('transition_hash',sa.String(64),nullable=False),sa.Column('evidence_reference',sa.String(512),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_serving_safety_control',sa.Column('forecast_serving_safety_control_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('model_version_id',sa.String(64),nullable=False),sa.Column('deployment_key',sa.String(128),nullable=False),sa.Column('control_state',sa.String(24),nullable=False),sa.Column('reason_codes_json',sa.JSON(),nullable=False),sa.Column('activated_at',sa.DateTime(timezone=True),nullable=False),sa.Column('released_at',sa.DateTime(timezone=True)),sa.Column('release_evidence_reference',sa.String(512)),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    op.create_table('journey_recovery_forecast_serving_governance_event',sa.Column('forecast_serving_governance_event_id',sa.String(64),primary_key=True),sa.Column('environment',sa.String(16),nullable=False),sa.Column('event_type',sa.String(64),nullable=False),sa.Column('model_version_id',sa.String(64)),sa.Column('deployment_key',sa.String(128)),sa.Column('evidence_json',sa.JSON(),nullable=False),sa.Column('actor',sa.String(64),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),nullable=False),sa.Column('supplier_fact_unchanged',sa.Boolean(),nullable=False,server_default=sa.true()))
    for t in ['journey_recovery_forecast_artifact_deployment_binding','journey_recovery_forecast_runtime_model_identity','journey_recovery_forecast_model_serving_attestation','journey_recovery_forecast_model_deployment_lineage','journey_recovery_forecast_serving_governance_event']: imm(t)

def downgrade():
    for t in ['journey_recovery_forecast_serving_governance_event','journey_recovery_forecast_serving_safety_control','journey_recovery_forecast_model_deployment_lineage','journey_recovery_forecast_model_serving_attestation','journey_recovery_forecast_runtime_model_identity','journey_recovery_forecast_artifact_deployment_binding','journey_recovery_forecast_serving_policy']: op.drop_table(t)
