const $=s=>document.querySelector(s); let readiness=null,selected=null,prebook=null,order=null;
const roomCatalog=[
['go-aol-room-01','1 King Bed (Hunter hut Sunlit Reverie)','42 sq m','City View'],['go-aol-room-02','2 Twin Beds (Hunter hut Sunlit Reverie)','42 sq m','City View'],['go-aol-room-03','1 King Bed City View (Hunter hut Dreamweaver)','48 sq m','City View'],['go-aol-room-04','2 Twin Beds City View (Hunter hut Dreamweaver)','48 sq m','City View'],['go-aol-room-05','1 King Bed River View (Hunter hut Gaudium Fluminis)','48 sq m','River View'],['go-aol-room-06','2 Twin Beds River View (Hunter hut Gaudium Fluminis)','48 sq m','River View'],['go-aol-room-07','1 King Bed, Deluxe (Hunter hut Moonlit Repose)','60 sq m','City View'],['go-aol-room-08','2 Twin Beds, Deluxe (Hunter hut Moonlit Repose)','60 sq m','City View'],['go-aol-room-09','1 King Bed, Premium (Hunter hut Cloudspire Haven)','72 sq m','City View'],['go-aol-room-10','2 Twin Beds, Premium (Hunter hut Cloudspire Haven)','72 sq m','City View'],['go-aol-room-11','1 King Bed River View, Deluxe (Hunter hut Riverside Reverie)','72 sq m','River View'],['go-aol-room-12','2 Twin Beds River View, Deluxe (Hunter hut Riverside Reverie)','72 sq m','River View'],['go-aol-room-13','1 King Bed, Premier (Hunter hut Sunset Perch)','80 sq m','River View'],['go-aol-room-14','Hunter hut Stardust Trail 2 Bedroom Suite','98 sq m','River View'],['go-aol-room-15','Hunter hut Lunar Embrace Premium Suite King','150 sq m','River View'],['go-aol-room-16','Hunter hut Rainbow Archway Family Suite','200 sq m','River View'],['go-aol-room-17','Maria Suo Chieftain Retreat','300 sq m','River View']];
function csrf(){return document.cookie.split('; ').find(x=>x.startsWith('go_consumer_csrf='))?.split('=').slice(1).join('')||''}
async function api(path,opts={}){const method=(opts.method||'GET').toUpperCase(),headers={'Content-Type':'application/json',...(opts.headers||{})};const token=csrf();if(token&&!['GET','HEAD','OPTIONS'].includes(method))headers['X-CSRF-Token']=decodeURIComponent(token);const r=await fetch(path,{credentials:'include',...opts,method,headers});let b={};try{b=await r.json()}catch{}if(!r.ok)throw new Error(typeof b.detail==='string'?b.detail:JSON.stringify(b.detail||`HTTP_${r.status}`));return b.data??b}
const money=n=>new Intl.NumberFormat('zh-CN',{style:'currency',currency:'CNY',maximumFractionDigits:0}).format(Number(n||0)/100);
function initDates(){const a=new Date(),b=new Date();a.setDate(a.getDate()+1);b.setDate(b.getDate()+2);const f=d=>d.toISOString().slice(0,10);$('#ci').value=f(a);$('#co').value=f(b)}
function emptyRooms(message){$('#room-list').replaceChildren(...roomCatalog.map(([id,name,area,view])=>{const x=document.createElement('article');x.className='room';x.dataset.room=id;x.innerHTML=`<div class="room-head"><div><h3></h3><div class="facts"></div></div></div><div class="offers"><div class="offer"><div><span class="badge">官网房型</span><small></small></div></div></div>`;x.querySelector('h3').textContent=name;x.querySelector('.facts').textContent=`${area} · ${view}`;x.querySelector('.offer small').textContent=message;return x}))}
async function loadReadiness(){readiness=await api('/v1/direct/aoluguya-harbin/runtime-readiness');$('#env').textContent=readiness.test_mode?'STAGING · TEST ONLY':'生产能力未开启';if(!readiness.test_mode){$('#status').textContent=`${readiness.booking_status} / ${readiness.payment_status}`;emptyRooms(readiness.booking_status);return}$('#status').textContent='TEST ONLY：使用 GO Runtime 测试库存、测试报价和隔离测试支付。';emptyRooms('请选择日期查询 TEST ONLY 报价')}
async function search(){if(!readiness?.test_mode){$('#status').textContent='暂不可预订 / 支付未开通';return}const ci=$('#ci').value,co=$('#co').value;if(!ci||!co||co<=ci){$('#status').textContent='请选择有效入住/离店日期';return}$('#status').textContent='正在通过 HK GO API 查询测试库存与报价…';const data=await api('/v1/search/hotels',{method:'POST',body:JSON.stringify({destination:{city_code:'HRB'},stay:{check_in:ci,check_out:co},occupancy:{rooms:Number($('#rooms').value),adults:Number($('#adults').value),children:0},currency:'CNY'})});const hotel=(data.hotels||[]).find(x=>x.hotel_id==='HRBUB');const offers=hotel?.offers||[];const by=new Map();for(const o of offers){if(!by.has(o.canonical_room_id))by.set(o.canonical_room_id,[]);by.get(o.canonical_room_id).push(o)};emptyRooms('当前无测试报价');for(const [rid,os] of by){const box=document.querySelector(`[data-room="${rid}"] .offers`);if(!box)continue;box.replaceChildren();for(const o of os){const row=document.createElement('div');row.className='offer';const info=document.createElement('div');const title=document.createElement('strong');title.textContent=o.rate_plan_name;const small=document.createElement('small');small.textContent=`TEST ONLY · 库存 ${o.availability} · ${o.meal_plan} · ${o.cancellation_summary||''}`;info.append(title,small);const price=document.createElement('b');price.textContent=money(o.total_amount_minor);const btn=document.createElement('button');btn.textContent='选择测试报价';btn.onclick=()=>choose(o);row.append(info,price,btn);box.append(row)}}$('#status').textContent=`已从 GO Runtime 返回 ${offers.length} 个测试报价，覆盖 ${by.size}/17 个官网房型。`}
async function choose(o){selected=o;$('#status').textContent='正在通过 GO Prebook 重新校验…';prebook=await api(`/v1/offers/${encodeURIComponent(o.offer_id)}/prebook`,{method:'POST',body:JSON.stringify({currency:'CNY'})});order=await api('/v1/orders',{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({prebook_id:prebook.prebook_id,account_id:'acct_r31_test',guests:[],traveler_ids:[],vault_release_ids:[]})});$('#summary').replaceChildren();for(const [k,v] of [['房型',o.room_name],['报价',o.rate_plan_name],['Prebook',prebook.prebook_id],['GO Order',order.order_id],['应付测试金额',money(order.total_amount_minor)]]){const r=document.createElement('div');r.className='row';const a=document.createElement('span');a.textContent=k;const b=document.createElement('strong');b.textContent=v;r.append(a,b);$('#summary').append(r)}$('#checkout-status').textContent='测试订单已创建，尚未授权/扣款。';$('#modal').classList.add('open')}
async function pay(){if(!order)return;$('#checkout-status').textContent='执行隔离测试支付：授权 → 酒店测试库存原子扣减 → capture…';try{const done=await api(`/v1/consumer/orders/${encodeURIComponent(order.order_id)}/checkout`,{method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({payment_method_token:'pm_success'})});if(String(done.status)!=='CONFIRMED'||!done.supplier_confirmation_no)throw new Error('BOOKING_NOT_CONFIRMED');$('#checkout-status').className='status success';$('#checkout-status').textContent=`TEST CONFIRMED · ${done.supplier_confirmation_no} · 无真实资金/供应商调用`;await search()}catch(e){$('#checkout-status').className='status fail';$('#checkout-status').textContent='测试结算失败：'+e.message}}
$('#search').onclick=()=>search().catch(e=>$('#status').textContent='查询失败：'+e.message);$('#close').onclick=()=>$('#modal').classList.remove('open');$('#pay').onclick=()=>pay();initDates();loadReadiness().catch(e=>{$('#status').textContent='Runtime readiness 失败：'+e.message;emptyRooms('暂不可预订')});
window.__GO_R31_DIRECT__={search,choose,pay,get state(){return{readiness,selected,prebook,order}}};
